const words_serbian_verbs = [
  // Группа «А»
  ["Znati", "Знать; уметь", "ja znam | on zna | oni znaju (группа А)"],
  ["Odgovarati", "Отвечать", "ja odgovaram | on odgovara | oni odgovaraju (группа А)"],
  ["Pitati", "Спрашивать", "ja pitam | on pita | oni pitaju (группа А)"],
  ["Pevati", "Петь", "ja pevam | on peva | oni pevaju (группа А)"],
  ["Razgovarati", "Разговаривать", "ja razgovaram | on razgovara | oni razgovaraju (группа А)"],
  ["Gurati", "Толкать", "ja guram | on gura | oni guraju (группа А)"],
  ["Plivati", "Плавать", "ja plivam | on pliva | oni plivaju (группа А)"],
  ["Štampati", "Печатать", "ja štampam | on štampa | oni štampaju (группа А)"],
  ["Kucati", "Стучать", "ja kucam | on kuca | oni kucaju (группа А)"],
  ["Gledati", "Смотреть", "ja gledam | on gleda | oni gledaju (группа А)"],
  ["Čuvati", "Беречь; оберегать", "ja čuvam | on čuva | oni čuvaju (группа А)"],
  ["Uspevati", "Удаваться, получаться", "ja uspevam | on uspeva | oni uspevaju (группа А)"],
  ["Sklanjati", "Убирать; прятать", "ja sklanjam | on sklanja | oni sklanjaju (группа А)"],
  ["Postavljati", "Ставить; расставлять", "ja postavljam | on postavlja | oni postavljaju (группа А)"],
  ["Sipati", "Наливать; насыпать", "ja sipam | on sipa | oni sipaju (группа А)"],
  ["Kuvati", "Варить, готовить", "ja kuvam | on kuva | oni kuvaju (группа А)"],
  ["Spremati", "Готовить, подготавливать", "ja spremam | on sprema | oni spremaju (группа А)"],
  ["Čitati", "Читать", "ja čitam | on čita | oni čitaju (группа А)"],
  ["Plaćati", "Платить", "ja plaćam | on plaća | oni plaćaju (группа А)"],
  ["Smatrati", "Считать, полагать", "ja smatram | on smatra | oni smatraju (группа А)"],
  ["Spavati", "Спать", "ja spavam | on spava | oni spavaju (группа А)"],
  ["Ručati", "Обедать", "ja ručam | on ruča | oni ručaju (группа А)"],
  ["Večerati", "Ужинать", "ja večeram | on večera | oni večeraju (группа А)"],
  ["Ponavljati", "Повторять", "ja ponavljam | on ponavlja | oni ponavljaju (группа А)"],
  ["Otvarati", "Открывать", "ja otvaram | on otvara | oni otvaraju (группа А)"],
  ["Zatvarati", "Закрывать", "ja zatvaram | on zatvara | oni zatvaraju (группа А)"],
  ["Čekati", "Ждать", "ja čekam | on čeka | oni čekaju (группа А)"],
  ["Slikati", "Фотографировать; рисовать", "ja slikam | on slika | oni slikaju (группа А)"],
  ["Imati", "Иметь", "ja imam | on ima | oni imaju (группа А)"],
  ["Nemati", "Не иметь", "ja nemam | on nema | oni nemaju (группа А)"],
  ["Aplicirati", "Подавать заявку", "ja apliciram | on aplicira | oni apliciraju (группа А)"],
  ["Bacati", "Бросать", "ja bacam | on baca | oni bacaju (группа А)"],
  ["Računati", "Считать; рассчитывать", "ja računam | on računa | oni računaju (группа А)"],
  ["Uzimati", "Брать", "ja uzimam | on uzima | oni uzimaju (группа А)"],
  ["Birati", "Выбирать", "ja biram | on bira | oni biraju (группа А)"],
  ["Pokušavati", "Пытаться; пробовать", "ja pokušavam | on pokušava | oni pokušavaju (группа А)"],
  ["Probati", "Пробовать; примерять", "ja probam | on proba | oni probaju (группа А)"],
  ["Čestitati", "Поздравлять", "ja čestitam | on čestita | oni čestitaju (группа А)"],
  ["Fenirati se", "Укладывать волосы феном", "ja feniram se | on fenira se | oni feniraju se (группа А)"],
  ["Šetati se", "Гулять, прогуливаться", "ja šetam se | on šeta se | oni šetaju se (группа А)"],
  ["Skidati se", "Раздеваться", "ja skidam se | on skida se | oni skidaju se (группа А)"],
  ["Umivati se", "Умываться", "ja umivam se | on umiva se | oni umivaju se (группа А)"],
  ["Tuširati се", "Принимать душ", "ja tuširam se | on tušira se | oni tuširaju se (группа А)"],
  ["Kupati se", "Купаться", "ja kupam se | on kupa se | oni kupaju se (группа А)"],
  ["Svađati se", "Ссориться, ругаться", "ja svađam se | on svaђа se | oni svađaju se (группа А)"],

  // Группа «И»
  ["Ležati", "Лежать", "ja ležim | on leži | oni leže (группа И)"],
  ["Ćutati", "Молчать", "ja ćutim | on ćuti | oni ćute (группа И)"],
  ["Držati", "Держать", "ja držim | on drži | oni drže (группа И)"],
  ["Postojati", "Существовать", "ja postojim | on postoji | oni postoje (группа И)"],
  ["Trčati", "Бегать", "ja trčim | on trči | oni trče (группа И)"],
  ["Bežati", "Убегать", "ja bežim | on beži | oni beže (группа И)"],
  ["Stajati", "Стоять", "ja stojim | on stoji | oni stoje (группа И)"],
  ["Brojati", "Считать, пересчитывать", "ja brojim | on broji | oni broje (группа И)"],
  ["Bojati se", "Бояться, страшиться", "ja bojim se | on boji se | oni boje se (группа И)"],
  ["Voleti", "Любить", "ja volim | on voli | oni vole (группа И)"],
  ["Sedeti", "Сидеть", "ja sedim | on sedi | oni sede (группа И)"],
  ["Živeti", "Жить", "ja živim | on živi | oni žive (группа И)"],
  ["Videti", "Видеть", "ja видим | on vidi | oni vide (группа И)"],
  ["Mrzeti", "Ненавидеть", "ja mrzim | on mrzi | oni mrze (группа И)"],
  ["Štedeti", "Экономить, сберегать", "ja štedim | on štedi | oni štede (группа И)"],
  ["Želeti", "Хотеть; желать", "ja želim | on želi | oni žele (группа И)"],
  ["Lepiti", "Лепить, клеить", "ja lepim | on lepi | oni lepe (группа И)"],
  ["Pržiti", "Жарить, поджаривать", "ja pržim | on prži | oni prže (группа И)"],
  ["Praviti", "Делать, создавать", "ja pravim | on pravi | oni praве (группа И)"],
  ["Cediti", "Выжимать; отцеживать", "ja cedim | on cedi | oni cede (группа И)"],
  ["Tražiti", "Искать; требовать; просить", "ja tražim | on traži | oni traže (группа И)"],
  ["Voziti", "Водить; везти", "ja vozim | on vozi | oni voze (группа И)"],
  ["Paziti", "Внимательно смотреть", "ja pazim | on pazi | oni paze (группа И)"],
  ["Maziti", "Угождать; баловать", "ja mazim | on mazi | oni maze (группа И)"],
  ["Vaditi", "Вынимать", "ja vadim | on vadi | oni vade (группа И)"],
  ["Dolaziti", "Приходить; приезжать", "ja dolazim | on dolazi | oni dolaze (группа И)"],
  ["Puniti", "Заряжать", "ja punim | on puni | oni pune (группа И)"],
  ["Misliti", "Думать", "ja mislim | on misli | oni misle (группа И)"],
  ["Čistiti", "Чистить; очищать", "ja čistim | on čisti | oni čiste (группа И)"],
  ["Raditi", "Работать; делать", "ja radim | on radi | oni rade (группа И)"],
  ["Koristiti", "Использовать", "ja koristim | on koristi | oni koriste (группа И)"],
  ["Donositi", "Приносить; доставлять", "ja donosim | on donosi | oni donose (группа И)"],
  ["Pratiti", "Следовать (за кем-либо)", "ja pratim | on prati | oni prate (группа И)"],
  ["Ulaziti", "Входить", "ja ulazim | on ulazi | oni ulaze (группа И)"],
  ["Izlaziti", "Выходить", "ja izlazim | on izlazi | oni izlaze (группа И)"],
  ["Nuditi", "Предлагать; угощать", "ja nudim | on nudi | oni nude (группа И)"],
  ["Ljubiti", "Целовать", "ja ljubim | on ljubi | oni ljube (группа И)"],
  ["Braniti", "Защищать", "ja branim | on brani | oni brane (группа И)"],
  ["Pušiti", "Курить", "ja pušim | on puši | oni puše (группа И)"],
  ["Baviti se", "Заниматься", "ja bavim se | on bavi se | oni bave se (группа И)"],
  ["Družiti se", "Общаться", "ja družim se | on druži se | oni drže se (группа И)"],
  ["Šaliti se", "Шутить", "ja šalim se | on šali se | oni šale se (группа И)"],
  ["Seliti se", "Выселяться; переезжать", "ja selim se | on seli se | oni sele se (группа И)"],
  ["Truditi se", "Стараться", "ja trudim se | on trudi se | oni trude se (группа И)"],
  ["Snalaziti se", "Ориентироваться; приспосабливаться", "ja snalazim se | on snalazi se | oni snalaze se (группа И)"],

  // Группа «Е»
  ["Zvati", "Звать; звонить; приглашать", "ja zovem | on zove | oni zovu (группа Е)"],
  ["Prati", "Мыть", "ja perem | on pere | oni peru (группа Е)"],
  ["Slati", "Посылать; отправлять", "ja šaljem | on šalje | oni šalju (группа Е)"],
  ["Piti", "Пить", "ja pijem | on pije | oni piju (группа Е)"],
  ["Kriti", "Скрывать; прятать", "ja krijem | on krije | oni kriju (группа Е)"],
  ["Ostajati", "Оставаться", "ja ostajem | on ostaje | oni ostaju (группа Е)"],
  ["Počinjati", "Начинать; начинаться", "ja počinjem | on počinje | oni počinju (группа Е)"],
  ["Kašljati", "Кашлять", "ja kašljем | on kašlje | oni kašlju (группа Е)"],
  ["Lagati", "Врать; обманывать", "ja lažem | on laže | oni lažu (группа Е)"],
  ["Polagati", "Сдавать (экзамен)", "ja polažem | on polaže | oni polažu (группа Е)"],
  ["Predlagati", "Предлагать", "ja predlažem | on predlaže | oni predlažu (группа Е)"],
  ["Pomagati", "Помогать", "ja pomažem | on pomaže | oni pomažu (группа Е)"],
  ["Stizati", "Догонять; прибывать", "ja stižem | on stiže | oni stižu (группа Е)"],
  ["Dizati", "Поднимать", "ja dižem | on diže | oni dižu (группа Е)"],
  ["Mazati", "Мазать", "ja mažem | on maže | oni mažu (группа Е)"],
  ["Naručivati", "Заказывать", "ja naručujem | on naručuje | oni naručuju (группа Е)"],
  ["Sređivati", "Приводить в порядок", "ja sređujem | on sređuje | oni sređuju (группа Е)"],
  ["Istraživati", "Исследовать", "ja istražujem | on istražuje | oni istražuju (группа Е)"],
  ["Davati", "Давать", "ja dajem | on daje | oni daju (группа Е)"],
  ["Dodavati", "Прибавлять; подавать", "ja dodajem | on dodaje | oni dodaju (группа Е)"],
  ["Prodavati", "Продавать", "ja prodajem | on prodaje | oni prodaju (группа Е)"],
  ["Pakovati", "Упаковывать", "ja pakujem | on pakuje | oni pakuju (группа Е)"],
  ["Verovati", "Верить", "ja verujem | on veruje | oni veruju (группа Е)"],
  ["Letovati", "Проводить лето", "ja letujem | on letuje | oni letuju (группа Е)"],
  ["Kupovati", "Покупать", "ja kupujem | on kupuje | oni kupuju (группа Е)"],
  ["Putovati", "Путешествовать; ездить", "ja putujem | on putuje | oni putuju (группа Е)"],
  ["Napredovati", "Прогрессировать", "ja napredujem | on napreduje | oni napreduju (группа Е)"],
  ["Doručkovati", "Завтракать", "ja doručkujem | on doručkuje | oni doručkuju (группа Е)"],
  ["Iznajmljivati", "Сдавать в аренду; Брать в аренду", "ja iznajmljujem | on iznajmljuje | oni iznajmljuju (группа Е)"],
  ["Prijavljivati se", "Подавать заявление", "ja prijavljujem se | on prijavljuje se | oni prijavljuju se (группа Е)"],
  ["Jesti", "Есть", "ja jedem | on jede | oni jedu (группа Е)"],
  ["Ići", "Идти", "ja idem | on ide | oni idu (группа Е)"],
  ["Seći", "Резать", "ja sečem | on seče | oni seku (группа Е)"],
  ["Peći", "Печь", "ja pečem | on peče | oni peku (группа Е)"],
  ["Vući", "Тянуть", "ja vučem | on vuče | oni vuku (группа Е)"],
  ["Tući", "Бить", "ja tučem | on tuče | oni tuku (группа Е)"],
  ["Vikati", "Кричать", "ja vičem | on viče | oni viču (группа Е)"],
  ["Rezervisati", "Бронировать", "ja rezervišem | on rezerviše | oni rezervišu (группа Е)"],
  ["Brisati", "Вытирать; стирать", "ja brišem | on briše | oni brišu (группа Е)"],
  ["Pisati", "Писать", "ja pišem | on piše | oni pišu (группа Е)"],
  ["Skretati", "Сворачивать", "ja skrećem | on skreće | oni skreću (группа Е)"],
  ["Okretati se", "Разворачиваться", "ja okrećem se | on okreće se | oni okreću se (группа Е)"],
  ["Brijati", "Брить", "ja brijem | on brije | oni briju (группа Е)"],
  ["Dobiti", "Получать", "ja dobijem | on dobije | oni dobiju (группа Е)"],
  ["Brinuti", "Беспокоиться", "ja brinem | on brine | oni brinu (группа Е)"],

  // Исключения
  ["Hteti", "Хотеть", "ja hoću | on hoће | oni hoće (исключение)"],
  ["Ne hteti", "Не хотеть", "ja neću | on neće | oni neće (исключение)"],
  ["Moći", "Мочь", "ja mogu | on može | oni mogu (исключение)"],
  ["Razumeti", "Понять", "ja razumem | on razume | oni razumeju (исключение)"]
];
