const words_anatomical_dirs = [
    ["superior", "gornji"],
    ["inferior", "donji"],
    ["anterior", "prednji"],
    ["posterior", "zadnji"],
    ["dexter", "desni"],
    ["sinister", "levi"],
    ["internus", "unutrašnji"],
    ["externus", "spoljašnji"],
    ["medialis", "bliže sredini"],
    ["lateralis", "bočni / sa strane"],
    ["ventralis", "sa strane stomaka"],
    ["dorsalis", "sa strane leđa"],
    ["cranialis", "ka glavi"],
    ["caudalis", "ka repu / nadole"],
    ["rostralis", "ka njušci / napred"],
    ["proximalis", "bliže trupu"],
    ["distalis", "dalje od trupu"],
    ["superficialis", "površinski / na površini"],
    ["profundus", "duboki / unutra"],
    ["centralis", "u centru"],
    ["periphericus", "na periferiji / na ivici"],
    ["palmaris", "na dlanu"],
    ["plantaris", "na tabanu"]
];