let words_anatomija_1 = [
	["Aditus", "ulaz"],
	["ala", "krilo"],
	["alveolus", "jama, alveola"],
	["angulus", "ugao"],
	["antrum", "ulaz"],
	["anulus", "prsten"],
	["apertura", "otvor"],
	["apex", "vrh"],
	["appendix", "dodatak"],
	["arcus", "luk"],
	["area", "polje"],
	["articulatio", "zglob"],
	["axis", "osovina"],
	["Basis", "osnova"],
	["brevis", "kratak"],
	["Canalicus", "kanalić"],
	["canalis", "žleb, kanal"],
	["capitulum", "glavica"],
	["caput", "glava"],
	["cauda", "rep"],
	["cavum", "šupljina"],
	["cellula", "ćelija"],
	["columna", "stub"],
	["collum", "vrat"],
	["cornu", "rog"],
	["corpus", "telo"],
	["crista", "greben"],
	["Eminentia", "uzvišenje"],
	["excavitio", "udubljenje"],
	["extremitas", "okrajak"],
	["Facies", "lice, strana"],
	["fascia", "omotač"],
	["foramen", "otvor"],
	["formatio", "tvorevina"],
	["fossa", "jama"],
	["fossula", "jamica"],
	["fovea", "otvor"],
	["foveola", "mali otvor"],
	["fundus", "dno"],
	["Impressio", "otisak"],
	["incisura", "usek"],
	["Lamina", "list"],
	["longus", "dugačak"],
	["limbus", "ivica"],
	["linea", "linija"],
	["Macula", "mrlja"],
	["Os (ossis)", "kost"],
	["Pars", "deo"],
	["planus", "ravan, širok"],
	["pelvis", "karlica"],
	["processus", "nastavak"],
	["prominentia", "uzvišenje"],
	["punctum", "tačka"],
	["Regio", "predeo"],
	["rudimentum", "zaostatak"],
	["Spatium", "prostor"],
	["spina", "bodlja"],
	["sulcus", "žleb"],
	["Tendo", "tetiva"],
	["torus", "greben"],
	["trigonum", "trougao"],
	["trochlea", "valjak"],
	["tuber", "kvrga"],
	["tuberculum", "kvržica"],
	["Vagina", "omotač"],
	["Verticalis", "uspravni"],
	["horizontalis", "vodoravni"],
	["medianus", "srednji"],
	["coronalis", "venčani"],
	["sagittalis", "uzdužni"],
	["frontalis", "čeoni"],
	["transversalis", "poprečni"],
	["medialis", "unutrašnji"],
	["intermedius", "središnji"],
	["lateralis", "spoljašnji"],
	["anterior", "prednji"],
	["medius", "srednji"],
	["posterior", "zadnji"],
	["ventralis", "prednji"],
	["dorsalis", "zadnji"],
	["internus", "unutrašnji"],
	["externus", "spoljašnji"],
	["dexter", "desni"],
	["sinister", "levi"],
	["longitudinalis", "uzdužni"],
	["transversus", "poprečni"],
	["cranialis", "gornji prema glavi"],
	["caudalis", "donji prema repu"],
	["superior", "gornji"],
	["inferior", "donji"],
	["superfacialis", "površni"],
	["profundus", "dubok"],
	["proximalis", "gornji"],
	["distalis", "donji"],
	["radialis", "spoljašnji, prema žbici"],
	["ulnaris", "unutrašnji, prema lakatnoj kosti"],
	["tibialis", "unutrašnji, prema golenjači"],
	["fibularis", "spoljašnji, prema lišnjači"],
	["palmaris", "dlanski"],
	["plantaris", "tabanski"]
];