const words_serbian_phrases = [
  ["Ako budeš most, svako će da te gazi", "Если ты мост, все на тебя наступят"],
  ["Ako drugog poštuješ za sebe ne brini", "Если вы уважаете других за себя, не волнуйтесь"],
  ["Ako dugo žive skupa, životinje se zavole, a ljudi se zamrze", "Если они долго живут вместе, животные любят друг друга, а люди ненавидят друг друга"],
  ["Ako želiš izgubiti prijatelja, posudi mu novac ", "Если хочешь потерять друга, одолжи ему денег"],
  ["Ako želiš izgubiti prijatelja, pričaj s njim o politici", "Если хочешь потерять друга, поговори с ним о политике"],
  ["Ako želiš jezgro, slomi ljusku", "Если тебе нужно ядро, сломай оболочку"],
  ["Ako ženu tučeš, svoju sreću tučeš", "Если вы бьете свою жену, вы бьете свое счастье"],
  ["Ako zagrmi na Svetog Iliju, neće biti lešnika", "Если на святого Илию прогремит, не будет фундука"],
  ["Ako zahteva napor, nije ga vredno raditi", "Если это требует усилий, то делать этого не стоит"],
  ["Ako znaš šta ti je bilo, ne znaš šta će ti biti", "Если вы знаете, что с вами произошло, вы не знаете, что с вами произойдет"],
  ["Ako imaš mašice, ne hvataj vatru rukama", "Если у вас есть перчатки, не прикасайтесь к огню руками"],
  ["Ako ih ne možeš pobediti pridruži im se", "Если ты не можешь победить их, присоединяйся к ним"],
  ["Ako je go, ali je soko", "Если он голый, то это сокол"],
  ["Ako je i koliba, naša je", "Если это хижина, то она наша"],
  ["Ako je i teško živeti, opet je život sladak", "Даже если жизнь трудна, жизнь все равно сладка"],
  ["Ako je na guvnu, nije u ambaru", "Если это в сарае, то не в сарае"],
  ["Ako je neko lud, ne budi mu drug", "Если кто-то сумасшедший, не будь ему другом"],
  ["Ako jedna želja nije zadovoljena to je dovoljan razlog", "Если одно желание не удовлетворено, этого достаточно"],
  ["Ako kupuješ često ono što ti ne treba, skoro ćeš prodavati ono što ti treba", "Если вы часто покупаете то, что вам не нужно, вы почти наверняка продадите то, что вам нужно"],
  ["Ako mi ne možeš pomoći, nemoj mi odmagati", "Если ты не можешь мне помочь, не отговаривай меня"],
  ["Ako ne može po konju,", "Если он не умеет ездить на лошади,"],
  ["Ako ne možemo kako hoćemo, a mi kako možemo", "Если мы не можем делать то, что хотим, и делаем то, что можем"],
  ["Ako ne počneš, nećeš ni završiti", "Если ты не начнешь, ты не закончишь"],
  ["Ako ne umije reći, umije leći", "Если он не может говорить, он может лечь"],
  ["Ako neće zlo od tebe, beži ti od zla", "Если не хочешь от себя зла, беги от зла"],
  ["Ako odgovaraš na poruku bit ćeš još više naoružan", "Если вы ответите на сообщение, вы будете еще более вооружены"],
  ["Ako si ti vuk, nijesam ni ja ćuk", "Если ты волк, то и я не волк"],
  ["Ako ti mogu kupiti kapu, pamet ne mogu", "Если я могу купить тебе шляпу, я не смогу купить тебе мозг"],
  ["Ako u starosti želiš odmor, moraš u mladosti uneti napor", "Если хочешь отдохнуть в старости, придется приложить усилия в молодости"],
  ["Ako hoćeš da pljuneš, pljuni u šaku", "Если хочешь плюнуть, плюй в кулак"],
  ["Ako hoćeš koga da poznaš, podaj mu vlast", "Если вы хотите узнать кого-то, дайте ему власть"],
  ["Ako činiš dobro, ne udaraj u veliko zvono", "Если делаешь добро, не звони в большой колокол"],
  ["Ako si lud,ostani lud", "Если ты сумасшедший, оставайся сумасшедшим"],
  ["Ako slepac slepca vodi, obojica će u jamu upasti", "Если слепой поведет слепого, оба упадут в яму"],
  ["Badava je dobro seme kad je rđavo oranje", "Бадава – хорошее семя, когда пахота плохая"],
  ["Batina ima dva kraja", "У клуба есть два конца"],
  ["Bez alata nema ni zanata", "Без инструментов нет ремесла"],
  ["Bez društva nema junaštva", "Без общества нет героизма"],
  ["Bez jednoga čoveka može vašar biti", "Ярмарка может проходить без одного человека"],
  ["Bez muke nema nauke", "Без боли нет науки"],
  ["Beri želje pokraj sebe!", "Забирайте желания рядом с собой!"],
  ["Bi se na srebrnoj pari obrnuo", "Он развернулся бы в мгновение ока"],
  ["Bivši prijatelj je gori nego neprijatelj", "Бывший друг хуже врага"],
  ["Bijele ruke tuđ posao miluju", "Белые руки ласкают чужой труд"],
  ["Biser ne valja pred svinje prosipati", "Не следует метать жемчуг перед свиньями"],
  ["Bježi kud ti je volja, od sebe ne utječe", "Беги куда хочешь, само на себя не действует"],
  ["Blago nestade, vrag ostade", "Сокровище исчезает, дьявол остается"],
  ["Blago onom ko se tuđom štetom opameti, a teško onom koji svojom mora", "Блажен, кто мудреет за счет других, и горе тому, кто должен заниматься своим делом"],
  ["Blago onome ko zna da ne zna, a hoće da zna", "Блажен, кто знает, что не знает, но хочет знать"],
  ["Bog je spor, ali dostižan", "Бог медленный, но достижимый"],
  ["Bog ne plaća svake subote", "Бог не платит каждую субботу"],
  ["Bez Boga ni preko praga", "Без Бога даже за порогом"],
  ["Bog onda pomaže kad niko ne može", "Бог помогает тогда, когда никто другой не может"],
  ["Bogat je ko nije dužan, a mlad ko je zdrav", "Кто не в долгах, тот богат, а кто здоров, тот молод"],
  ["Bogat je onaj koji više proizvede, nego što pojede", "Богат тот, кто производит больше, чем ест"],
  ["Bogata je teško darovati, sita gosta još teže častiti", "Трудно подарить богатый подарок, еще труднее почтить полного гостя"],
  ["Bogatstvo menja čud, retko nabolje", "Богатство меняется чудесно, редко к лучшему"],
  ["Bogatstvo nikad nije sito", "Богатство никогда не бывает полным"],
  ["Boj ne bije svijetlo oružje, već boj bije srce u junaka", "Не битва бьет яркое оружие, но битва бьет сердце героя"],
  ["Bol se savlada strpljivošću", "Боль преодолевается терпением"],
  ["Bolan se pita, a zdravom se daje", "У больных спрашивают, а у здоровых дают"],
  ["Bolest na kolima dolazi, a na dlaku izlazi", "Болезнь приходит в машине и выходит в мгновение ока"],
  ["Bolja je poštena smrt nego sramotan život", "Честная смерть лучше позорной жизни"],
  ["Bolja je svoja proja nego tuđa pogača", "Свой хлеб лучше чужого торта"],
  ["Bolje da te smrt prijeka digne, nego suza siromaška stigne", "Лучше смерть поднимет тебя, чем слезы бедной женщины"],
  ["Bolje i dvared pitati nego jedared zaići", "Лучше спросить дважды, чем пойти прямо"],
  ["Bolje saviti nego slomiti", "Лучше согнуть, чем сломать"],
  ["Bolje nepravdu trpiti, nego činiti", "Лучше терпеть несправедливость, чем совершать ее"],
  ["Bolje obići šumu, nego na prečcu sresti vuka", "Лучше пойти по лесу, чем встретить волка на переходе"],
  ["Bolje iz daleka se voleti, nego izbliza mrzeti", "Лучше любить издалека, чем ненавидеть вблизи"],
  ["Bolje poslednji među dobrim, no prvi među zlim", "Лучше быть последним среди добрых, чем первым среди злых"],
  ["Bolje ikad nego nikad", "Лучше поздно, чем никогда"],
  ["Bolje je dobro slušati, nego loše zapovedati", "Лучше хорошо слушать, чем плохо командовать"],
  ["Bolje je dobroga služiti, nego rđavu zapovijedati", "Лучше служить добру, чем повелевать злу"],
  ["Bolje je i malo s blagoslovom, negoli i dosta s prokletstvom", "Лучше немного с благословением, чем много с проклятием"],
  ["Bolje je imati rđavu godinu, nego rđava susjeda", "Лучше иметь плохой год, чем плохой сосед"],
  ["Bolje je ne početi, nego ne dočeti", "Лучше не начать, чем не закончить"],
  ["Bolje je neznalica no tvrdoglavica", "Лучше быть невежественным, чем упрямым"],
  ["Bolje je nemati, nego otimati", "Лучше не иметь, чем воровать"],
  ["Bolje je nešto ne znati nego naopako i zlo znati", "Лучше чего-то не знать, чем знать неправильно и плохо"],
  ["Bolje je pokliznuti nogom nego jezikom", "Лучше поскользнуться ногой, чем языком"],
  ["Bolje je s mudrim plakati nego s ludim pevati", "Лучше плакать с мудрыми, чем петь с глупыми"],
  ["Bolje je svašta jesti, nego svašta govoriti", "Лучше что-нибудь съесть, чем что-то сказать"],
  ["Bolje je svoje jaje nego tuđa kokoš", "Своё яйцо лучше чужой курицы"],
  ["Bolje je u kolibi pjevati nego u dvoru plakati", "Лучше петь в избе, чем плакать во дворе"],
  ["Bolje je umeti nego imati", "Лучше знать, чем иметь"],
  ["Bolje mršav mir nego debela parnica", "Лучше худой мир, чем толстый иск"],
  ["Bolje prazna kesa nego prazna glava", "Лучше пустая сумка, чем пустая голова"],
  ["Bolje s mudrim orati nego s ludim vino piti", "Лучше пахать с мудрыми, чем пить вино с глупыми"],
  ["Bolje se zamjeriti Bogu, no narodu", "Лучше возмущаться на Бога, чем на людей"],
  ["Bolje se ograditi dobrim komšijom nego dobrom ogradom", "Лучше окружить себя хорошим соседом, чем хорошим забором"],
  ["Bolje se od po puta vratiti nego rđavim do kraja ići", "Лучше вернуться на полпути, чем пройти весь путь грязным"],
  ["Bolje se s junakom biti, nego s rđom ljubiti", "Лучше быть с героем, чем целовать ржавчину"],
  ["Bolje slep očima, nego slep pameću", "Лучше быть слепым глазами, чем слепым разумом"],
  ["Bolje suv hleb s poštenjem nego kolač s nepoštenjem", "Лучше сухой хлеб с честностью, чем торт с нечестностью"],
  ["Bolje ukor mudroga,nego hvala ludoga", "Лучше упрекнуть мудрого, чем похвалить дурака"],
  ["Bolje džabe sedeti, nego džabe raditi", "Лучше сидеть зря, чем зря работать"],
  ["Bolji je dobar glas nego zlatan pas", "Хороший голос лучше золотой собаки"],
  ["Bolji je i crn kolač nego prazna torba", "Черный торт лучше, чем пустой мешок"],
  ["Bolje vrabac u ruci, nego golub na grani", "Лучше воробей в руке, чем голубь на ветке"],
  ["Brat brata nad jamu vodi, ali u jamu ne meće", "Брат ведет брата через яму, но не входит в яму"],
  ["Brat je mio ma koje vere bio (kad bratski čini i postupa)", "Брат добр, независимо от того, какого он вероисповедания (когда он поступает и поступает как брат)"],
  ["Brdo se s brdom ne može sastati, a živi se ljudi sastanu", "Холм не может встретиться с холмом, а встречаются живые люди"],
  ["Budalu ne treba tražiti, sama se javi", "Не надо искать дурака, называет он себя"],
  ["Budi dobar, ne budi grobar", "Будь хорошим, не будь могильщиком"],
  ["Vatra i voda su dobre sluge, ali zli gospodari", "Огонь и вода — добрые слуги, но злые хозяева"],
  ["Velike ribe veliku vodu traže", "Большая рыба ищет большую воду"],
  ["Veselo srce pola zdravlja", "Веселое сердце – половина здоровья"],
  ["Veća glava više glavobolje", "Чем больше голова, тем больше головная боль"],
  ["Vinograd ne ište molitve, nego motike", "Виноградник не молитв просит, а мотыг"],
  ["Više valja gram pameti nego oka snage", "Грамм ума стоит больше, чем глаз силы"],
  ["Više je ljudi pomrlo od jela i pića nego od gladi i žeđi", "От еды и питья умерло больше людей, чем от голода и жажды"],
  ["Više um zamisli nego more ponese", "Разум воображает больше, чем может унести море"],
  ["Vješt goru lomi, a nevješta gora", "Умелый ломает гору, а неумелый ломает гору"],
  ["Vo se veže za rogove, a čovjek za jezik", "Волка привязывают к рогам, а человека к языку"],
  ["Voda svašto opere, do crna obraza", "Вода смывает все, вплоть до черных щек"],
  ["Vodu koju ćeš pit nemoj mutit", "Не перемешивайте воду, которую собираетесь пить"],
  ["Vreme gradi niz Kotare kule, vreme gradi vreme razgrađuje", "Время строит серию башен Котаре, время строит, время разрушает"],
  ["Vreme donese sve ko ga dočekati ume", "Время приводит всех, кто умеет его ждать"],
  ["Vreme je najveći gospodar", "Время – величайший хозяин"],
  ["Vuk dlaku mijenja, ali ćudi nikada", "Волк меняет шерсть, но никогда — характер"],
  ["Vuk ne vije što je mesa gladan, nego vije da družinu svije", "Волк воет не потому, что жаждет мяса, а для того, чтобы разбудить группу"],
  ["Tršić, Vukov spome park", "Тршич, Вуковский парк растений"],
  ["Gvožđe reže i drvo i kamen, ali i njega rđa jede", "Железо режет дерево и камень, но и ржавчина его съедает"],
  ["Gvožđe se kuje dok je vruće", "Железо куется пока оно горячее"],
  ["Gde žena buči tu muž muči", "Где жена шумит, муж мучается"],
  ["Gde zlato govori, usta ćute", "Там, где говорит золото, уста молчат"],
  ["Gde zlato gospoduje, razlog se ne čuje", "Там, где правит золото, разум не слышен"],
  ["Gde je mnogo priče malo je rada", "Где много разговоров, там мало работы"],
  ["Gde je sila gospodar, pravda je sluga", "Там, где сила — хозяин, справедливость — слуга"],
  ["Gde je sloga tu je i pobeda", "Где гармония, там и победа"],
  ["Gde je sova izlegla sokola?", "Где сова высидела сокола?"],
  ["Gde je stida, tu je i poštenja", "Где стыд, там честность"],
  ["Gde je cvet, tu je i med", "Где цветок, там и мед"],
  ["Gde je čija kuća tu je i sredina sveta", "Где чей-то дом, там и середина мира"],
  ["Gde miš ne cijuče, tu ni pile ne pijuče", "Где мышка не чирикает, там курочка не пьет"],
  ["Gde nije mira, nema ni sreće", "Где нет покоя, нет счастья"],
  ["Gde se ništa ne može pomoći lepo je osmehnuti se", "Там, где ничем нельзя помочь, приятно улыбаться"],
  ["Gde se pije primakni se, gde se bije odmakni se", "Там, где пьют, подойдите ближе, где ругаются, отойдите"],
  ["Gdje nema vola orača, tu nema ni kolača", "Где нет пахотного вола, там нет и лепешек"],
  ["Ginu ti što se smeju uoči bitke", "Они умирают от смеха перед битвой"],
  ["Glava je starija od knjige", "Глава старше книги"],
  ["Glad je najbolji kuvar", "Голод – лучший повар"],
  ["Glad očiju nema", "Нет голода для глаз"],
  ["Gladan pas i na gazdu laje", "Голодная собака лает на своего хозяина"],
  ["Gladnog ne teši, već nahrani", "Не утешайте голодного, а накормите"],
  ["Gle Miloša, pope se na plot!", "Посмотри на Милоша, перелезь через забор!"],
  ["Govori kao bez vilica", "Он говорит так, будто у него нет челюсти"],
  ["Govori u bespuće", "Он говорит напрасно"],
  ["Gospodskom smijehu i vedru nebu ne valja vjerovati, jer se začas promijeni", "Смеху Господа и ясному небу не следует доверять, потому что оно меняется в одно мгновение"],
  ["Gradi ražanj, a zec u šumi", "Он строит косу, а кролик в лесу"],
  ["Gde će kruška nego pod kruškom", "Где будет груша, как не под грушей"],
  ["Dobro čini ne boj se,zlo čini na daj se", "Делай добро, не бойся, делай зло бойся"],
  ["Tršić, Vukov spomen park", "Тршич, мемориальный парк Вука"],
  ["Da ga zemlja ne vuče sebi, poleteo bi", "Если бы земля не притянула его к себе, он бы улетел"],
  ["Da ga čoek pošalje po smrt, mogao bi se naživljeti", "Если парень отправил его умирать, его можно было воскресить"],
  ["Da je srce tvrđe od kamena opet bi ga rastopilo zlato", "Если бы сердце было тверже камня, золото снова расплавило бы его"],
  ["Da je steći ko što reći, svi bi bogati bili", "Если бы приобретение было чем-то, что могло бы сказать, все были бы богатыми"],
  ["Da je švati ko zjati, i vrana bi košulju nosila", "Если бы она знала своего зятя, даже ворона носила бы рубашку"],
  ["Da ne bole, ne b' se rane zvale", "Если бы они не причиняли боли, их бы не называли ранами"],
  ["Da nije vetrova, pauci bi nebo premrežili", "Если бы не ветер, пауки оплетали бы небо"],
  ["Da padne na leđa, razbio bi nos", "Если бы он упал на спину, то сломал бы себе нос"],
  ["Da se prava istina pozna, treba čuti dva zvona", "Чтобы узнать настоящую правду, нужно услышать два звонка"],
  ["Dan se hvali kad veče, a život kad smrt dođe", "Прославляется день, когда наступает вечер, и жизнь, когда приходит смерть"],
  ["Danas vezir, sjutra rezil", "Сегодня визирь, завтра клинок"],
  ["Danas u zlatu, sutra u blatu", "Сегодня в золоте, завтра в грязи"],
  ["Darovni kolač često u grlu zapne", "Подарочный торт часто застревает в горле"],
  ["Dva loša ubiše Miloša", "Два плохих парня убили Милоша"],
  ["Dva lješnika, orahu su vojska", "Два фундука, грецкий орех – армия"],
  ["Dva puta mjeri, a treći kroj", "Дважды отмерь, а в третий раз отрежь"],
  ["Dvaput zine – triput slaže", "Зин дважды – совпадение три раза"],
  ["Devojka koja žuri na sastanak već je zakasnila", "Девушка, спешащая на встречу, уже опаздывает"],
  ["Dobavio se ki ćelav kape", "Добавлена ​​ки лысина"],
  ["Dobar glas daleko ide, a zao još dalje", "Хорошее слово идет далеко, а плохое еще дальше"],
  ["Dobar espap lasno kupca nađe", "Хороший espap легко найдет покупателя"],
  ["Dobar posao se sam hvali", "Хорошая работа говорит сама за себя"],
  ["Dobar čovek uvek ostaje početnik", "Хороший человек всегда остается новичком"],
  ["Dobra žena poštuje muža, pa da je kao pevac", "Хорошая жена уважает своего мужа, поэтому она как певица"],
  ["Dobra žena praznu kuću čini da je puna", "Хорошая женщина наполняет пустой дом"],
  ["Dobra krava se i u štali proda!", "Хорошую корову можно продать в коровнике!"],
  ["Dobra nije gde se pametni ne slušaju", "Нехорошо там, где умных не слушают"],
  ["Dobra ovca mnogo ne bleji, ali mnogo vune daje", "Хорошая овца мало блеет, но шерсти дает много"],
  ["Dobra čeljad uvek posla nađu", "Хорошие люди всегда находят работу"],
  ["Dobre komšije podižu cenu kući i dobrom imanju", "Хорошие соседи повышают цену на дом и хорошую недвижимость"],
  ["Dobro je kašto i pametnu ženu poslušati", "Приятно слушать умную женщину"],
  ["Dobro je lasno zaboraviti, a zlo nikada", "Хорошее легко забыть, а плохое – никогда"],
  ["Dobro je teško videti, a lako se pozna", "Добро трудно увидеть, но легко познать"],
  ["Dobro jelo samo se nudi", "Хорошая еда просто предлагает себя"],
  ["Dobro mi je i boljem se nadam", "Я в порядке и надеюсь на лучшее"],
  ["Dobro obrađena zemlja nikad nije jalova", "Хорошо обрабатываемая земля никогда не бывает бесплодной"],
  ["Dobro se ne pozna dok se ne izgubi", "Вы не узнаете себя хорошо, пока не потеряетесь"],
  ["Dobrom konju ne treba mamuza", "Хорошей лошади шпора не нужна"],
  ["Dobru čoveku sve dobro stoji", "Все устраивает хорошего человека"],
  ["Dogovorna je najbolja", "Договорная-лучше всего"],
  ["Dok dete ne padne, ne može naučiti da hoda", "Пока ребенок не упадет, он не сможет научиться ходить"],
  ["Dok živiš, dolikuje ti da se nadaš", "Пока вы живы, вам надлежит надеяться"],
  ["Dok je leđa, biće samara", "Пока есть спина, будет Самара"],
  ["Dok je raje i muka, biće i hajduka", "Пока есть рай и боль, будет и хаджа"],
  ["Dok je šiba tanka, treba je ispravljati", "Пока хлыст тонкий, его следует выпрямить"],
  ["Dok lipa cveta, prepuna je pčela", "Пока липа цветет, на ней полно пчел"],
  ["Dok svi kažu 'E vala!' - osta glava ćelava", "Пока все говорят: «Ух ты!» - голова остается лысой"],
  ["Dok se mudri namudrovaše, ludi se naživovaše", "Пока мудрые дурачились, дураки развлекались"],
  ["Dok se muke ne namuči, pameti se ne nauči", "Пока ты не работаешь усердно, ты не научишься мудрости"],
  ["Dokle prosi, zlatna usta nosi, a kad vraća, pleća obraća", "Пока он просит, он носит золотые уста, а когда отдает, то поворачивает плечо"],
  ["Dragom često opraštaj, sebi nikad", "Чаще прощайте любимого человека, а не себя"],
  ["Drvo bez grane i čovek bez mane - ne mogu biti", "Дерево без ветки и человек без изъяна – их не может быть"],
  ["Drvo se na drvo oslanja, a čovek na čoveka", "Дерево опирается на дерево, а человек опирается на человека"],
  ["Drž’ se nova puta i stara prijatelja", "Держись новых путей и старых друзей"],
  ["Drži se novog puta i starog prijatelja", "Держись нового пути и старого друга"],
  ["Drugo doba, druge ćudi", "Другой возраст, другие темпераменты"],
  ["Duboka voda je bistra, a plitka mutna", "Глубокая вода прозрачна, а на мелководье мутная"],
  ["Dug je zao drug", "Долг – злой друг"],
  ["Đe brat brata ne voli, tu nema sreće", "Если брат не любит брата, не будет удачи"],
  ["Đe velika zvona zvone, tu se mala ne čuju", "Там, где звонят большие колокола, не слышно маленьких"],
  ["Đe dosta ruka pregne, radnja je brzo završena", "После долгих хлопот действие было быстро завершено"],
  ["Đe je sreća, tu je i nesreća", "Где есть счастье, там есть и несчастье"],
  ["Đe je tor tu je i mor", "Где тор, там и море"],
  ["Đe ko nikne, tu i obikne", "Где бы оно ни проросло, там оно и растет"],
  ["Đe nema malenog nema ni golemog", "Нет ни маленького, ни огромного"],
  ["Đe nije žene, tu nije ni kuće", "Нет женщины, нет дома"],
  ["Đe nije mačke, tu miši kolo vode", "Там, где нет кошек, вокруг воды водятся мыши"],
  ["Đe se god sastanu ljudi, ocjenjuju druge, a sebe ne", "Всякий раз, когда люди встречаются, они судят других, а не себя"],
  ["Đe će kruška no pod krušku", "Это будет груша, но под грушей"],
  ["Đeca su kao rosa", "Дети как роса"],
  ["Ekser drži potkov, potkov konja, konj junaka, junak grad, a grad zemlju", "Гвоздь держит подкову, подкову коня, коня героя, город героя, город страну"],
  ["Eto mene, eto vas, eto vama rat sa Turcima. Miloš Obrenović", "Вот я, вот ты, вот война с турками. Милош Обренович"],
  ["Eto ti ga,đavole!", "Вот так, дьявол!"],
  ["E,džaba ga,vala,bilo!", "Ну, это зря!"],
  ["E, ta ti valja!", "Ну, это хорошо для тебя!"],
  ["E,da je baba deda", "Да, бабушка есть дедушка"],
  ["Žalost i radost se poznaju čoveku po licu", "Грусть и радость узнают по лицу человека"],
  ["Žežen kašu hladi", "Ежен охлаждает кашу"],
  ["Žena muža nosi na licu, a muž ženu na košulji", "Жена носит мужа на своем лице, а муж носит жену на своей рубашке"],
  ["Ženi je najslađi zalogaj - muško srce", "Самый сладкий кусочек женщины – сердце мужчины"],
  ["Ženi sina kad 'oćeš a udaj 'ćer kad možeš!", "Женитесь на своем сыне, когда захотите, и женитесь на дочери, когда сможете!"],
  ["Ženi sina pa šalji u vojsku", "Женитесь на своем сыне и отправьте его в армию"],
  ["Ženiti se mlad - prerano je, a star - prekasno je", "Жениться молодым – рано, а старым – поздно"],
  ["Ženska lepota je njeno oružje", "Красота женщины – ее оружие"],
  ["Žensko je oružje jezik", "Оружие женщины – язык"],
  ["Žensko je tuđa sreća", "Женское счастье – чужое"],
  ["Ženu i kosu nikome ne daj", "Не отдавай свою жену и волосы никому"],
  ["Živ mi Todor da se čini govor", "Да здравствует Тодор, выступающий с речью"],
  ["Živa glava sve podnese i na sve se navikne", "Живая голова все терпит и ко всему привыкает"],
  ["Živ bio,srećan bio,kud god hodio!", "Будьте живы, будьте счастливы, куда бы вы ни пошли!"],
  ["Žive ko pas i mačka", "Они живут как собака и кошка"],
  ["Živeo i Bog te veselio!", "Живите долго и храни вас Бог!"],
  ["Živi ko riba na suvom", "Он живет, как рыба на суше"],
  ["Živi prosto- doživećeš sto", "Живи просто – проживешь сто лет"],
  ["Živ mi i zdrav bio!", "Пусть я буду жив и здоров!"],
  ["Živ mi ti!", "Я тебя люблю!"],
  ["Živ ti ja!", "Да здравствует я!"],
  ["Za brige je teško čuvati lepe devojke", "Трудно заботам удержать красивых девушек"],
  ["Za zlato rđa ne prijanja", "Ржавчина не прилипает к золоту"],
  ["Za jedan dobar dan mnogo se zlih pretrpi", "За один хороший день приходится страдать много плохих"],
  ["Za majstorom gora plače", "Гора плачет по хозяину"],
  ["Za nevolju babu vode, kad devojke ne nahode", "Они винят в беде бабушку, когда девочки нигде нет"],
  ["Za nevolju i medved igrati nauči", "Научитесь играть в медведя на неприятности"],
  ["Za neprijateljem ako i misliš ne govori zlo", "Даже если вы имеете в виду это, не говорите зло о враге"],
  ["Za čisto zlato rđa ne prijanja", "Ржавчина не прилипает к чистому золоту"],
  ["Zaboravnost je znak lenjosti", "Забывчивость – признак лени"],
  ["Zavadio bi dva oka u glavi", "Он вырвал бы два глаза на своей голове"],
  ["Zajedničkom konju, grbava su leđa", "Обыкновенная лошадь имеет горбатую спину"],
  ["Zaklela se zemlja raju da se svake tajne znaju", "Райская земля поклялась знать каждую тайну"],
  ["Zakrvavio očima ko divlji petao", "Налитые кровью глаза, как у дикого петуха"],
  ["Zbori pravo pa sedi gde ti drago", "Говори прямо и садись, где хочешь"],
  ["Zid ruši vlaga, a čovjeka briga", "Стена разрушается от влаги, а мужчине все равно"],
  ["Zima ne traži ljepote, nego toplote", "Зима ищет не красоты, а тепла"],
  ["Zima ujeda bez zuba", "Зимние укусы без зубов"],
  ["Zlatan lanac slobodu ne pruža", "Золотая цепь не дает свободы"],
  ["Zlato je čisto i u prljavoj kesi", "Золото чисто даже в грязном мешке"],
  ["Zlato se u vatri prebira, čovek u nevolji", "Золото просеяно в огне, человек в беде"],
  ["Zlo brzo dođe, a polako prođe", "Зло приходит быстро и проходит медленно"],
  ["Zlo je ko ne zna a učiti se ne da", "Зло тот, кто не знает и не хочет учиться"],
  ["Zloba jede dušu kao rđa gvožđe", "Злоба разъедает душу, как железная ржавчина"],
  ["Zna se zlato i u đubretu", "Ты знаешь, что в мусоре есть золото"],
  ["I vrag zna šta je pravo, ma neće, nego kako mu milo", "И черт его знает, что правильно, он этого не сделает, а как хочет"],
  ["I vuk vije jer ga rđa bije!", "А волк воет, потому что его бьет ржавчина!"],
  ["I zid ima uši, i plot ima oči", "И у стены есть уши, и у забора есть глаза"],
  ["I jedan je neprijatelj mnogo, a sto je prijatelja malo", "И один враг – много, а сто друзей – мало"],
  ["I kljuse i goveče teži na svoj zavičaj", "И клювы, и говядина стремятся к своей родине"],
  ["I krme rokne kad mu se čovjek javi", "И корма корабля, когда мужчина зовет его"],
  ["I loncem o kamen ili kamenom o lonac, teško loncu svakojako", "И горшок о камень или камень о горшок, все равно сильно ударяет по горшку"],
  ["I ljude poslušaj, i svoje pameti imaj", "И слушайте людей, и имейте свой собственный ум"],
  ["I najmudriji da proda sve što ima, ne može da kupi sve što nema", "Даже самый мудрый человек, продавший все, что у него есть, не сможет купить все, чего у него нет"],
  ["I sunce prolazi kroz kaljava mesta ali se ne okalja", "И солнце проходит сквозь мутные места, но не оскверняется"],
  ["I crna krava ima bijelo mleko", "Даже у черной коровы молоко белое"],
  ["Iver ne pada daleko od klade", "Щепка недалеко от бревна падает"],
  ["Ide vreme, nosi breme", "Время идет, несет бремя"],
  ["Iz prazne kuće i miši bježe", "Даже мыши убегают из пустого дома"],
  ["Iza dažda biće i sunca", "За дождем будет солнечный свет"],
  ["Izvalila magla panj", "Возник туманный пень"],
  ["Izvan očiju, izvan srca", "С глаз долой, из сердца"],
  ["Izgoreće slama, ali će i miši sesti gde ne valja", "Солома сгорит, но и мыши сядут там, где им не следует"],
  ["Izreke su ukras govora", "Пословицы – украшение речи"],
  ["Ili ne pokušavaj, ili dovrši", "Либо не пытайтесь, либо доведите дело до конца"],
  ["Imadoh – ne znadoh, izgubih – poznadoh", "У меня это было - я этого не знал, я потерял это - я это знал"],
  ["Inat babi dušu gubi", "Инат баби теряет душу"],
  ["Inat je zao zanat", "Упрямство – злое ремесло"],
  ["Inat je nesrećan zanat", "Упрямство — несчастливая профессия"],
  ["Ispeci pa reci", "Испеките и расскажите"],
  ["Ispod Mire sto đavola vire", "Сотня чертей выглядывает из-под Миры"],
  ["Isteruje mak na konac", "Он выгоняет мак на веревочке"],
  ["Istina i žena najlepše su - gole", "Правда и женщины самые красивые - обнаженные"],
  ["Istina i pravda pobeđuju", "Правда и справедливость побеждают"],
  ["Istina je da je svaki general posle rata pametan", "Это правда, что каждый генерал после войны умный"],
  ["Istina je ono ušta ubediš većinu da veruje", "Истина – это то, во что вы убеждаете поверить большинство"],
  ["Istina uvek najviše boli", "Правда всегда ранит больше всего"],
  ["Istorija je učiteljica života", "История – учитель жизни"],
  ["Istorija se ponavlja", "История повторяется"],
  ["Istoriju pišu pobjednici. To je razlog što je ona puna neistina!", "Историю пишут победители. Вот почему он полон лжи!"],
  ["Ja psu, a pas repu, a rep dlaci: idi dlaka ti si laka", "Я кусаю, а собака хвосты, а хвост волосы: иди волосы, ты легко"],
  ["Ja tikvu u vodu, a tikva iz vode", "Я опускаю тыкву в воду, и она выходит из воды"],
  ["Jak koren duge mladare pušta", "Сильный корень радуги прорастает"],
  ["Jača su dvojica nego sam Radojica", "Двое из них сильнее самого Радожицы"],
  ["Jače je djelo nego besjeda", "Действие сильнее речи"],
  ["Jedan drobi, drugi kusa", "Один давит, другой кусает"],
  ["Jedna glava, hiljada jezika", "Одна голова, тысяча языков"],
  ["Jedna greška, večna muka", "Одна ошибка, вечные муки"],
  ["Jedna lasta ne čini proleće", "Одна ласточка весны не делает"],
  ["Jedna šugava ovca celo stado ošuga", "Одна паршивая овца царапает все стадо"],
  ["Jedno krivo drvo ceo tovar raspe", "Одно кривое дерево распинает весь груз"],
  ["Jedno misli, drugo govori, treće tvori", "Один думает, другой говорит, третий творит"],
  ["Jednog gleda, dvojica se nadaju", "Один смотрит, двое надеются"],
  ["Jednom se lebac lomi", "Однажды хлеб сломался"],
  ["Jezik je više glava posekao nego sablja", "Язык разрубил больше голов, чем сабля"],
  ["Jezik kosti nema, ali kosti lomi", "Язык не имеет костей, но кости он ломает"],
  ["Jeftina roba kasu prazni", "Дешевые товары опустошают казну"],
  ["Junakova majka najpre zaplače", "Первой заплакала мать героя"],
  ["Kad bi se sve pameti iznele na vašar, svak bi se svoje mašio", "Если бы все мозги привезли на ярмарку, каждый бы свой выставил"],
  ["Kad Bog daje ne pitaj čiji je sin", "Когда Бог дает, не спрашивай, чей это сын"],
  ["Kad vidim onda ću i verovati", "Когда увижу, поверю"],
  ["Kad ideš vuku na čast, povedi psa sa sobom", "Когда пойдешь чествовать волка, возьми с собой собаку"],
  ["Kad je volje i zlo ide na bolje", "Когда есть воля, даже зло становится лучше"],
  ["Kad je glava luda, sve telo strada", "Когда голова сумасшедшая, страдает все тело"],
  ["Kad je dobre volje, svega je", "Когда у него хорошее настроение, все в порядке"],
  ["Kad je preša: đe si Peša? kad nije preša: oklen si Peša?", "Когда наступит пресса: где ты, Пеша? когда прессы нет: ты вооружен Пеша?"],
  ["Kad lažeš, kreću li ti se zubi", "Когда вы лжете, ваши зубы шевелятся?"],
  ["Kad legneš znači - predao si se", "Когда ты лежишь, это значит – ты сдался"],
  ["Kad lisica pridikuje, pazi dobro na guske", "Когда проповедует лиса, внимательно следите за гусями"],
  ["Kad mator pas laje, valja videti šta je", "Когда лает старая собака, вы должны увидеть, что это такое"],
  ["Kad mi ne možeš pomoći, nemoj mi odmagati", "Если ты не можешь мне помочь, не отговаривай меня"],
  ["Kad najviše grmi, najmanje kiše pada", "Когда больше всего грома, меньше всего идет дождь"],
  ["Kad se prase naije, ono korito prevali", "Когда поросенок рождается, корыто переполняется"],
  ["Kad se prase najede onda korito prevali", "Когда свинья сыта, тогда и корыто переполняется"],
  ["Kad se slože i slabi su jaki", "Когда они соглашаются, слабые становятся сильными"],
  ["Kad si u kolu, valja da igraš", "Когда ты в кругу, ты должен играть"],
  ["Kad sultan nazebe, raja kija", "Когда султан простужается, король чихает"],
  ["Kad čovek tone i za vrelo gvožđe se hvata", "Когда человек тонет, он хватается за раскаленный утюг"],
  ["Kad čoek nema svoga dobra, tuđe zlo premeće", "Когда у человека нет своего добра, чужое зло сметается"],
  ["Kakav pozdrav onaki i odzdrav", "Какое приветствие и прощание"],
  ["Kakav starješina, takva sva opština", "Такой старейшина, такой целый муниципалитет"],
  ["Kako došlo onako i prošlo", "Как пришло, так и прошло"],
  ["Ki da se svaka iščešljana uda!?", "Почему каждый причесанный волос должен выйти замуж!?"],
  ["Ko besjedi šta hoće, mora slušati sta neće", "Тот, кто проповедует то, что хочет, должен слушать то, чего он не хочет"],
  ["Ko rano rani dve sreće grabi", "Тот, кто наносит удар раньше, получает два состояния"],
  ["Ko brzo sudi, brzo se i kaje", "Кто скоро судит, тот быстро и раскаивается"],
  ["Ko vara na testu, vara na svakom mestu", "Кто жульничает на тесте, жульничает везде"],
  ["Ko visoko leti, nisko pada", "Тот, кто летает высоко, падает низко"],
  ["Ko voli da radi, dabogda mu se o glavi radilo", "Любой, кто любит работать, наверняка был занят"],
  ["Ko dva zeca vije, ne ulovi nijednog", "Кто гонится за двумя зайцами, не поймает ни одного"],
  ["Ko dete suviše voli, upropasti ga", "Тот, кто слишком любит ребенка, губит его"],
  ["Ko dobro počne, on je na pola radnje", "Кто хорошо начинает, тот уже на полпути"],
  ["Ko drugome jamu kopa, sam će u nju pasti", "Кто роет яму другому, тот сам в нее упадет"],
  ["Ko želi da peva, uvek će naći pesmu", "Кто хочет петь, тот всегда найдет песню"],
  ["Ko za tuđom vunom pođe, sam ostrižen kući dođe", "Кто пойдет за чужой шерстью, придет домой со своей стрижкой"],
  ["Ko zavisi od drugog, treba i njegovom psu da se umiljava", "Кто зависит от другого, его собаку нужно баловать"],
  ["Ko zna ne zja", "Кто знает, я не знаю"],
  ["Ko istinu gudi, gudalom ga po prstima biju", "Тех, кто ищет истину, бьют по пальцам луком"],
  ["Ko jarca za rog vuče, njemu je teško", "Тяжело приходится тому, кто тянет козла за рог"],
  ["Ko je jači taj tlači", "Кто сильнее, тот угнетает"],
  ["Ko je mnogo patio, mnogo je i zapamtio", "Тот, кто много страдал, многое помнил"],
  ["Ko jedanput slaže, drugi put mu se ne vjeruje iako istinu kaže", "Кто согласится один раз, тому второй раз не поверят, даже если он скажет правду"],
  ["Ko kasno brazdu zaore u jesen čičak obere", "Кто поздно пашет борозду, тот пожнет чертополох"],
  ["Ko laže za tebe, lagaće i protiv tebe", "Тот, кто лжет за вас, будет лгать против вас"],
  ["Ko lopovu gleda kroz prste i sam je lopov", "Кто смотрит сквозь пальцы вора, тот сам вор"],
  ["Ko lupeža krije, bolji ni on nije", "Тот, кто прячет вора, не лучше"],
  ["Ko ljeti hladuje, zimi gladuje", "Кто летом охлаждается, зимой голодает"],
  ["Ko ljude ne sluša, ni čovek nije", "Тот, кто не слушает людей, тоже не мужчина"],
  ["Ko me lani bio, ni sad mi nije mio", "Кому я нравился в прошлом году, я не нравлюсь сейчас"],
  ["Ko meće prst među tuđa vrata, otkinuće mu", "Кто сунет палец в чужую дверь, того ограбят"],
  ["Ko mnogo zbori - ili mnogo zna ili mnogo laže", "Кто много говорит – либо много знает, либо много врёт"],
  ["Ko na zvezde laje, ispašće mu zubi", "Кто лает на звезды, тот потеряет зубы"],
  ["Ko naglo počne, naglo će i završiti", "Кто резко начал, тот резко и кончит"],
  ["Ko ne čuva malo, ne može ni dosta imati", "Кто не откладывает мало, не может иметь много"],
  ["Ko ne čuva tuđe, neće imati ni svoje", "Кто не заботится о других, тот не будет иметь своего"],
  ["Ko nema sokola i kukavici se veseli", "Радуется тот, у кого нет сокола и трус"],
  ["Ko nema sreće u sebi neće je naći u svetu", "Кто не имеет счастья в себе, тот не найдет его в мире"],
  ["Ko neće brata za brata, 'oće tuđina za gospodara", "Кто не хочет брата за брата, тот будет иметь чужого господином"],
  ["Ko nije služio, ne umije ni zapovjedati", "Кто не служил, тот даже командовать не умеет"],
  ["Ko nosi, ne prosi", "Кто носит, тот не просит"],
  ["Ko odgoni mačke, vabi miše", "Кто отгоняет кошек, тот приглашает мышей"],
  ["Ko pita ne skita", "Кто спрашивает, тот не блуждает"],
  ["Ko pjeva, zlo ne misli", "Тот, кто поет, не мыслит зла"],
  ["Ko prati tuđ posao, svoj zaboravlja", "Кто следит за делами других, забывает свои"],
  ["Ko rakiju večera, vodu doručkuje", "Кто ест бренди на ужин, тот пьет воду на завтрак"],
  ["Ko rat želi, kod kuće ga imao", "Кто хочет войны, тот имел ее дома"],
  ["Ko s vragom tikve sadi, o glavu mu se razbijaju", "Кто тыквы с чертом посадит, тому на голову разобьются"],
  ["Ko sa đavolom tikve sadi o glavu mu se lupaju", "Кто посадит тыквы против головы дьявола, тот будет побит"],
  ["Ko svoj može biti, tuđ nek ne bude", "Кто может быть своим, пусть не будет чужим"],
  ["Ko se Boga ne boji i ljudi ne stidi beži od njega", "Кто не боится Бога и людей не стыдится, тот беги от него"],
  ["Ko se dima ne nadimi, taj se vatre ne ogreja", "Кто не надувается дымом, тот не согревается огнем"],
  ["Ko se na tuđim kolima vozi, neće daleko otići", "Тот, кто ездит на чужой машине, далеко не уедет"],
  ["Ko se ne muči u mladosti, kuku mu u starosti", "Кто не борется в молодости, тот будет страдать в старости"],
  ["Ko se ne stidi svoga obraza, neće ni moga", "Кто не стыдится своего лица, тот не постыдится и моего"],
  ["Ko se ne brani od gnjida, braniće se od vašiju", "Если не защитишься от гнид, то защитишься от вшей"],
  ["Ko se ovcom učini, kurjaci ga izjedu", "Кто притворится овцой, того съедят куры"],
  ["Ko se pred jednim klanja, pokazuje drugom leđa", "Тот, кто кланяется одному, показывает спину другому"],
  ["Ko se rada boji, taj u bedi živi", "Кто боится работы, тот бедствует"],
  ["Ko se seli, taj se ne veseli", "Тот, кто движется, не радуется"],
  ["Ko se tuđem zlu veseli, nek se svome nada", "Кто радуется чужому злу, пусть надеется на свое"],
  ["Ko se hvali sam se kvari", "Кто хвалится, портит себя"],
  ["Ko seje trnje, ne bere grožđe", "Кто сеет тернии, тот не пожнет винограда"],
  ["Ko spretnije traži, lakše dobije", "Кто ищет более умело, тот и добивается легче"],
  ["Ko staro ljubi, danke gubi", "Тот, кто любит старое, теряет свою благодарность"],
  ["Ko staro ne krpi, ni novo ne nosi", "Кто не чинит старое, тот не носит новое"],
  ["Ko ti iskopa oko? Brat rođeni! Odmah sam mislio čim je tako duboko", "Кто тебе глаз выколол? Брат родился! Я сразу подумал, раз уж так глубоко"],
  ["Ko traži veće, izgubi iz vreće", "Кто попросит больше, тот проиграет"],
  ["Ko tuđ posao gleda, svoj zaboravlja", "Кто смотрит на чужие работы, забывает свои"],
  ["Ko će naplesti uzica za tuđih gubica?", "Кто будет плести веревку для чужих потерь?"],
  ["Ko u krčmu ide, tuđu decu hrani", "Кто ходит в гостиницу, тот кормит чужих детей"],
  ["Ko u nebo pljuje na obraz mu pada", "Кто плюнет в небо, упадет ниц"],
  ["Ko umije, njemu dvije", "Кто сможет, тот получит два"],
  ["Ko hoće da ga drugi poštuju, valja najpre da se sam poštuje", "Если вы хотите, чтобы другие уважали вас, вы должны сначала уважать себя"],
  ["Ko hoće časno, ne moze lasno", "Тот, кто хочет чести, не может сделать это легко"],
  ["Ko čeka i dočeka", "Кто ждет и ждет"],
  ["Ko šta zagrize, teško ostavlja", "Кто что-то укусит, того трудно отпустить"],
  ["Koga nije, bez njega se može", "Кто нет, можно обойтись и без"],
  ["Koga su zmije klale i guštera se boji", "Кого змеи зарезали и ящерица боится"],
  ["Koga tišti taj i vrišti", "Кого он беспокоит и кричит"],
  ["Kod komšije, trava zelenija", "У соседа трава зеленее"],
  ["Koja da dvadeset litara varenike,", "Что дает двадцать литров вареники,"],
  ["Koja kokoš mnogo kakoće, malo jaja nosi", "Курица, которая много какает, несет мало яиц"],
  ["Koja se ne rekne, ona se ne čuje", "Что не сказано, то не услышано"],
  ["Koja se ovca od stada odvoji, vuk će je pojesti", "Любая овца, отделенная от стада, будет съедена волком"],
  ["Koja se često ogleda, slabo kuću nadgleda", "Что часто отражается, слабо контролирует дом"],
  ["Koja Crkva ne pomaže, ne valja joj se ni moliti", "Церковь, которая не помогает, не стоит того, чтобы ей молиться"],
  ["Ko je gotov na smrt, nikad nije rob", "Тот, кто готов умереть, никогда не будет рабом"],
  ["Ko je junak? Ko nadvlada svoje strasti", "Кто герой? Кто преодолевает свои страсти"],
  ["Koje pseto hoće da ubiju, poviču ~ bijesno je", "Какую собаку они хотят убить, кричали они ~ она в ярости"],
  ["Koji konja slamom hrani, sam kola vuče", "Кто кормит лошадь соломой, тот сам тащит телегу"],
  ["Koji se hrt silom u lov vodi, onaj zeca ne hvata", "Борзая, вынужденная охотиться, не ловит кролика"],
  ["Kojoj ovci svoje runo smeta, onđe nije ni ovce ni runa", "Какая овца не против своей руны, нет ни овцы, ни руна"],
  ["Koliko je nizbrdica onoliko je uzbrdica", "Подъёмов столько же, сколько и спусков"],
  ["Koliko ljudi toliko ćudi", "Сколько людей так возмущено"],
  ["Kome je Bog otac, lako mu je biti svetac", "Кому Бог отец, тому легко быть святым"],
  ["Kome svijet kroji kapu, onaj ide bez kape", "Кому мир делает шляпу, тот ходит без шляпы"],
  ["Krv nije voda", "Кровь – это не вода"],
  ["Krivac se i senke boji", "Виновник также боится теней"],
  ["Krpež i trpež po svijeta drže", "Тряпка и стол держат мир"],
  ["Kupuj prvo suseda, pa posle kuću", "Сначала купите соседа, потом дом"],
  ["Kurjak kožom plaća", "Куржак платит своей шкурой"],
  ["Kućni prag je najveća planina", "На пороге находится самая большая гора"],
  ["Lavica jedno okoti ali lava", "Львица рождает льва"],
  ["Laje ko pas na zvezde", "Он лает, как собака на звезды"],
  ["Lako je tuđim kurcem po koprivama mlatiti", "Легко забить чужой член крапивой"],
  ["Lako je zdravome bolesnoga savetovati", "Легко дать совет здоровому человеку, который болен"],
  ["Lako je iza šest volova gurati plug", "Легко толкать плуг за шестью волами"],
  ["Lako je ljubav steći, al’ je teško uzdržati", "Любовь легко получить, но трудно ее сохранить"],
  ["Lako ti je plitku vodu zamutiti i budalu naljutiti", "Вам легко замутить мелководье и разозлить дурака"],
  ["Lakše je skuvati željezo nego savladati ženinu tvrdoglavost", "Легче сварить железо, чем побороть женское упрямство"],
  ["Lakše je steći nego sačuvati", "Легче приобрести, чем сохранить"],
  ["Lakše je šta pokuditi nego moći sam učiniti", "Легче что-то сделать, чем уметь сделать это самому"],
  ["Lasni je kavgu zametnuti, al je teško kavzi dževap dati", "Легко начать драку, но трудно дать ответ"],
  ["Lasno je biti s tuđijem dobar", "Легко быть хорошим с кем-то другим"],
  ["Lasno je govoriti, al’ je teško tvoriti", "Легко говорить, но сложно создавать"],
  ["Lasno je zdravom bolesnog savetovati", "Легко дать совет здоровому человеку, который болен"],
  ["Lasno je pokraj čaša junakom biti", "Рядом с очками легко быть героем"],
  ["Lasno je tuđim rukama za vrelo gvožđe hvatati", "Легко схватить горячий утюг чужими руками"],
  ["Lasno je u Dunav kamen baciti, al ga je teško izvaditi", "Легко бросить камень в Дунай, но трудно его вытащить"],
  ["Lepu ženu i vinograd pored puta ne treba imati", "У тебя не должно быть красивой жены и виноградника на обочине дороги"],
  ["Lovac je da lovi, a prepelici da se čuva", "Охотник должен охотиться, а перепел – охранять"],
  ["Ludi boj biju, a mudri vino piju", "Сумасшедшие дерутся, а мудрые пьют вино"],
  ["Ludi se penje da visoko sjede, a kad bude do bjesede, kaje se što onđe sjede", "Сумасшедшие люди забираются высоко, а когда добираются до кафедры, жалеют, что там сидели"],
  ["Ljeti od hlada do hlada, a zimi od jada do jada", "Летом из тени в тень, а зимой от нищеты к нищете"],
  ["Ljubav vera i nada ostavile traga", "Любовь, вера и надежда оставили свой след"],
  ["Ljubav dugo trpi", "Любовь долго терпит"],
  ["Ljubav za ljubav, sirenje za pare", "Любовь за любовь, сыр за деньги"],
  ["Ljubav i sloga nemoguće omoguće", "Любовь и гармония делают невозможное возможным"],
  ["Ljubav je jedina strast koja ne trpi prošlost, ni budućnost", "Любовь – единственная страсть, которая не страдает ни от прошлого, ни от будущего"],
  ["Ljubav je lepa ali slepa", "Любовь прекрасна, но слепа"],
  ["Ljubav je puna meda i jeda", "Любовь полна меда и еды"],
  ["Ljubav ne traje dugo ako ukloniš svađe", "Любовь не продлится долго, если убрать раздоры"],
  ["Ljubav nema godina: ona se uvek rađa", "У любви нет возраста: она рождается всегда"],
  ["Ljubav pametnog zaluđuje", "Любовь умных сводит с ума"],
  ["Ljubav prema istini je glavna i najvažnija crta karaktera. Onaj koji laže - nema karaktera", "Любовь к истине – главная и самая важная черта характера. У того, кто лжет, нет характера"],
  ["Ljubav prema otadžbini ne zna za tuđe granice", "Любовь к Родине не знает границ"],
  ["Ljubavna čarolija u pogledu tvom,ti si sreću donijela srcu slomljenom", "Приворот на твоих глазах, ты принесла счастье разбитому сердцу"],
  ["Ljubazan ali jedva čeka da mu vidi leđa", "Добрый, но не могу дождаться, чтобы увидеть его спину"],
  ["Ljubi bližnjega svoga kao samoga sebe", "Возлюби ближнего своего, как самого себя"],
  ["Ljudi se najviše muče zbog hleba i ljubavi", "Больше всего люди борются за хлеб и любовь"],
  ["Ljudi se po odjelu sretaju, a po pameti prate", "Люди встречаются по отделам и следят друг за другом по разведке"],
  ["Ljudi su gusto posijani, ali rijetko niču", "Люди сеются густо, но всходят редко"],
  ["Ljut čovek ne zadrži prijatelja", "Злой человек не держит друга"],
  ["Magarac - magarac i pod zlatnim sedlom", "Осел – осел и под золотым седлом"],
  ["Mala sjekira veliki dub povali", "Маленький топор срубил большой дуб"],
  ["Malena je tica prepelica, al umori konja i junaka", "Перепелка маленькая, но утомляет лошадь и богатыря"],
  ["Mali Hodža, ispod velikog turbana", "Маленький Ходжа, под большим тюрбаном"],
  ["Mačija igračka - mišija smrt", "Кошачья игрушка – мышиная смерть"],
  ["Među ćoravijem, ko ima jedno oko meću ga za Cara", "У чорави императором считается тот, у кого есть один глаз"],
  ["Mi o vuku, a vuk na vrata", "Мы о волке и волке у двери"],
  ["Mlado se drvo savija", "Молодое дерево склоняется"],
  ["Mladost – radost", "Молодость - радость"],
  ["Mlati rukom, ko kobila repom", "Хлопает рукой, как кобылий хвост"],
  ["Mnogi ljudi su kao satovi: pokazuju jedno vreme, a otkucavaju drugo", "Многие люди подобны часам: показывают одно время, а бьют другое"],
  ["Mnogo asova treba dok se istina sahrani", "Требуется много козырей, прежде чем истина будет похоронена"],
  ["Mnogo znati, znači pre vremena ostariti", "Знать много – значит стареть раньше времени"],
  ["Mnogo zrna gomilu načine", "Много зерен, много способов"],
  ["Mnogo je mački celo pečenje", "Целое жаркое — это слишком много для кошки"],
  ["Mnogo treba vremena da od deteta čovek bude", "Чтобы из ребенка превратиться в мужчину, нужно много времени"],
  ["Mrav i pčela uče kako se teče", "Муравей и пчела учатся течь"],
  ["Mrtvu kurjaku rep mjeri", "Мертвого петуха измеряют по хвосту"],
  ["Muka ide po ljud`ma", "Боль преследует людей"],
  ["Mučno je mudrome među budalama besjediti", "Больно говорить с мудрым среди дураков"],
  ["Muči đeca kad stariji govore", "Детей беспокоит, когда говорят старшие"],
  ["Na jednu glavu ne može se dve kape", "Нельзя носить две шляпы на одной голове"],
  ["Na jeziku med, a u srcu jed", "Мед на языке и мед в сердце"],
  ["Na kurjake vika, a lisice meso jedu", "Он кричит на кур, а лисы едят мясо"],
  ["Na mlađima svijet ostaje", "Мир держится на младших"],
  ["Na muci se poznaju junaci", "Герои познаются через страдания"],
  ["Na poruke vuk mesa ne ije", "Волк не ест мясо на сообщениях"],
  ["Na psa koji bježi svako viče", "Все кричат ​​на бегущую собаку"],
  ["Na silu se ne može voleti", "Нельзя любить насильно"],
  ["Na sirotnoga svakom je laka ruka", "Каждый имеет легкую руку к бедным"],
  ["Na sokolu je malo mesa", "Мяса на соколе мало"],
  ["Na tuđim leđima lako je breme", "Это легкая ноша на чужой спине"],
  ["Na ugašenu vatru vode ne sipaj", "Не лейте воду на потухший огонь"],
  ["Na usamljenost osuđuju prijatelji", "Одиночество осуждается друзьями"],
  ["Navalio ko zima na gola čovjeka", "Оно упало, как зима на голого человека"],
  ["Navika je jedna muka al odvika dvije", "Привычка – это одна боль, а отказ от нее – это две"],
  ["Navika je jedna muka, a odvika dvije muke", "Привычка – одна боль, привычка – две боли"],
  ["Nad silom sila je pravda", "Справедливость важнее силы"],
  ["Naduri se ko ćuran na bunjištu", "Надулся как индюк на свалке"],
  ["Najviše se vole ljudi koji imaju iste vrline, najviše se mrze koji imaju iste mane", "Людей, обладающих одинаковыми достоинствами, любят больше всего, больше всего ненавидят тех, у кого такие же недостатки"],
  ["Najgore je kad padneš u njenim očima", "Самое страшное, когда ты падаешь в ее глазах"],
  ["Najpre ispred svoje kuće počisti", "Сначала наведите порядок перед домом"],
  ["Najčešće opeče potajni žar", "Чаще всего горит тайный уголек"],
  ["Nalik gajde na muziku", "Как волынка под музыку"],
  ["Namrgodio se kao da će mu kiša iz čela udariti", "Он нахмурился, как будто дождь вот-вот ударил ему в лоб"],
  ["Napao ko smrt na život", "Напал как смерть на жизнь"],
  ["Ne boj se onoga kome nisi dobro učinio", "Не бойтесь того, что у вас не получилось"],
  ["Ne bojim se smrti nego zla života", "Я не боюсь смерти, но зла жизни"],
  ["Ne budi otrov da truješ drugog i ne budi med da te drugi poližu", "Не будьте ядом, чтобы отравлять других, и не будьте медом, чтобы другие лизали его"],
  ["Ne valja donde leteti dokle krila ne narastu", "Нехорошо летать, пока крылья не вырастут"],
  ["Ne valja jarca za baštovana namestiti", "Нехорошо садовнику заводить козу"],
  ["Ne valja svakoj tici kobac biti", "Не каждый заслуживает быть воробьем"],
  ["Ne viči, ono što te je snašlo nećes tako oterati", "Не кричи, ты не прогонишь то, что тебя так поразило"],
  ["Ne vjeruj prijatelju za trpezom, nego na vratima od tamnice", "Доверься другу не за столом, а у дверей темницы"],
  ["Ne goji se prase uoči Božića", "Не откармливайте свинью перед Рождеством"],
  ["Ne gori nam pod noktima", "Он не горит под ногтями"],
  ["Ne gori obraz od sunca, već od poštenih ljudi", "Лицо обожжено не солнцем, а честными людьми"],
  ["Ne gori ti pod nogama", "Не гори под ногами"],
  ["Ne guraj nos u tuđa posla", "Не суй нос в чужие дела"],
  ["Ne da se posranom do potoka", "Не переноси дерьмо на стрим"],
  ["Ne da se, ali će se dati. Vuk Karadžić", "Не дано, но будет дано. Вук Караджич"],
  ["Ne zna da besjedi, a ne ume da ćuti", "Он не умеет говорить, но и не умеет молчать"],
  ["Ne zaboravljaj na smrt, i ona tebe ne zaboravlja", "Не забывайте смерть, и она не забудет вас"],
  ["Ne jedu vuci meso po poruci", "Они не едят волчье мясо по требованию"],
  ["Ne kupuje se sloboda na vašaru", "Свободу не покупают на ярмарке"],
  ["Ne laje kuja radi sela, nego radi sebe", "Сука лает не для деревни, а для себя"],
  ["Ne lipši magarče do zelene trave", "Не пропустите осла в зеленую траву"],
  ["Ne može se kriva Drina ramenom ispraviti", "Кривую Дрину плечом не расправить"],
  ["Ne možeš dlanom sunce zakloniti", "Вы не можете закрыть солнце ладонью"],
  ["Ne niče sve što se seje", "Не все, что посеяно, всходит"],
  ["Ne pada snijeg da pomori svijet, već da svaka zvjerka svoj trag pokaže", "Снег идет не для того, чтобы убить мир, а для того, чтобы каждое животное могло показать свой след"],
  ["Ne plaši vuka s' kozijom mješinom", "Не пугайте волка козьей смесью"],
  ["Ne sveti se zlotvoru, no čekaj na Boga", "Не поклоняйтесь злодею, но ждите Бога"],
  ["Ne stoji kuća na zemlji, nego na ženi", "Дом стоит не на земле, а на женщине"],
  ["Ne treba kvocati, nego jaja nositi", "Следует не крякать, а нести яйца"],
  ["Ne trči, ko ždrebe, pred rudu", "Не беги, как жеребенок, перед рудой"],
  ["Ne hvataj se u kolo ako ne znaš igrati", "Не попадайтесь в ловушку, если не знаете, как играть"],
  ["Nevolja svačemu čoveka nauči", "Невзгоды учат человека всему"],
  ["Neko se za list sakrije, nekoga ni dub da pokrije", "Кто-то прячется за листом, кто-то даже не удосуживается прикрыться"],
  ["Nekom i olovo plivje, a nekome i slamka tone", "У кого-то свинец плавает, у кого-то солома тонет"],
  ["Nema većeg zla, od zle pameti", "Нет большего зла, чем злой ум"],
  ["Nema zime dok ne padne inje", "Зимы не будет, пока не выпадут морозы"],
  ["Nema leta dok se ne zakikoće lug", "Лета не будет, пока щелок не захихикает"],
  ["Nema ništa nesnosnije od bogate žene", "Нет ничего невыносимее богатой женщины"],
  ["Nema tu ćuka, da nije vuka", "Нет быка, если нет волка"],
  ["Nemirna savest je i tužilac i sudija u isto vreme", "Неспокойная совесть – это и обвинитель, и судья одновременно"],
  ["Nemogoše pojedoše, a nekće se sve popiše", "Есть невозможно было, а иногда все перечислялось"],
  ["Nemoj, pa se neboj", "Не надо, не бойся"],
  ["Nepostojan kao Mart mjesec", "Непостоянен, как месяц март"],
  ["Nepravdu ne vole ni oni koji ju čine", "Это не нравится даже тем, кто совершает несправедливость"],
  ["Nesta blaga, nesta prijatelja", "Ни сокровищ, ни друзей"],
  ["Neće kruška ispod trešnje", "Под вишней не будет груши"],
  ["Neće kuče na kuče", "Они не будут ходить от двери к двери"],
  ["Ni vratiša ni platiša", "Ни возвращает, ни платит"],
  ["Ni najbolji petao ne može da izmeni vreme", "Даже самый лучший петух не сможет изменить погоду"],
  ["Nije vuk ničije sreće izio", "Он не был волком чьей-то удачи"],
  ["Nije dopušteno sve znati", "Не позволено знать все"],
  ["Nije žita bez kukolja ni naroda bez izroda", "Нет зерна без плевел, и нет народа без потомства"],
  ["Nije zlato sve što sija", "Не все то золото, что блестит"],
  ["Nije nikakva majstorija među dobrima dobar biti", "Среди хороших быть хорошими не значит быть мастером"],
  ["Nije svaka muka dovijeka", "Не каждая боль длится вечно"],
  ["Nije siromah ko malo ima, već ko mnogo želi", "Бедный не тот, у кого мало, а тот, кто хочет многого"],
  ["Nije umrla baba od korbe, već od prazne torbe", "Бабушка умерла не от корзины, а от пустой сумки"],
  ["Nije čovjeku žao na malo nego na nepravo", "Человек жалеет не о мелочи, а о неправде"],
  ["Nijedna muka nije dovijeka", "Никакая боль не вечна"],
  ["Nijedno zlo ne prođe neopaženo", "Ни одно зло не остается незамеченным"],
  ["Nikad zao na gorega neće", "Он никогда не будет злым"],
  ["Niko ne zna šta je dobro, samo onaj koji se zla napatio", "Никто не знает, что такое добро, только тот, кто пострадал от зла"],
  ["Niko ne može natkati mahrama da cijelom svijetu usta poveže", "Никто не может надеть махрам, чтобы заткнуть рот всему миру"],
  ["Niko ne može tako malo da me plati, koliko malo ja mogu da radim", "Никто не может платить мне так мало, как мало я могу работать"],
  ["Niko ne može cijelom svijetu kolača namijesiti", "Никто не сможет испечь торт на весь мир"],
  ["Niko ne ume da se veseli kao sirotinja", "Никто не умеет радоваться так, как бедняк"],
  ["Niko nije zadovoljan svojim bogatstvom i nezadovoljan", "Никто не доволен своим богатством и не удовлетворен"],
  ["Niko sam sebi sudija ne može biti", "Никто не может быть судьей самому себе"],
  ["Niko se nije naučen rodio", "Никто не рождается образованным"],
  ["Niče đe ga ne siju", "Они его нигде не сеют"],
  ["Ništa nije lepše od osmeha zaljubljene žene", "Нет ничего прекраснее, чем улыбка влюбленной женщины"],
  ["Ništa nije tako loše da ne može biti gore", "Нет ничего настолько плохого, чтобы не могло быть хуже"],
  ["Nov bunar kopaj, u star ne pljuj", "Рой новый колодец, не плюй в старый"],
  ["Nove čizme i nova gospoda najvećma tište", "Новые ботинки и новые джентльмены — это самое важное"],
  ["Novci kad odlaze imaju sto nogu, kad dolaze samo dvije", "У денег есть сотня ног, когда они уходят, но только две, когда они приходят"],
  ["Novci sitno zveče, al' se daleko čuju", "Монеты звенят, но слышно далеко"],
  ["Nužda nauči i babu igrati", "Он также должен научиться играть в бабушку"],
  ["Nj", "Нью-Джерси"],
  ["Njegovo jajce nema žumance", "В его яйце нет желтка"],
  ["Njegovo je svako dvožučno", "Все обоюдоострые"],
  ["Njemu i voda uzbrdo teče", "Для него тоже вода течет в гору"],
  ["Njemu i jare i pare, a tebi brabonjci (izmet ovce)", "Ему козленок и самец, а вам брабони (овечьи экскременты)"],
  ["Njiva traži radnika a žena neradnika (odmorna čoveka)", "Поле ищет рабочего, а женщина ищет нерабочего (отдыхающего мужчину)"],
  ["Njiva hoće motiku, a ne molitvu", "Полю нужна мотыга, а не молитва"],
  ["Njega može da voli samo rođena majka", "Любить его может только собственная мать"],
  ["Njega ni metak neće", "Его не убьет даже пуля"],
  ["Njega se ni vrapci ne boje", "Его не боятся даже воробьи"],
  ["Njegova je reč i prva i poslednja", "Его слово – и первое, и последнее"],
  ["Njegova kokoška vredi više nego nečiji soko", "Его курица стоит больше, чем чей-то сокол"],
  ["Njegova se poštuje", "Его уважают"],
  ["Njemu i Bog gleda kroz prste", "Даже Бог смотрит сквозь пальцы"],
  ["Njemu ni kesu ni iz kese", "У него нет ни сумки, ни сумки"],
  ["Njima je obraz iza leđa", "Их лицо скрыто за спиной"],
  ["O jarane, bole li te rane?", "Ох, мальчик, твои раны болят?"],
  ["O neprijatelju ne govori zlo, nego misli", "Он не говорит зло о враге, а думает"],
  ["Obećanje, ludom radovanje", "Обещание, безумная радость"],
  ["Obilazi ko kiša oko Kragujevca", "Вокруг Крагуеваца идет дождь"],
  ["Običan život je jači od mudrih knjiga", "Обычная жизнь сильнее мудрых книг"],
  ["Oboje je zlo: i svima verovati, i nikome", "И то, и другое — зло: доверять всем и никому"],
  ["Ovca je vučije štene dojila i uzgojila", "Овца выкормила и вырастила волчонка"],
  ["Od govneta pita ne biva", "Из дерьма не делают пирогов"],
  ["Od zla gore, a od dobra bolje ima", "Есть хуже зла и лучше добра"],
  ["Od inata nema goreg zanata", "Нет худшего ремесла, чем злоба"],
  ["Od lopova je sigurno što ne dosegne", "Защищено от вора, что не доберется"],
  ["Od male iskre velika vatra", "Из маленькой искры большой пожар"],
  ["Od mira glava ne boli", "Голова не болит от покоя"],
  ["Od pruta biva veliko drvo", "Плетеная ткань становится большим деревом"],
  ["Od samoće ništa gore nema", "Нет ничего хуже одиночества"],
  ["Od Svetog Ilije, sunce sve milije", "От святого Илии светит солнце"],
  ["Ozbiljno odgodimo za sutra", "Давайте серьезно отложим это до завтра"],
  ["Onaj ko te se boji kad si prisutan, mrzi te kad si odsutan", "Тот, кто боится тебя, когда ты присутствуешь, ненавидит тебя, когда тебя нет"],
  ["Onaj te voli koji te nagoni na plač", "Тот, кто любит тебя, заставляет тебя плакать"],
  ["Onome, ko ume da čeka, vremenom sve dolazi", "К тому, кто умеет ждать, все приходит со временем"],
  ["Oparen kašu hladi", "Заваренная каша остывает"],
  ["Osmehni se svakome jutru", "Улыбайтесь каждое утро"],
  ["Osoba kojoj 'treba' ljubav poslednja je koja će je dobiti", "Человек, которому «нуждается» в любви, получает ее последним"],
  ["Ostavimo vremenu i našoj rešenosti", "Давайте оставим это на усмотрение времени и нашей решимости"],
  ["Oteto - prokleto", "Похищен – проклят"],
  ["Otišao da mu vide noge put", "Пошел посмотреть на его ноги"],
  ["Otkud sam se nadao da me sunce ogrije, otuda me led bije", "Откуда я надеялся, что меня согреет солнце, оттуда меня бьет лед"],
  ["Oštar nož ljuto seče, a oštar jezik i gore", "Острый нож сердито режет, а острый язык обжигает"],
  ["Pametan lako ide, a brzo dođe", "Смарт идет легко и приходит быстро"],
  ["Pametna glava - stotinu ruku", "Умная голова – сто рук"],
  ["Pametni ljudi uče se na tuđim greškama, budale na vlastitim", "Умные люди учатся на чужих ошибках, дураки – на своих"],
  ["Pijana glava ne nosi barjaka", "Пьяная голова не несет знамени"],
  ["Po glasu ptica, a po šapama se lav poznaje", "Льва узнают по птичьему голосу и по лапам"],
  ["Po drugi put lisicu ne uhvati u gvožđe", "Второй раз не поймал лису в утюг"],
  ["Podnosi, a ne tuži na ono čemu se ne može izbeći", "Он подчиняется и не судится за то, чего нельзя избежать"],
  ["Pozajmi rukama, pa traži nogama", "Бери руками, а потом проси ногами"],
  ["Poklon dušu gubi", "Подарок теряет душу"],
  ["Poklon i okatog zaslepi", "Подарок ослепляет глаза"],
  ["Pomogneš li zlog u zlu, dobićeš ga za neprijatelja", "Если ты поможешь злу во зле, ты приобретешь его во врага"],
  ["Pošten manje obeća, nego što učini", "Честный человек обещает меньше, чем делает"],
  ["Preko dubokog potoka prelazi poslednji", "Последний пересекает глубокий ручей"],
  ["Primaš li poklone, prodaješ slobodu", "Если вы принимаете подарки, вы продаете свободу"],
  ["Pokraj suha drveta i sirovo izgori,", "Рядом с сухими дровами и горящими сырыми,"],
  ["Pop đaku, đak crkvenjaku", "Поп студенту, студент церковнику"],
  ["Posle boja kopljem u trnje", "После цветов я вонзаюсь в шипы"],
  ["Počni! Započeto je pola dela", "Начинать! Половина дела начата"],
  ["Poštenje je ravno sa životom", "Честность равна жизни"],
  ["Pošto se kola slome, mnogi put kazuju", "Поскольку машина ломается, многие прощаются"],
  ["Pošto se napiješ vode, ne muti izvor za sobom", "Когда вы пьете воду, не оставляйте фонтан позади себя"],
  ["Poštuj, ako hoćeš da si poštovan", "Уважайте, если хотите, чтобы вас уважали"],
  ["Prav se smije, a kriv se krije", "Правильный смеется, а неправильный прячется"],
  ["Pravda ne može ni utonuti ni izgoreti", "Справедливость не может ни утонуть, ни сгореть"],
  ["Prazna vreća uspravno ne može da stoji", "Пустая сумка не может стоять вертикально"],
  ["Prva je vrlina biti bez mane", "Первая добродетель – быть без порока"],
  ["Prvo pojedi svoje pa tuđe", "Сначала ешь свое, потом чужое"],
  ["Preveo ga žednog preko vode", "Принес ему жажду через воду"],
  ["Preko brda vrba mrda na vrh vrbe leži zec", "За ивовым холмом на вершине ивы лежит кролик"],
  ["Preko preče naokolo bliže", "Через бар вокруг ближе"],
  ["Prelomiti jezik — ovladati izgovorom, početi govoriti, progovoriti", "Ломать язык — освоить произношение, начать говорить, говорить"],
  ["Prema guberu se valja pružiti", "По словам губера, надо достучаться"],
  ["Prijatelj je najbolja imovina u životu", "Друг – лучшее богатство в жизни"],
  ["Prijatelj se u nevolji poznaje, kao zlato u vatri", "Друг в беде познается, как золото в огне"],
  ["Prijatelju i neprijatelju daj uvek dobar savet, jer prijatelj ga prihvata, a neprijatelj ne", "Всегда давайте хороший совет другу и врагу, потому что друг его принимает, а враг нет"],
  ["Priča sebi u bradu", "Он разговаривает сам с собой"],
  ["Pričaj zidu", "Поговори со стеной"],
  ["Prokleta nek je zemlja u kojoj su psi pušteni a kamenje svezano", "Проклята земля, где отпущены псы и связаны камни"],
  ["Proricala baba da će biti posle kiše blata", "Бабушка напророчила, что после дождя будет грязь"],
  ["Ptica po perju, a čovjek se po besjedi poznaje", "Птицу узнают по перьям, а человека узнают по его словам"],
  ["Ravnodušnost je najbolji način u brigama", "Безразличие – лучший способ справиться с тревогами"],
  ["Radi pa se ne boj gladi", "Работай, чтобы не бояться голода"],
  ["Rad je najbolja lutrija", "Работа – лучшая лотерея"],
  ["Rano voće brzo trune", "Ранние плоды быстро гниют"],
  ["Razdrta vreća ne može se napuniti", "Порванный мешок невозможно наполнить"],
  ["Ralo i motika svijet hrane", "Плуг и мотыга в мире еды"],
  ["Ranoranilac i docnolegalac kuću teče", "Домом управляют тот, кто рано встает, и тот, кто встает поздно"],
  ["Rat je kao oblak pa nekog orosi, nekog pokvasi", "Война как облако, она делает кого-то росистым, кого-то мокрым"],
  ["Rat, rak i rad, su tri najgore srpske reči", "Война, рак и работа – три худших сербских слова"],
  ["Rđa jede gvožđe, a tuga srce", "Ржавчина съедает железо, а печаль съедает сердце"],
  ["Rđa ne prijanja za zlato", "Ржавчина не прилипает к золоту"],
  ["Rđav je čovek koji se tuđem zlu raduje", "Злой человек – это тот, кто радуется чужому злу"],
  ["Rep glavi ne zapovijeda", "Хвост не командует головой"],
  ["Retka je sreća bez gordosti", "Счастье без гордости – редкость"],
  ["Reč 'sutra' je izmišljena za decu i za neodlučne ljude", "Слово «завтра» придумано для детей и для нерешительных людей"],
  ["Reči su kao pčele, one su istovremeno i med i žaoka", "Слова как пчелы: они и мед, и жалят одновременно"],
  ["Reči treba meriti, a ne brojati", "Слова следует измерять, а не считать"],
  ["Riba od glave smrdi, a od repa se čisti", "Рыба воняет с головы, а чистится с хвоста"],
  ["Riba ribi grize rep", "Рыба кусает рыбью хвост"],
  ["Riba ribu, a ribar obe", "Он ловит рыбу, а рыбак делает и то, и другое"],
  ["Ribe se love udicom, a ljudi rečima", "Рыбу ловят на крючок, а людей на слова"],
  ["Rizik stvara kapital", "Риск создает капитал"],
  ["Roba govori, trgovac laje, gazda pare daje", "Товар говорит, торговец лает, начальник деньги дает"],
  ["Robija nije teška, već robijaši", "Тюрьма не тяжелая, заключенные"],
  ["Rovitom govnetu malo vode fali(kiše treba)", "Дерьму Ровита нужно немного воды (нужен дождь)"],
  ["Rodi me majko srećnog, pa me baci u trnje", "Счастливая мать меня родила, а потом бросила в тернии"],
  ["Ruga se lonac loncu, a oba su crna", "Горшок издевается над горшком, и оба черные"],
  ["Rugovka je klela: Umro joj sin da bi mogla lošu *snahu da pusti", "Руговка проклялась: сын умер, чтобы она отпустила свою плохую *невестку"],
  ["Ruka koja daje ne oskudeva", "Рука дающая не имеет недостатка"],
  ["Ruka ruku mije obraz obad bije", "Моя рука гладит мою щеку"],
  ["Rumena zora, mokra gora", "Румяный рассвет, мокрая гора"],
  ["S brda s dola", "Вниз по холму"],
  ["S kim si takav si", "Ты тот, с кем ты есть"],
  ["S konja na magarca", "От лошади до осла"],
  ["S kozom na oranje", "С пашущей козой"],
  ["S pola jezika (reći, kazati) — poluglasno, tiho (reći, kazati)", "Полъязыка (сказать, сказать) — тихим голосом, тихо (сказать, сказать)"],
  ["Sa dva ili tri čoveka još možeš pričati a ljudi su već razuzdana rulja", "С двумя-тремя людьми еще можно поговорить, а люди уже буйная толпа"],
  ["Sablju paši konja jaši pa u boj se spremaj", "Наточите коня на саблю, оседлайте его и готовьтесь к бою"],
  ["Sad smo kvit", "Мы квиты сейчас"],
  ["Sakrio se u mišiju rupu", "Он спрятался в мышиной норе"],
  ["Samo vi vršljajte (što bi rekli naši stari),poslje ja moram sve da sravnavam", "Только ты шлифоваешь (как сказали бы наши старшие), потом мне все выравнивать"],
  ["Samo nek komšiji crkne krava", "Просто позволь соседской корове мычать"],
  ["Sačuvaj se Bože, od mirnog sina kod opake snaje", "Спаси меня, Боже, от мирного сына со злой невесткой"],
  ["Sva je huka na vuka, a iza vuka i lisica sita", "Все волки ревут, а за волком лиса"],
  ["Sva mu je pamet na jeziku. Ko govori šta mu na usta dođe", "Его ум полностью сосредоточен на языке. Кто говорит то, что приходит ему в рот"],
  ["Svagđe je dobro, ali kod kuće je najbolje", "Везде хорошо, но дома лучше"],
  ["Svak za se koze pase!", "Каждый человек пасет своих коз!"],
  ["Svak po sebi sudi o drugome", "Каждый судит другого по себе"],
  ["Svaka batina ima dva kraja", "У каждого клуба есть два конца"],
  ["Svaka budala ima svoje veselje", "У каждого дурака свое веселье"],
  ["Svaka žurba je spora", "Всякая спешка медленна"],
  ["Svaka je šala pola istine", "Каждая шутка — половина правды"],
  ["Svaka knjiga ima svoju sudbinu", "У каждой книги своя судьба"],
  ["Svaka muka za vremena, a sramota zavijeka", "Вся боль на время и стыд навсегда"],
  ["Svaka ptica svome jatu leti", "Каждая птица летит к своей стае"],
  ["Svaka kamena glava, jednim udarcem čekića se razbija", "Каждая каменная голова разбивается одним ударом молота"],
  ["Svaki je početak težak", "Каждое начало сложно"],
  ["Svako ima prava koliko ima moći", "У каждого столько же прав, сколько и власти"],
  ["Svako je svoje sreće kovač", "Каждый сам творит свою удачу"],
  ["Svako čudo za tri dana", "Каждое чудо за три дня"],
  ["Sveća je sveća ako je slepac i ne vidi", "Свеча — это свеча, если ее не видит слепой"],
  ["Svojstvo je ludosti tuđe mane videti, a svoje zaboraviti", "Видеть недостатки других людей и забывать свои собственные — это признак глупости"],
  ["Svuda pođi, kući dođi", "Иди куда угодно, возвращайся домой"],
  ["Sirotinjo, i Bogu si teška", "Бедняжка, ты трудна даже для Бога"],
  ["Sit gladnom ne veruje", "Сытый не доверяет голодному"],
  ["Slabo slovi, ali dobro lovi", "У него плохая репутация, но охотится он хорошо"],
  ["Sloboda je, ne da radiš šta hoćeš, već da ne radiš, šta nećeš", "Свобода – это не делать того, что хочешь, но и не делать того, чего не хочешь"],
  ["Slogom rastu male stvari, neslogom se i najveće raspadaju", "При гармонии мелочи растут, при разладе даже самые большие распадаются"],
  ["Slađa je i milosna reč, nego nemilosna milostinja", "Доброе слово слаще беспощадной милостыни"],
  ["Spolja je gladac, a iznutra jadac", "Он гладкий снаружи, но едок внутри"],
  ["Spram sveca i tropar, spram anđela i krila", "Против святителя и тропаря, против ангела и крыльев"],
  ["Snaga na usta ulazi", "Власть в рот входит"],
  ["Srećan je onaj koji sedi u svojoj kući", "Счастлив тот, кто сидит в своем доме"],
  ["Srce oće, a dupe klokoće", "Сердце бьется и задница булькает"],
  ["Srditom popu prazni bisazi", "Пустые седельные сумки с сердитым хлопком"],
  ["Srebrno sedlo ne čini dobra konja", "Серебряное седло не делает хорошую лошадь"],
  ["Sreća se sastoji od izbegnutih nesreća", "Счастье состоит из предотвращенных случайностей"],
  ["Srećan je onaj koji sedi u svojoj kući", "Счастлив тот, кто сидит в своем доме"],
  ["Stari vuk, pasja sprdačina", "Старый волк, собачья шутка"],
  ["Starije je jutro od večeri", "Утро старше вечера"],
  ["Starci bolje na daleko vide", "Пожилые люди лучше видят на расстоянии"],
  ["Starost je bolest od koje svako umire", "Старость – болезнь, от которой умирают все"],
  ["Sto ljudi, sto ćudi", "Сто людей, сто характеров"],
  ["Strah je već pola nesreće", "Страх – это половина беды"],
  ["Strpljenja! Vremenom od trave postaje mleko", "Терпение! Со временем трава превращается в молоко"],
  ["Takav je čovek, samo onima najviše zavidi kojima najviše duguje", "Вот такой человек, он завидует только тем, кому он больше всего обязан"],
  ["Tvrd je orah voćka čudnovata,ne slomi je al zube polomi", "Твёрдый орех — странный фрукт, не сломай его, он сломает тебе зубы"],
  ["Tamnica je za ljude načinjena", "Подземелье было создано для людей"],
  ["Terao zeca pa isterao vuka", "Погнался за кроликом и прогнал волка"],
  ["Teško volu u jarmu i čoveku u najmu", "Горе запряженному быку и наемнику"],
  ["Teško domu u kom nema sloge", "Горе дому, в котором нет гармонии"],
  ["Teško zemlji kuda prođe vojska", "Горе стране, где проходит армия"],
  ["Teško je dobro videti, a lasno ga poznati", "Трудно хорошо видеть, но легко узнать"],
  ["Teško je dugo dobar biti", "Трудно быть хорошим долгое время"],
  ["Teško je čuvati tuđe pare i svoju ženu", "Трудно охранять чужие деньги и свою жену"],
  ["Teško je šutu sa rogatim bosti se", "Трудно стрелять из рогов"],
  ["Teško konju kog slepci teraju", "Горе коню, ведомому слепым"],
  ["Teško nogama pod ludom glavom", "Твердые ноги под сумасшедшей головой"],
  ["Teško onome koji neprijatelja na kućnom pragu čeka", "Горе тому, кто ждет врага на пороге своего"],
  ["Teško onome koji ne zna, a učiti se ne da", "Горе тому, кто не знает и не хочет учиться"],
  ["Teško svetu kad se lude pojunače", "Горе миру, когда восстанут безумцы"],
  ["Teško svuda svome bez svojega", "Горе всем без своего"],
  ["Teško tome ko za tuđom pameti ide", "Горе тем, кто следует за мыслями других людей"],
  ["Tiha voda brijeg roni", "Тихая вода горных погружений"],
  ["Traži hljeba preko pogače", "Он ищет хлеб над буханкой хлеба"],
  ["Triput kroji, jedanput reži", "Разрежь три раза, разрежь один раз"],
  ["Tuđa ruka svrab ne češe", "Чужая рука не чешется"],
  ["Tuđe je sve lijepo, ali je svoje najljepše", "Все остальное прекрасно, но самое прекрасное — свое"],
  ["Tuđe je slađe", "Чужое слаще"],
  ["Tuđina je svuđe ista", "Иностранцы везде одинаковы"],
  ["Tuđoj se budalaštini smejemo, a svoje se ne stidimo", "Мы смеемся над чужой глупостью, но не стыдимся своей"],
  ["Tukle se jetrve preko svekrve", "Они бьют друг друга из-за тещи"],
  ["Tumara ko pijan po pomračini", "Он бродит, как пьяный, в темноте"],
  ["Tup kao ud", "Тупой как конечность"],
  ["Tup ko budak", "Тупой как дурак"],
  ["Tucao mu luk na glavi", "Он ударил луком по голове"],
  ["Ćeraćemo se mi još", "Мы все равно будем смеяться"],
  ["Ćirilica nema ćelava, a latinica imade", "В кириллице нет лысы, а в латинице есть"],
  ["Ćutanje zlata vredi", "Молчание на вес золота"],
  ["Ćutanje je zlato", "Молчание - золото"],
  ["Ćuti avetinjo jedna", "Заткнись, маленькое привидение"],
  ["Ćuti i pokri se ušima", "Заткнись и заткни уши"],
  ["Ćuti kao prase kad piša u vodu (iz Šumadije)", "Заткнись, как свинья, когда писает в воду (из Шумадии)"],
  ["Ćuti, tu si gde(di) si", "Заткнись, ты там, где ты есть"],
  ["Ćorava mu posla!", "У него много работы!"],
  ["Ćuti,da ne urekne zlo!", "Молчи, чтобы не проклинать зло!"],
  ["Ćuti,dobro nije!", "Заткнись, это нехорошо!"],
  ["Ćuti i gledaj svoja posla", "Заткнись и занимайся своими делами"],
  ["Ćuti ko govedo", "Заткнись, как корова"],
  ["Ćuti ko kurva", "Заткнись как шлюха"],
  ["Ćuti ko mula", "Заткнись, как мул"],
  ["Ćuti ko ćutuk", "Молчать"],
  ["Ćuti i plivaj dalje!", "Заткнись и плыви дальше!"],
  ["Ćutanje je zlato a govorenje srebro", "Молчание – золото, а речь – серебро"],
  ["Ćorava mu sreća", "Его удача слепа"],
  ["Ćar poeo vajdu", "Огонь погас"],
  ["U vinu je istina", "В вине есть истина"],
  ["U gladnim očima svaki je komad mali", "В голодных глазах каждый кусочек мал"],
  ["U kog je nož, u tog je pogača", "Где нож, где торт?"],
  ["U kog su ovce, u tog je i planina", "Где есть овцы, там есть и горы"],
  ["U koga je pogača u toga je i nož", "Где торт, там и нож"],
  ["U kolo kad hoćeš, iz kola kad puste", "В машине, когда захочешь, из машины, когда отпустят"],
  ["U nevolji ne treba plakati, nego leka tražiti", "В беде надо не плакать, а искать лекарство"],
  ["U ratara crne ruke, a bijela pogača", "У фермера черные руки и белый хлеб"],
  ["U sreću se uzda lud, a pametan u svoj trud", "Глупец надеется на удачу, а мудрый на свои усилия"],
  ["U stara glava, u mlada snaga", "Старой голове, молодой силе"],
  ["U stara krvnika nema novog prijatelja", "У старого палача нет нового друга"],
  ["U tekućoj vodi mulj ne leži", "Осадок не задерживается в проточной воде"],
  ["U tuđem oku vidi slamku, a u svome grede ne vidi", "В чужом глазу соломинку видит, а в своем бревна не видит"],
  ["U šumu drva nosi", "Он несет дрова в лес"],
  ["Uz malo može biti dosta, a u dosta malo", "Малое может быть много, а многое может быть маленьким"],
  ["Uzeh vraga radi blaga; blago nestade, a vrag ostade", "Я принял дьявола за сокровище; сокровище исчезает, но дьявол остается"],
  ["Um caruje, a snaga klade valja", "Разум царит, и сила ставки действительна"],
  ["Umro ko radi, umro ko ne radi", "Тот, кто работает, умер, тот, кто не работает, умер"],
  ["Utopljenik se za slamku hvata", "Утопающий хватается за соломинку"],
  ["Uzdaj se u se i u svoje kljuse", "Доверяй всему и своим ушам"],
  ["Učenje je svetlost", "Обучение лёгкое"],
  ["Učiniš li zlo, ne misli da će te zlo mimoići", "Если ты делаешь зло, не думай, что зло пройдет мимо тебя"],
  ["Učini dobro, ne kaj se; učini zlo, nadaj se", "Делай добро, не раскаивайся; твори зло, надейся"],
  ["U nevilji se drug poznaje", "Друг известен в деревне"],
  ["Fale mu dva kraja i sredina", "У него нет двух концов и середины"],
  ["Falim te Bože!", "Спасибо, Боже!"],
  ["Fali mu jedna daska u glavi", "В его голове не хватает одной доски"],
  ["Frkće ko pokiso konj", "Он фыркает, как мокрая лошадь"],
  ["Fabrika je košnica sa mnogo trutova", "Фабрика — это улей со множеством дронов"],
  ["Fali mi pet da načinim šest", "Мне нужно пять, чтобы получить шесть"],
  ["Fali mu daska u glavi", "Ему не хватает доски в голове"],
  ["Fudbal vode pametni, a gledaju ludi", "В футбол играют умные люди и смотрят сумасшедшие"],
  ["Fudbal se ne igra za publiku nego za novac", "В футбол играют не ради зрителей, а ради денег"],
  ["Frkće od besa", "Он фыркает от гнева"],
  ["Hajduke narod ceni, ali za njima u goru neće", "Народ ценит Хайдук, но не пойдет за ним в горы"],
  ["Hajdučke kuće nema", "Дома в Хайдуке нет"],
  ["Hartija i ćuprija trpe sve", "Бумага и мост выдерживают все"],
  ["Hvali ga ko Ciganin konja", "Он его хвалит, как цыганского коня"],
  ["Hvali selo, a živi u gradu", "Он хвалит деревню, но живет в городе"],
  ["Hvalte me usta da vas ne pocepam(poderem)", "Мой рот хвалит меня за то, что я не разорвал тебя на части"],
  ["Hvala ti do neba!", "Большое спасибо!"],
  ["Hvala ti ko bratu!", "Спасибо, братан!"],
  ["Hvalim te Bože!", "Славлю Тебя, Боже!"],
  ["Hvali se ko Crnogorac", "Он хвастается тем, что он черногорец"],
  ["Hvaliti na sva usta", "Хвалите изо всех сил"],
  ["Hvata zmije tuđim rukama", "Он ловит змей чужими руками"],
  ["Hvata muvu na sirće", "Ловля ложки дегтя"],
  ["Hvata se u kolo, a ne ume da igra", "Он попадает в круг, но не знает, как играть"],
  ["Hladan ko stena", "Холодный как камень"],
  ["Hladan ko špricer", "Холодный как шприц"],
  ["Hleba i igara, pisaru", "Хлеб и игры, писец"],
  ["Hlebom ga dušmani hranili!", "Его враги кормили его хлебом!"],
  ["Hoće vatru koja ne peče", "Ему нужен огонь, который не горит"],
  ["Heroj nadživi sebe", "Герой переживает самого себя"],
  ["Hleb jesti - nije majstorija; hleb peći - mala je majstorija; a hleb zaraditi - to je najveća majstorija", "Употребление хлеба – это не навык; печь хлеб – это маленькое умение; и зарабатывать на хлеб - вот величайшее мастерство"],
  ["Hoćeš li da te svi mrze, reci svakome ko je ko", "Хочешь, чтобы все тебя ненавидели, расскажи всем, кто есть кто"],
  ["Hranitelj je kao i roditelj", "Приемный опекун похож на родителя"],
  ["Hoće ga svaki đavo", "Каждый дьявол хочет его"],
  ["Hoće hleba preko pogače", "Он хочет хлеб вместо булочки"],
  ["Hoće hleba bez motike", "Он хочет хлеба без мотыги"],
  ["Hrabrima sreća dodaje ruku", "Фортуна протягивает руку помощи смелым"],
  ["Hrabrom i sreća pomaže", "Смелость и удача помогут"],
  ["Hrabre sreća prati!", "Удача сопутствует смелым!"],
  ["Car nad carom uvek se nađe", "Король над королем всегда находится"],
  ["Carska se ne poriče", "Царская не отказывает себе"],
  ["Caru carevo a Bogu Božje navjek i amin", "Царю царей и Богу Божиему во веки веков и аминь"],
  ["Cvet je najlepši dok je neubran", "Цветок самый красивый, когда его не сорван"],
  ["Crnogorci ne ljube lance", "Черногорцы не любят цепи"],
  ["Celom svetu ne možeš ugoditi!", "Невозможно угодить всему миру!"],
  ["Cigani ti kuću kućili!", "Цыгане построили твой дом!"],
  ["Caru carevo,nama naše", "Король, король, наш"],
  ["Crn mu obraz!", "Лицо у него черное!"],
  ["Crno rade a još crnje misle", "Они работают черным и думают еще чернее"],
  ["Celo leto jedna šljiva,i ona crvljiva", "Все лето одна слива, да червячная"],
  ["Car daleko,a Bog visoko", "Царь далеко, а Бог высок"],
  ["Časna smrt proslavi vas život", "Почетная смерть прославит твою жизнь"],
  ["Čaša iza čaše, a iza čaše istina", "Стакан за стаканом, а за стаканом правда"],
  ["Čega se mudar stidi, tim se lud ponosi", "Чего стыдится мудрый, тем гордится дурак"],
  ["Čega je srce puno, toga i jezik", "Чем наполнено сердце, тем и язык"],
  ["Čelo, oči i pogled vrlo često lažu, a govor najčešće", "Лоб, глаза и взгляд очень часто лгут, а речь чаще всего"],
  ["Često malena varnica veliku vatru užeže", "Часто маленькая искра зажигает большой пожар"],
  ["Četiri stvari mogu da unište čoveka: rđava zemlja, zla žena, loš porod i mrtav kapital", "Четыре вещи могут погубить человека: плохая страна, плохая жена, плохое рождение и мертвый капитал"],
  ["Čija sila, toga i pravda", "Чья сила – справедливость"],
  ["Čije june, onoga i uže", "Чей июнь, эта веревка"],
  ["Čini dobro, dobrome se nadaj, čini loše, još gorem se nadaj", "Делайте добро, надейтесь на хорошее, делайте зло, надейтесь на худшее"],
  ["Čini dobro, raduj se, čini loše, nadaj se", "Делай добро, радуйся, делай зло, надейся"],
  ["Čini drugom što je tebi drago da ti se učini", "Делай другим то, что ты хотел бы, чтобы делали тебе"],
  ["Čist račun, duga ljubav", "Чистый счет, долгая любовь"],
  ["Čisti računi - dobri prijatelji", "Чистые счета – хорошие друзья"],
  ["Čistoća je pola zdravlja", "Чистота – половина здоровья"],
  ["Čovek bez slobode, k’o riba bez vode", "Человек без свободы подобен рыбе без воды"],
  ["Čovek želi da je od svakoga bolji, a od sina da je gori", "Человек хочет быть лучше всех и хуже своего сына"],
  ["Čovek ima samo ono što daje", "Человек имеет только то, что он дает"],
  ["Čovek je tvrđi od kamena, a slabiji od jajeta", "Человек тверже камня и слабее яйца"],
  ["Čovek se do smrti uči", "Человек учится до смерти"],
  ["Čovek se nada dok god je duše u njemu", "Человек надеется, пока в нем душа его"],
  ["Čovek se pozna u tri slučaja: u jelu, u bogatstvu i u pijanstvu", "Человек познаётся в трёх случаях: в еде, в богатстве и в пьянстве"],
  ["Čovek se prima prema odelu koje nosi a ispraća prema duhu", "Человека принимают согласно одежде, которую он носит, и отсылают согласно его духу"],
  ["Čovek se uči dok je živ, pa opet lud umre", "Человек учится, пока живет, а потом умирает дураком"],
  ["Čovjek sve dava za obraz, a obraz ni za šta", "Человек отдает все ради своего лица, а свое лицо даром"],
  ["Čuvaj bele novce za crne dane", "Сохраните белые деньги на черный день"],
  ["Čuvaj se mnogih ako se ne bojiš pojedinaca", "Остерегайтесь многих, если не боитесь отдельных личностей"],
  ["Čuvaj se onih koji kroz smeh ujedaju", "Остерегайтесь тех, кто умеет смеяться"],
  ["Čuvaj se onoga ko stavlja obraz pod opanak", "Остерегайся того, кто сует щеку под ковер"],
  ["Čuvaj se tihe vode i psa koji ćuti", "Остерегайтесь стоячей воды и молчаливой собаки"],
  ["Čuturom se pregrabi i najveće bure", "Даже самые большие бочки захватываются воронкой"],
  ["Džaba ti svila i kadifa", "Не нужен шелк и бархат"],
  ["Džabe je i sirće slatko", "Уксус тоже сладкий просто так"],
  ["Džabe mu je, da dubi na glavi", "Ему бесполезно копаться в голове"],
  ["Džin na staklenim nogama", "Великан на стеклянных ногах"],
  ["Džak soli treba pojesti sa čovekom, da bi ga dobro upoznao", "С человеком следует съесть джак соли, чтобы лучше его узнать"],
  ["Džaba ga bilo!", "Это было зря!"],
  ["Džaba ti supa kad je slana", "Суп бесполезен, когда он соленый"],
  ["Džaba im", "Им это бесполезно"],
  ["Š", "Ш"],
  ["Šeta se po oštrici noža", "Он идет по лезвию ножа"],
  ["Šilo za ognjilo", "Огненное шило"],
  ["Šolju mleka pa u krevet", "Чашка молока и спать"],
  ["Šta vredi znanje bez radnje", "Чего стоят знания без действий"],
  ["Šta zna dete šta je petsto kila - uze i odnese", "Да что ребенок знает, что такое пятьсот килограммов – возьми и унеси"],
  ["Šta ko misli, o onom i sanja", "О чем он думает, о чем он мечтает"],
  ["Šta ko čini sve sebi čini", "Тот, кто делает все, делает для себя"],
  ["Šta me gledaš, ko da igra bela mečka", "Почему ты смотришь на меня, который должен играть белого медведя?"],
  ["Šta osveta čini", "Что делает месть"],
  ["Što se hoće to se može", "Все, что хочется, возможно"],
  ["Što više sile, više i zla", "Чем больше силы, тем больше зла"],
  ["Što više ljubavi vraćaš, više ćeš i primiti", "Чем больше любви вы отдадите в ответ, тем больше вы получите"],
  ["Što danas ne potrošiš, to si stekao", "То, что вы не потратили сегодня, вы заработали"],
  ["Što ih manje titraš to te više spopadaju", "Чем меньше вы их вибрируете, тем сильнее они вас бьют"],
  ["Što ih pasa laje, da svaki ujede, zlo", "Что на них собака лает, чтобы каждая кусала, злая"],
  ["Što je babi milo to joj se i snilo", "К радости бабушки, ей это приснилось"],
  ["Što je brzo to je kuso", "Чем быстрее, тем короче"],
  ["Što je veća ptica, veće joj gnezdo treba", "Чем крупнее птица, тем большее гнездо ей нужно"],
  ["Što je više brdo, to je dublja dolja", "Чем выше холм, тем глубже долина"],
  ["Što je život skuplji - karakter je jeftiniji", "Чем дороже жизнь, тем дешевле персонаж"],
  ["Što je svačije, to je ničije", "То, что принадлежит всем, не принадлежит никому"],
  ["Što jedan lud zamrsi, sto mudrijeh ne mogu razmrsiti", "Что дурак напутал, мудрый не распутает"],
  ["Što ljudi imaju više, to više žele", "Чем больше у людей есть, тем больше они хотят"],
  ["Što ne znaš pitaj onoga ko zna", "Чего не знаешь, спроси у того, кто знает"],
  ["Što ne umeš popraviti, nemoj ni menjati", "То, что вы не можете исправить, не меняйте"],
  ["Što ne ide od srca, ne ide ni k srcu", "Что не исходит от сердца, то не приходит к сердцу"],
  ["Što nećeš nekome u oči da kažeš, nemoj govoriti ni za leđima", "Чего бы вы не сказали кому-то в лицо, не говорите и за спиной"],
  ["Što si rad da sam znaš, ne govori nikom", "Ты должен знать, что делаешь, никому не говори"],
  ["Što smije pop, ne smije đak", "То, что может поп, не может студент"],
  ["Što srce ne zapazi to ni oči ne vide", "Чего не замечает сердце, того не видят глаза"],
  ["Što ti je život - tražiš od pravde ruku, dobiješ nogu", "Что твоя жизнь - просишь у справедливости руки, получаешь ногу"],
  ["Što ti je suđeno doći će ti i preko plota", "То, что тебе суждено, придет к тебе через забор"],
  ["Što ti meni popuješ", "Что ты делаешь со мной?"],
  ["Što trijezan misli, (to) pijan govori", "Что думает трезвый человек, то и говорит пьяный"],
  ["Što u kući treba, crkvi se ne daje", "То, что нужно в доме, в церковь не отдается"],
  ["Što čovek više živi, više i zna", "Чем больше человек живет, тем больше он знает"],
  ["Što čovek manje zna to mu se njegovo znanje čini obimnije", "Чем меньше человек знает, тем более обширными кажутся ему его знания"],
  ["Šuga i ljubav se ne mogu sakriti", "Чесотку и любовь не скрыть"],
  ["Šugava ovca sve stado ošuga", "Паршивая овца царапает все стадо"],
  ["Šuplju glavu i vetar nosi", "Они долбят головы, и ветер уносит их"]
];
