/* Movies */
let movies = [
	["A caelo usque ad centrum","Od neba do središta (Zemlje)"],
	["A capillo usque ad ungues","Od kose do noktiju (od glave do pete)"],
	["A capite ad calcem","Od glave do pete"],
	["A casu ad casum","Od slučaja do slučaja"],
	["A contrario","Nasprotiv / sa suprotne strane"],
	["A dato","Od dana izdavanja (od ovog datuma)"],
	["A die","Od ovog dneva (od današnjeg dana)"],
	["A fortiori","Ukoliko pre / sa jačim razlogom"],
	["A limine","Sa praga (odmah, sa samog početka)"],
	["A majore ad minus","Od većeg ka manjem"],
	["A mari usque ad mare","Od mora do mora"],
	["A maximis ad minima","Od najvećeg ka najmanjem"],
	["A mensa et toro","Od stola i postelje (rastava braka)"],
	["A nativitate","Od rođenja"],
	["A nescire ad non esse","Od neznanja ka nepostojanju"],
	["A novo","Iznova / od početka"],
	["A parte","Sa strane / odvojeno"],
	["A pedibus usque ad caput","Od peta do glave"],
	["A posse ad esse","Od mogućeg ka stvarnom"],
	["A posse ad esse non valet consequential","Od mogućeg ka stvarnom ne važi zaključak"],
	["A posteriori","Na osnovu iskustva (naknadno)"],
	["A potentia ad actum","Od mogućnosti ka ostvarenju"],
	["A potiori","Po jačem (razlogu) / na osnovu pretežnog"],
	["A potiori fit denominatio","Naziv se daje po pretežnom deo/svojstvu"],
	["A prima facie","Na prvi pogled"],
	["A priori","Unapred (nezavisno od iskustva)"],
	["A probis probari, ab improbis improbari aequa laus est","Biti hvaljen od dobrih i kuđen od loših jednaka je pohvala"],
	["A realibus ad realiora","Od stvarnog ka stvarnijem"],
	["A sacris","Odvojen od svetih stvari"],
	["A tuo lare incipe","Počni od svog ognjišta"],
	["Ab absurdo","Iz apsurda (dokazivanje suprotnim)"],
	["Ab aeterno","Od večnosti"],
	["Ab antiquo","Od davnina"],
	["Ab equis ad asinos","Sa konja na magarca"],
	["Ab esse ad posse valet consequentia","Zaključivanje sa stvarnog na moguće važi"],
	["Ab exterioribus ad interiora","Spolja ka unutra"],
	["Ab extra","Spolja / sa strane"],
	["Ab hinc","Odavde / od ovog trenutka"],
	["Ab hoc et ab hac","O ovome i onome (bez reda i smisla)"],
	["Ab hodierno","Od današnjeg dana"],
	["Ab hoedis scindere oves","Odvojiti ovce od jaraca"],
	["Ab igne ignem","Vatrom na vatru"],
	["Ab imis unguibus ad verticem summum","Od vrhova noktiju do samog temena"],
	["Ab imo pectore","Iz dubine duše (iz dna grudi)"],
	["Ab inconvenienti","Zbog neprijatnosti / iz razloga neuputnosti"],
	["Ab incunabulis","Od kolevke"],
	["Ab initio","Od početka"],
	["Ab initio nullum, semper nullum","Što je od početka ništavo, uvek je ništavo"],
	["Ab intestato","Bez testamenta"],
	["Ab irato","U gnjevu / u ljutnji"],
	["Ab Jove principium","Početak je od Jupitera (početi od najvažnijeg)"],
	["Ab origine","Od porekla / iz početka"],
	["Ab ovo","Od jajeta (od samog početka)"],
	["Ab ovo usque ad mala","Od jajeta do jabuka (od početka do kraja)"],
	["Ab posse ad esse consequentia (illatio) non valet","Prelaz sa mogućeg na stvarno nije valjan"],
	["Ab uno disce omnes","Po jednom upoznaj sve"],
	["Ab Urbe condita","Od osnivanja Grada (Rima)"],
	["Abeunt studia in mores","Interesovanja prelaze u navike"],
	["Abiens, abi!","Odlazeći, idi!"],
	["Absente aegroto","U odsustvu bolesnika"],
	["Absit omen!","Neka je daleko loš znak! (Ne bilo uroka)"],
	["Absit verbo invidia","Neka reč ne izazove zavist (bez uvrede)"],
	["Absolutio ab instantia","Oslobađanje optužbe usled nedostatka dokaza"],
	["Absolvo te!","Opraštam ti!"],
	["Absque nota","Bez oznake"],
	["Absque omni exceptionae","Bez ikakvog izuzetka"],
	["Abstractum pro concreto","Apstraktno umesto konkretnog"],
	["Absurdum in adjecto","Apsurd u pripisivanju (protivrečnost u samom pojmu)"],
	["Abusus non tollit usum","Zloupotreba ne ukida pravo na upotrebu"],
	["Abyssus abyssum invocat","Ponor priziva ponor"],
	["Accessio cedit principali","Sporedna stvar prati glavnu"],
	["Acta diurna","Dnevni događaji / novine"],
	["Acta est fabula!","Predstava je završena!"],
	["Actio immanens","Unutrašnja (imanentna) radnja"],
	["Actio in distans","Delovanje na daljinu"],
	["Actio in factum","Tužba zasnovana na činjenicama"],
	["Actio popularis","Narodna tužba"],
	["Actio transiens","Prelazna radnja"],
	["Actore non probante reus absolvitur","Ako tužilac ne dokaže, optuženi se oslobađa"],
	["Actor sequitur forum rei","Tužilac sledi sud tuženog"],
	["Actum atque tractatum","Urađeno i raspravljeno"],
	["Actum est ilicet!","Sve je završeno!"],
	["Actum ut supra","Urađeno kao što je gore navedeno"],
	["Actus purus","Čisti čin / čista delatnost"],
	["Ad absurdum","Do apsurda"],
	["Ad acta","U spise / među arhivirane predmete"],
	["Ad aeternum","Za večnost"],
	["Ad aras","Do žrtvenika (do krajnjih granica)"],
	["Ad arbitrium","Po volji / po nahođenju"],
	["Ad augusta per angusta","Kroz trnje do zvezda (do uzvišenog kroz prepreke)"],
	["Ad bestias!","Pred zveri!"],
	["Ad Calendas Graecas","O grčkim kalendama (nikada)"],
	["Ad captandum benevolentiam","Da bi se pridobila naklonost"],
	["Ad captandum vulgus","Da bi se pridobila svetina"],
	["Ad cogitandum et agendum homo natus est","Čovek je rođen da bi razmišljao i delao"],
	["Ad delectandum","Za uživanje / radi zabave"],
	["Ad discendum, non ad docendum","Radi učenja, a ne radi podučavanja"],
	["Ad disputandum","Za raspravu"],
	["Ad ea debeat adaptari jus, quae frequenter eveniunt","Pravo treba prilagođavati onome što se često događa"],
	["Ad exemplum","Na primer / po uzoru"],
	["Ad extra","Ka spolja"],
	["Ad extremitates","Do krajnosti"],
	["Ad finem","Do kraja"],
	["Ad fontes","Na izvore"],
	["Ad futuram memoriam","Za buduće sećanje"],
	["Ad futuram rei memoriam","Za trajno sećanje na događaj"],
	["Ad gloriam","Za slavu"],
	["Ad gustum","Po ukusu"],
	["Ad hastam","Na javnoj prodaji (pod kopljem)"],
	["Ad Herculis columnas","Do Herkulovih stubova"],
	["Ad hoc","Za ovu priliku / posebne namene"],
	["Ad hominem","Prema čoveku (argument usmeren na ličnost)"],
	["Ad honores","Radi časti (počasno)"],
	["Ad hoste maligno libera nos, Domine","Od zlog neprijatelja izbavi nas, Gospode"],
	["Ad impossibilia nemo tenetur","Niko nije obavezan na nemoguće"],
	["Ad infinitum","Do beskonačnosti"],
	["Ad informandum","Radi informisanja"],
	["Ad instar","Po ugledu na / nalik"],
	["Ad instruendum","Radi pripreme predmeta"],
	["Ad interim","Privremeno / za međuvreme"],
	["Ad latus","Uz boku / pored"],
	["Ad libita librarii","Po volji prepisivača"],
	["Ad libitum","Po volji / po želji"],
	["Ad limina (apostolorum)","Do pragova (apostolskih)"],
	["Ad litem","Za potrebe spora"],
	["Ad litteram","Doslovno"],
	["Ad loca!","Na mesta!"],
	["Ad majorem Dei gloriam","Na veću slavu Božiju"],
	["Ad manum","Pri ruci"],
	["Ad maximum","Do maksimuma"],
	["Ad meliora tempora","Za bolja vremena"],
	["Ad meliorem","Ka boljem"],
	["Ad memorandum","Za sećanje / podsetnik"],
	["Ad minimum","Do minimuma"],
	["Ad modum","Po načinu / po uzoru"],
	["Ad multos annos!","Na mnogaje ljeta! / U zdravlje!"],
	["Ad narrandum, non ad probandum","Radi kazivanja, a ne radi dokazivanja"],
	["Ad nauseam","Do mučnine (do dosade)"],
	["Ad normam","Po pravilu / po normi"],
	["Ad notam","Za zabelešku / na znanje"],
	["Ad notanda","Što treba zabeležiti"],
	["Ad notata","Uz zabeleške"],
	["Ad oculos","Očigledno / pred očima"],
	["Ad opus!","Na posao!"],
	["Ad patres","Ka ocima (umreti)"],
	["Ad patres conscriptos","Očevima senatogilima"],
	["Ad perpetuam rei memoriam","Za večno sećanje na događaj"],
	["Ad personam","Na ličnost"],
	["Ad pias causas","U dobrotvorne namene"],
	["Ad pluralitatem votorum","Većinom glasova"],
	["Ad populum","Narodu / publici"],
	["Ad profundum","Do dna"],
	["Ad publicandum","Za objavljivanje"],
	["Ad ratificandum","Za potvrdu / za ratifikaciju"],
	["Ad referendum","Za izveštaj / na odobrenje"],
	["Ad rem","Ka stvari / na temu"],
	["Ad se ipsum","Samome sebi"],
	["Ad totalem evaporationem","Do potpunog isparavanja"],
	["Ad tertium","Kao treće"],
	["Ad unguem","Besprenkorno / savršeno (do nokta)"],
	["Ad unum omnes","Svi do jednoga"],
	["Ad usum delphini","Za upotrebu delfina (začinjeno/skraćeno izdanje)"],
	["Ad usum externum","Za spoljnu upotrebu"],
	["Ad usum internum","Za unutrašnju upotrebu"],
	["Ad usum populi","Za narodnu upotrebu"],
	["Ad usum proprium","Za sopstvenu upotrebu"],
	["Ad usum vitae","Za životnu potrebu"],
	["Ad valorem","Prema vrednosti"],
	["Ad verbum","Od reči do reči"],
	["Ad verbum audiendum","Radi usmenog saslušanja"],
	["Ad victoriam","Ka pobedi"],
	["Ad vitam","Za život"],
	["Ad vitam aeternam","Za večni život"],
	["Ad vitam aut culpam","Do kraja života ili do prve krivice"],
	["Ad vocem","Na reč / u pogledu reči"],
	["Adhuc sub judice lis est","Spor je još pred sudijom"],
	["Adverbium","Prilog"],
	["Advitalitum","Doživotno"],
	["Advocatus Dei","Božiji advokat"],
	["Advocatus Diaboli","Đavolji advokat"],
	["Aequam memento rebus in arduis servare mentem","Zapamti da u teškim trenucima sačuvaš smirenost"],
	["Aequat causa effectum","Uzrok je jednak posledici"],
	["Aequilibrium indifferentiae","Ravnoteža ravnodušnosti"],
	["Aequo animo","Ravnodušno / mirne duše"],
	["Aequo pulsat pede","Smrt kuca jednakim korakom"],
	["Aequum est neminem cum alterius detrimento et injuria fieri locupletiorem","Pravedno je da se niko ne obogati na štetu i nepravdu drugoga"],
	["Aere perennius","Trajnije od mesinga"],
	["Aes triplex","Trostruki oklop (trostruka zaštita)"],
	["Aeterna historia","Večna istorija"],
	["Aeterna urbs","Večni grad (Rim)"],
	["Aeternae veritates","Večne istine"],
	["Aeternum vale","Večni pozdrav / zbogom zauvek"],
	["Age, libertate decembri utere","Hajde, iskoristi decembarsku slobodu"],
	["Age, quod agis, et respice finem","Radi to što radiš i misli na kraj"],
	["Agere sequitur esse","Delovanje sledi postojanje"],
	["Ager publicus","Javno zemljište"],
	["Agnosco veteris vestigia flammae","Prepoznajem tragove starog plamena"],
	["Agnus Dei","Jagnje Božije"],
	["Ajo!","Tvrdim! / Da!"],
	["Albo lapillo notare diem","Obeležiti dan belim kamenom (srećan dan)"],
	["Alea iacta (jacta) est","Kocka je bačena"],
	["Alia editio","Drugo izdanje"],
	["Alia tempora","Druga vremena"],
	["Alibi","Na drugom mestu (alibi)"],
	["Aliena vitia in oculis habemus, a tergo nostra sunt","Tuđe mane su nam pred očima, a naše iza leđa"],
	["Alienatio mentis","Pomračenje uma"],
	["Alieni juris","Pod tuđim pravom (zavisan)"],
	["Aliis inserviendo consumor","Služeći drugima sagorevam"],
	["Aliquando bonus dormitat Homerus","Ponekad i dobri Homer zadrema"],
	["Aliud stans, aliud sedens","Jedno priča stojeći, drugo sedeći"],
	["Alius alio plura invenire potest, nemo omnia","Neko može naći više od drugog, niko sve"],
	["Alma Mater","Majka hraniteljka (univerzitet)"],
	["Alter ego","Drugo ja"],
	["Alter idem","Drugi isti"],
	["Altera pars","Druga strana"],
	["Altum silentium","Duboka tišina"],
	["Amabile opus","Ljupko delo"],
	["Amabilis insania","Prijatno ludilo"],
	["Amabilis scientia","Prijatna nauka (botanika)"],
	["Amant alterna Camenae","Muze vole naizmenične pesme"],
	["Amantes non vident. Videntes non amant.","Zaljubljeni ne vide. Oni koji vide ne vole."],
	["Amantes sunt amentes","Zaljubljeni su bezuma"],
	["Amantium irae","Svađe zaljubljenih"],
	["Amantium irae amoris integratio","Svađe zaljubljenih su obnova ljubavi"],
	["Amat victoria curam","Pobeda voli pripremu"],
	["Amata nobis quantum amabitur nulla","Voljena od nas kao nijedna druga"],
	["Amen!","Amin! / Neka tako bude!"],
	["Amicalia desideria","Prijateljske želje"],
	["Amici, diem perdidi","Prijatelji, izgubio sam dan"],
	["Amicus certus in re incerta cernitur","Pravi prijatelj se poznaje u nevolji"],
	["Amicus cognoscitur amore, more, ore, re","Prijatelj se poznaje po ljubavi, ponašanju, rečima i delima"],
	["Amicus (Animal) humani generis","Prijatelj (životinja) ljudskog roda"],
	["Amicus incommodus ab inimico non differt","Nezgodan prijatelj se ne razlikuje od neprijatelja"],
	["Amicus meus","Moj prijatelj"],
	["Amicus Plato, sed magis amica est veritas","Drag mi je Platon, ali mi je draža istina"],
	["Amicus verus rara avis","Pravi prijatelj je retka ptica"],
	["Amor caecus","Ljubav je slepa"],
	["Amor fati","Ljubav prema sudbini"],
	["Amor patriae","Ljubav prema domovini"],
	["Amor vincit omnia","Ljubav sve pobeđuje"],
	["Amor non est medicabilis herbis","Ljubav se ne leči travama"],
	["An nescis longas regibus esse manus?","Zar ne znaš da kraljevi imaju duge ruke?"],
	["An nescis, mi fili, quantilla prudentia mundus regatur?","Zar ne znaš, sine moj, sa kako malo mudrosti se vlada svetom?"],
	["Analogia entis","Analogija bića"],
	["Anathema maranata","Neka bude proklet"],
	["Ancilla philosophiae","Služavka filozofije"],
	["Ancilla theologiae","Služavka teologije"],
	["Anguis in herba","Zmija u travi"],
	["Angulus ridet","Ovaj kutak mi se osmehuje"],
	["Anima","Duša / duh"],
	["Anima vilis","Bezvredna duša / bezvredan subjekat"],
	["Animalia vivunt, crescunt et sentiunt","Životinje žive, rastu i osećaju"],
	["Animam in promptu habere","Nositi dušu u nosu"],
	["Animi magnitudo","Veličina duha"],
	["Animus","Duh / namera"],
	["Animus denuntiandi","Namera da se prijavi"],
	["Animus injuriandi","Namera da se nanese uvreda"],
	["Animus meminisse horret","Duša drhti od samog sećanja"],
	["Animus possidendi","Namera posedovanja"],
	["Animus quod perdidit optat, Atque in praeterita se totus imagine versat","Duša čezne za onim što je izgubila i sva se predaje slikama prošlosti"],
	["Animus rem sibi habendi","Namera da se stvar zadrži za sebe"],
	["Animus suspicax","Sumnjičav duh"],
	["Anni currentis","Tekuće godine"],
	["Anno","Godine"],
	["Anno ab urbe condita","Od osnivanja Rima"],
	["Anno aetatis suae","U svojoj godini života"],
	["Anno ante Christum Natum","Godine pre Hristovog rođenja"],
	["Anno Christi","Godine Hristove"],
	["Anno Domini","Godine Gospodnje"],
	["Anno mundi","Godine od stvaranja sveta"],
	["Anno post Romam conditam","Godine posle osnivanja Rima"],
	["Annus horribilis","Užasna godina"],
	["Ante bellum","Pre rata"],
	["Ante Christum Natum","Pre Hristovog rođenja"],
	["Ante diem","Pre određenog dana"],
	["Ante factum","Pre učinjenog dela"],
	["Ante mare undae","Talas postoji i pre mora"],
	["Ante meridiem","Pre podne"],
	["Ante nuptias donatio","Poklon pre braka"],
	["Ante quem","Pre kojeg"],
	["Anterioritas","Prvenstvo / prednost"],
	["Ante scriptum","Pre napisanog"],
	["Apparatus criticus","Kritički aparat"],
	["Appellatio","Žalba / apelacija"],
	["Appendix","Dodatak"],
	["Appetitus societatis","Težnja ka društvu"],
	["Aqua bulliens","Kipuća voda"],
	["Aqua destillata","Destilovana voda"],
	["Aqua et igni alicui interdicere","Zabraniti nekome vodu i vatru (prognati)"],
	["Aqua et ignis","Voda i vatra"],
	["Aqua et panis, vita canis","Voda i hleb, pseći život"],
	["Aqua fontana","Izvorska voda"],
	["Aqua [cavat] lapidem non vi, sed saepe cadendo","Voda dubi kamen ne snagom, već čestim padanjem"],
	["Aqua pluvialis","Kišnica"],
	["Aqua pura","Čista voda"],
	["Aqua tophana","Tofana voda (otrov)"],
	["Aqua vitae","Voda života (rakija)"],
	["Aquae et ignis interdictio, hoc est exillum","Zabrana vode i vatre, to jest izgnanstvo"],
	["Aquae potoribus","Oni koji piju vodu"],
	["Aquila non captat muscas","Orao ne lovi muve"],
	["Arbiter elegantiae","Sudija ukusa"],
	["Arboretum","Botančka bašta drveća"],
	["Arcades ambo","Obojica su Arkadijci (jednaki su)"],
	["Argenteis hastis pugnare","Boriti se srebrnim kopljima (popećivati novcem)"],
	["Argentum nitricum","Srebro-nitrat (pakleni kamen)"],
	["Argumenta ambigua","Dvosmisleni dokazi"],
	["Argumenta ponderantur, non numerantur","Dokazi se mere, a ne broje"],
	["Argumentum a contrario","Dokaz sa suprotne strane"],
	["Argumentum a posteriori","Dokaz na osnovu iskustva"],
	["Argumentum a priori","Dokaz nezavisan od iskustva"],
	["Argumentum a silentio","Dokaz iz ćutanja"],
	["Argumentum a tuto","Dokaz sa sigurne strane"],
	["Argumentum ab impossibili","Dokaz iz nemogućnosti"],
	["Argumentum achilleum","Ahilov dokaz (glavni dokaz)"],
	["Argumentum ad crumenam","Dokaz usmeren na novčanik"],
	["Argumentum ad hominem","Dokaz usmeren na čoveka"],
	["Argumentum ad ignorantiam","Dokaz zasnovan na neznanju"],
	["Argumentum ad invidia","Dokaz proizašao iz zavisti"],
	["Argumentum ad judicum","Dokaz usmeren na rasuđivanje"],
	["Argumentum ad misericordiam","Dokaz usmeren na sažaljenje"],
	["Argumentum ad populum","Dokaz usmeren na svetinu/narod"],
	["Argumentum ad rem","Dokaz usmeren na samu stvar"],
	["Argumentum ad verecundiam","Dokaz usmeren na stid/poštovanje autoriteta"],
	["Argumentum ad veritatem","Dokaz usmeren na istinu"],
	["Argumentum ambiguum (communis)","Dvosmislen (zajednički) argument"],
	["Argumentum baculinum","Dokaz batinom"],
	["Argumentum ex consensu gentum","Dokaz zasnovan na opštem pristanku narodâ"],
	["Argumentum ex silentio","Dokaz iz ćutanja"],
	["Argumentum externum","Spoljni dokaz"],
	["Argumentum internum","Unutrašnji dokaz"],
	["Argumentum legis","Dokaz na osnovu zakona"],
	["Argumentum primarium (palmarium)","Glavni (pobednički) argument"],
	["Arma virumque cano","O oružju i junaku pevam"],
	["Arrectis auribus","Naćuljenih ušiju"],
	["Ars adeo latet arte sua","Umetnost se krije sopstvenom umetnošću"],
	["Ars amandi","Umetnost ljubavi"],
	["Ars est celare artem","Umetnost je sakriti umetnost"],
	["Ars et norma interpretandi naturam","Umetnost i pravilo tumačenja prirode"],
	["Ars gubernandi","Umetnost vladanja"],
	["Ars moriendi","Umetnost umiranja"],
	["Ars logica","Logička umetnost"],
	["Ars longa, vita brevis","Umetnost je duga, život kratak"],
	["Ars oratoria","Govornička umetnost"],
	["Ars poetica","Pesnička umetnost"],
	["Ars sacra","Sveto slikarstvo / sveta umetnost"],
	["Ars una, species mille","Umetnost je jedna, oblika je hiljadu"],
	["Ars vitae","Umetnost življenja"],
	["Artes ingenuae (liberales)","Slobodne veštine"],
	["Artes molliunt mores","Umetnosti ublažavaju običaje"],
	["Articulo mortis","U trenutku smrti"],
	["Articulus","Član / tačka"],
	["Articulus secretissimus","Najstroža tajna član"],
	["Artificiosa natura","Veštačka priroda"],
	["Artium magister","Magistar umetnosti"],
	["Asa foetida","Smrdljiva smola"],
	["Asini exiguo pabulo vivunt","Magarci žive od malo hrane"],
	["Asinos non curo","Ne marim za magarca"],
	["Asinus asinorum in saecula saeculorum","Magarac nad magarcima u vekove vekova"],
	["Asinus asinum fricat","Magarac magarca češe"],
	["Asinus Buridani inter duo prata","Buridanov magarac između dva plastena"],
	["Associatio idearum","Asocijacija ideja"],
	["Astra inclinant, non necessitant","Zvezde nagoveštavaju, ali ne primoravaju"],
	["Asylum ignorantiae","Utočište neznanja"],
	["Atrium mortis","Predvorje smrti"],
	["Atrophia nervorum","Atrofija živaca"],
	["Auctoritas foris","Spoljni autoritet"],
	["Auctoritas rei judicatae","Autoritet presuđene stvari"],
	["Audacter calumniare, semper aliquid haeret","Klevetajte odvažno, uvek nešto ostane"],
	["Audentes fortuna juvat","Sreća pomaže odvažnima"],
	["Audiatur et altera pars","Neka se čuje i druga strana"],
	["Auguror nec me fallit augurium, historias tuas immortales futuras","Predviđam i ne vara me proročanstvo da će tvoje priče biti besmrtne"],
	["Aura popularis","Naklonost naroda"],
	["Aurea mediocritas","Zlatna sredina"],
	["Aures habent, et non audient","Uši imaju, a ne čuju"],
	["Auri sacra fames","Prokleta glad za zlatom"],
	["Auribus teneo lupum","Držim vuka za uši"],
	["Aurora borealis","Polarna svetlost"],
	["Aurora musis amica est","Zora je prijateljica muza"],
	["Аurum nostrum non est aurum vulgi","Naše zlato nije zlato svetine"],
	["Aurum potestas est","Zlato je moć"],
	["Auspicia sunt fausta","Znamenja su povoljna"],
	["Auspicium melioris aevi","Nadam se boljem dobu"],
	["Aut bene, aut nihil","Ili dobro, ili ništa"],
	["Aut bibat, aut abeat","Neka pije ili neka ide"],
	["Aut Caesar, aut nihil","Ili Cezar, ili ništa"],
	["Aut cum scuto, aut in scuto","Ili sa štitom, ili na štitu"],
	["Aut deus, aut natura","Ili Bog, ili priroda"],
	["Aut non tentaris, aut perfice","Ili ne pokušavaj, ili dovedi do kraja"],
	["Aut disce, aut discede","Ili uči, ili odlazi"],
	["Aut prodesse volunt aut delactare poetae","Pesnici žele ili da koriste ili da zabave"],
	["Aut vincere, aut mori","Ili pobediti, ili umreti"],
	["Ave","Zdravo"],
	["Ave, Caesar, morituri te salutant","Zdravo, Cezare, pozdravljaju te oni koji će umreti"],
	["Ave Maria","Zdravo Marijo"],
	["Ave ac vale","Zdravo i zbogom"],
	["Ave verum corpus","Zdravo pravo telo"],
	["Avibus bonis","Pod dobrim znamenjem"],
	["Bacchum Nymphis temperare","Mešati vino sa vodom"],
	["Barba crescit caput nescit","Brada raste, glava ne zna"],
	["Barba non facit philosophum","Brada ne čini filozofa"],
	["Barbam video, sed philosophum non video","Bradu vidim, ali filozofa ne vidim"],
	["Barbarus hic ego sum, quia non intelligor ulli","Ovde sam ja varvarin jer me niko ne razume"],
	["Beata stultitia","Blaženo neznanje"],
	["Beatae plane aures, quae non vocem foris sonantem, sed intus auscultant veritatem docentem","Blažene su uši koje ne slušaju glas spolja, već unutrašnju istinu"],
	["Beati pauperes spiritu","Blaženi siromašni duhom"],
	["Beati possidentes","Blaženi posednici"],
	["Beatudio non est virtutis praemium, sed ipsa virtus","Blaženstvo nije nagrada za vrlinu, već sama vrlina"],
	["Beatus ille, qui procul negotiis","Blažen je onaj koji je daleko od briga"],
	["Bella matribus detestata","Ratovi koje majke mrze"],
	["Bellum internecivum","Rat do uništenja"],
	["Bellum omnium contra omnes","Rat svih protiv svih"],
	["Bene diagnoscitur, bene curatur","Dobro se dijagnostikuje, dobro se leči"],
	["Bene misceatur","Neka se dobro pomeša"],
	["Bene placito","Po dobroj volji"],
	["Bene qui latuit, bene vixit","Ko je dobro skriveno živeo, dobro je živeo"],
	["Bene tritum","Dobro isitnjeno"],
	["Bene valete","Budite dobro / zbogom"],
	["Benevole lector","Dobronamerni čitaoče"],
	["Benevolentiae captandae causa","Radi pridobijanja naklonosti"],
	["Bestiolae, quae unum tantum diem vivunt","Buba koja živi samo jedan dan"],
	["Biblia pauperum","Biblija siromašnih"],
	["Bibliothecae scriptorum","Biblioteka pisaca"],
	["Bis dat qui cito dat","Ko brzo daje, dvostruko daje"],
	["Bis repetitia placent","Ono što se ponovi, sviđa se"],
	["Bis vincit qui se vincit in victoria","Dvostruko pobeđuje onaj ko sebe savlada u pobedi"],
	["Bona adventica","Imovina stečena sa strane"],
	["Bona dicta","Dobre reči"],
	["Bona fama divitiis est potior","Dobar glas je bolji od bogatstva"],
	["Bona fide","U dobroj veri / savesno"],
	["Bona fides","Dobra vera / savesnost"],
	["Bona hereditaria","Nasleđena imovina"],
	["Bona mente","U dobroj nameri"],
	["Bona opinio homini tuttior pecunia est","Dobar glas čoveku je sigurniji od novca"],
	["Bona venia vestra","Uz vaše dobro dopuštenje"],
	["Bonae fidei possesio","Savesna državina"],
	["Boni homines","Dobri ljudi"],
	["Bonis auspiciis","Pod dobrim znamenjem"],
	["Bono modo","Na dobar način"],
	["Bono sensu","U dobrom smislu"],
	["Bonum publicum","Opšte dobro"],
	["Bonum vinum laetificat cor hominum","Dobro vino veseli srce čoveka"],
	["Bonus eventus","Dobar ishod"],
	["Bonus ordo","Dobar red"],
	["Bonus pater familias","Dobar domaćin (pater familijas)"],
	["Bonus vir semper tiro est","Dobar čovek je uvek početnik"],
	["Breves vibrantesque sententiae","Kratke i prodiruće misli"],
	["Brevi manu","Kratkim postupkom / iz ruke u ruku"],
	["Brevis esse laboro, obscurus fio","Trudim se da budem kratak, a postajem nejasan"],
	["Bruta fulmina","Prazne pretnje (bezzube munje)"],
	["Cacatum non est pictum","Iskaljano nije naslikano"],
	["Cadit quaestio","Pitanje otpada"],
	["Cadmea victoria","Kadmejska pobeda (pobeda sa velikim gubicima)"],
	["Caedite eos. Novit enim Dominus qui sunt eius","Ubijajte ih sve, Gospod zna koji su njegovi"],
	["Caelo tonantem credidimus Jovem Regnare","Verovali smo da Jupitera vlada dok grmi na nebu"],
	["Caelum, non animum mutant, qui trans mare currunt","Nebo, a ne dušu menjaju oni koji preko mora žure"],
	["Caesar ad Rubiconem","Cezar na Rubikonu"],
	["Caesar citra Rubiconem","Cezar sa ove strane Rubikona"],
	["Caesarem licet stantem mori","Cezar treba da umre stojeći"],
	["Caesarem vehis Caesarisque fortunam","Nosiš Cezara i Cezarovu sreću"],
	["Caesar non supra grammaticos","Cezar nije iznad gramatičara"],
	["Caetera activitati","Ostalo prepustimo radu"],
	["Caetera desiderantur","Ostalo se priželjkuje"],
	["Caetera desunt","Ostalo nedostaje"],
	["Calamitas virtutis occasio","Nesreća je prilika za vrlinu"],
	["Callida junctura","Vštački spoj / vešta veza"],
	["Calumniare audacter, semper aliquid haeret","Klevetajte odvažno, uvek nešto ostane"],
	["Calvitium non est vitium sed prudentiae judicium","Ćelavost nije mana nego znak mudrosti"],
	["Camera clara","Svetla komora"],
	["Camera lucida","Svetlosna komora"],
	["Camera obscura","Mračna komora"],
	["Camica santa","Sveta košulja"],
	["Candidior lacte","Belji od mleka"],
	["Canina facundia","Pseća rečitost (režanje)"],
	["Canis a non canendo","Pas jer ne peva"],
	["Cantabit vacuus coram latrone viator","Siromašan putnik peva pred razbojnikom"],
	["Capitis deminutio","Gubitak građanskih prava"],
	["Captatio benevolentiae","Pridobijanje naklonosti"],
	["Caput atro carbone notatum","Osoba obeležena crnim ugljem (zloglasna)"],
	["Caput mortuum","Mrtva glava / bezvredan ostatak"],
	["Caput mundi","Preshodnica sveta (Rim)"],
	["Caput orbi","Glava sveta"],
	["Caritas humani generis","Ljubav prema ljudskom rodu"],
	["Caritas omnia credit","Ljubav sve veruje"],
	["Carmen famosum","Klevetnička pesma"],
	["Carmen horrendum","Strašna pesma"],
	["Carmina nulla canam","Nijednu pesmu neću pevati"],
	["Carmina morte carent","Pesme ne umiru"],
	["Caro est qui securis est","Meso je onaj ko je pod sekirom"],
	["Carpe angelum","Uhvati anđela"],
	["Carpe diem","Iskoristi dan"],
	["Carpent tua poma nepotes","Tvoje plodove braće potomci"],
	["Carthago delenda est","Kartaginu treba razoriti"],
	["Casta est quam nemo rogavit","Čedna je ona koju niko nije pitao"],
	["Castis omnia casta","Čistima je sve čisto"],
	["Casum sentit dominus","Vlasnik snosi rizik slučajne propasti"],
	["Casus a nullo praestantur","Za slučajne događaje niko ne odgovara"],
	["Casus belli","Povod za rat"],
	["Casus conscietiae","Slučaj savesti"],
	["Casus foederis","Slučaj predviđen savezom"],
	["Casus incurabilis","Neizlečiv slučaj"],
	["Catena scientiarum","Lanac nauka"],
	["Causa activa","Aktivni uzrok"],
	["Causa bibendi","Povod za piće"],
	["Causa causalis","Uzrok uzroka"],
	["Causa civilis","Građanski pravni osnov"],
	["Causa criminalis","Krivični predmet"],
	["Causa efficiens","Delotvorni uzrok"],
	["Causa essendi","Uzrok postojanja"],
	["Causa finalis","Krajnji cilj / svrha"],
	["Causa finita est","Stvar je završena"],
	["Causa formalis","Formalni uzrok"],
	["Causa irae","Uzrok gnjeva"],
	["Causa justa","Pravno valjan razlog"],
	["Causa materialis","Materijalni uzrok"],
	["Causa naturalis","Prirodni uzrok"],
	["Causa occasionalis","Povod / sporedni uzrok"],
	["Causa prima","Prvi uzrok"],
	["Causa principalis","Glavni uzrok"],
	["Causa privata","Privatna stvar"],
	["Causa proxima, non remota spectatur","Gleda se neposredni, a ne daleki uzrok"],
	["Causa sine qua non","Uslov bez koga se ne može"],
	["Causa sufficiens","Dovoljan uzrok"],
	["Causa sui","Uzrok samoga sebe"],
	["Cautio judicatum solvi","Obezbeđenje za sudske troškove"],
	["Cave canem","Čuvaj se psa"],
	["Cave hominem unius libri","Čuvaj se čoveka koji je pročitao samo jednu knjigu"],
	["Cave ne cadas","Pazi da ne padneš"],
	["Caveant consules!","Neka konzuli budu na oprezu!"],
	["Cedant arma togae","Neka oružje ustupi mesto togi"],
	["Cedo majori","Ustupam većem od sebe"],
	["Censor morum","Čuvar morala"],
	["Certa de causa","Iz izvesnog razloga"],
	["Certa viriliter sustine patienter","Bori se muški, podnosi strpljivo"],
	["Cessante causa, cessat effectus","Kada prestane uzrok, prestaje i posledica"],
	["Cessio bonorum","Ustupanje imovine"],
	["Ceteris paribus","Pod ostalim jednakim uslovima"],
	["Ceterum censeo","Uostalom, smatram"],
	["Charta non erubescit","Papir ne crveni"],
	["Cibus, onus et virga asino","Hrana, teret i batina za magarca"],
	["Circulus in probando","Krug u dokazivanju"],
	["Circulus vitiosus","Začarani krug"],
	["Citato loco","Na navedenom mestu"],
	["Citius, altius, fortius!","Brže, više, jače!"],
	["Cito citissimo","Hitno, najhitnije"],
	["Civiliter mortui","Građanski mrtvi"],
	["Civis Romanus sum","Ja sam rimski građanin"],
	["Civitas Dei","Božija država"],
	["Clara pacta, boni amici","Čisti računi, duga ljubav"],
	["Clari viri","Slavni ljudi"],
	["Claris verbis","Jasnim rečima"],
	["Classicus scriptor","Klasični pisac"],
	["Classicus testis","Pouzdan svedok"],
	["Claudite jam rivos, sat prata biberunt","Zatvorite potoke, livade su se dovoljno napile"],
	["Clausula rebus sic stantibus","Kauzula dok stvari tako stoje"],
	["Cloaca maxima","Velika kanalizacija (Glavni odvod)"],
	["Codex chartaceus","Papirni kodeks"],
	["Codex manuscriptus","Rukopisni kodeks"],
	["Codex rescriptus","Ponovo napisan rukopis (palimpsest)"],
	["Coeli lumen","Nabeska svetlost"],
	["Cogita et visa","Misli i viđeno"],
	["Cogitationum poenam nemo luit","Niko ne snosi kaznu za misli"],
	["Cogito ergo sum","Mislim, dakle postojim"],
	["Cognata vocabula rebus","Reči odgovaraju stvarima"],
	["Cognatio spiritualis","Duhovno srodstvo"],
	["Coincidencia oppositorum","Spajanje suprotnosti"],
	["Collegium musicum","Muzički skup"],
	["Collegium privatum","Privatni kolegijum"],
	["Collegium publicum","Javni kolegijum"],
	["Colluvies gentium","Mešavina naroda"],
	["Columnae Herculis","Herkulovi stubovi"],
	["Commentarius perpetuus","Neprekidni komentar"],
	["Commodum possessionis","Prednost posedovanja"],
	["Commodum publicum","Opšta korist"],
	["Commotio cerebri","Potres mozga"],
	["Communa bonorem","Zajedničko dobro"],
	["Communibus annis","Prosečnih godina"],
	["Communis opinio","Opšte mišljenje"],
	["Comoedia togata","Rimska komedija (u togi)"],
	["Compelle intrate","Nateraj ih da uđu"],
	["Compesce mentem","Obuzdaj gnjev"],
	["Comple promissum","Ispunii obećanje"],
	["Compos mentis","Zdravog uma"],
	["Compos sui","Gospodar samog sebe"],
	["Conclamatum est","Završeno je / gotovo je"],
	["Concordet sermo cum vitā","Neka se reči slažu sa životom"],
	["Concordia discors","Neskladna sloga"],
	["Concordia parvae res crescunt, discordia maximae dilabuntur","Slogom male stvari rastu, neslogom se i najveće raspadaju"],
	["Conditio sine qua non","Uslov bez koga se ne može"],
	["Conditio suspensiva","Odložni uslov"],
	["Confessus pro judicato habetur","Onaj ko prizna, smatra se osuđenim"],
	["Confiteor solum hoc tibi","Priznajem ovo samo tebi"],
	["Consensus facit nuptias","Pristanak čini brak"],
	["Consensus gentium","Pristanak naroda"],
	["Consensus omnium","Sveopšta saglasnost"],
	["Consequentia non valet","Zaključak ne važi"],
	["Consideratis considerandis","Uzimajući sve u obzir"],
	["Consilio manuque","Savetom i rukom"],
	["Consilium abeundi","Savet da se ode (isključenje)"],
	["Consortium omnis vitae","Zajednica celog života"],
	["Consuetudo altera natura","Navika je druga priroda"],
	["Consummatum est!","Svršeno je!"],
	["Consumor aliis inserviendo","Sagorevam služeći drugima"],
	["Contra bonos mores","Prodiv dobrih običaja"],
	["Contra Gracchos Tiberim habemus","Nasuprot Grahima imamo Tiber"],
	["Contra factum non datur argumentum","Protiv činjenice nema argumenta"],
	["Contra jus et fas","Protiv ljudskog i božanskog prava"],
	["Contra tabulas","Suprotno dokumentima"],
	["Contra rationem","Protiv razuma"],
	["Contra contrariis curantur","Suprotno se leči suprotnim"],
	["Contra spem spero","Nadam se uprkos nadi"],
	["Contra vim mortis non est medicamen in hortis","Protiv sile smrti nema leka u vrtovima"],
	["Contradictio in adjecto","Protivrečnost u samom pojmu"],
	["Contradictio in contrarium","Protivrečnost suprotnom"],
	["Contradictio in re","Protivrečnost u samoj stvari"],
	["Contradictio simptomatum","Protivrečnost simptoma"],
	["Contraria sunt complementa","Suprotnosti se dopunjuju"],
	["Contumacia cumulat poenam","Oglušenje povećava kaznu"],
	["Coram arbitris","Pred sudijama"],
	["Coram hominibus","Pred ljudima"],
	["Coram publico (populo)","Pred javnošću (narodom)"],
	["Cornu copiae","Rog izobilja"],
	["Corpora non agent nisi soluta","Tela ne deluju osim ako su rastvorena"],
	["Corpus delicti","Predmet krivičnog dela"],
	["Corpus Domini","Telo Gospodnje"],
	["Corpus juris","Zbornik prava"],
	["Corpus juris civilis (romani)","Zbornik rimskog građanskog prava"],
	["Corpus simbioticum","Simbiozno telo"],
	["Corpus solidum","Čvrsto telo"],
	["Corpus vile","Bezvedno telo (objekat ogleda)"],
	["Correctis, corrigendis, imprimatur","Pravljeno, ispraviti, neka se štampa"],
	["Corruptio optimi pessima","Izopačenje najboljeg je najgore"],
	["Corruptissima re publica plurimae leges","U najnevaljalijoj državi ima najviše zakona"],
	["Corvus corno oculos non eruit","Vran vrani oči ne vadi"],
	["Crambe repetita","Podgrejani kupus (dosadno ponavljanje)"],
	["Crassa ignorantia","Potpuno neznanje"],
	["Crassa Minerva","Bez finoće / priprosta mudrost"],
	["Credo quia absurdum","Verujem jer je apsurdno"],
	["Credando vides","Verujući vidiš"],
	["Crescit amor nummi, quantum ipsa pecunia crescit","Raste ljubav prema novcu koliko raste i sam novac"],
	["Crescite, nos qui vivimus, multiplicamini","Množite se vi koji živite"],
	["Crimen laesae majestatis","Zločin uvrede veličanstva"],
	["Crimine ab uno disce omnes","Po jednom zločinu proceni sve"],
	["Cui bono?","U čiju korist?"],
	["Cui podest malum?","Kome koristi zlo?"],
	["Cujus regio, ejus lingua","Čija je zemlja, njegov je jezik"],
	["Cujus regio, ejus religio","Čija je zemlja, njegova je i vera"],
	["Cujusvis hominis est errare, nullius nisi insipientis in errore perseverare","Svakom čoveku se dešava da pogreši, ali samo budala ustrajava u grešci"],
	["Culpa fictia","Izmišljena krivica"],
	["Culpa in eligendo","Krivica zbog lošeg izbora"],
	["Culpa in inspiciendo","Krivica zbog nedovoljnog nadzora"],
	["Culpa lata","Teška krivica / nehat"],
	["Culpa lata dolo camparatur","Teški nehat se izjednačava sa namerom"],
	["Culpa lata dolo proxima est","Teški nehat je najbliži nameri"],
	["Culpa levis","Laki nehat"],
	["Culpa poena par esto","Kazna neka bude srazmerna krivici"],
	["Cum commento","Sa komentarom"],
	["Cum Deo","Sa Bogom"],
	["Cum eximia laude","Sa najvišom pohvalom"],
	["Cum figuris","Sa slikama / ilustracijama"],
	["Cum grano salis","Sa zrnom soli (sa rezervom)"],
	["Cum hoc non est propter hoc","Zajedno sa ovim ne znači i zbog ovoga"],
	["Cum moriar, medium solvar et inter opus","Kada umrem, neka to bude u sred posla"],
	["Cum notis variorum scriptorum","Sa zabeleškama raznih pisaca"],
	["Cum principia negante non est disputandum","Sa onim ko poriče osnovna načela ne treba raspravljati"],
	["Cum quodam fastidio","Sa izvesnim gadjenjem"],
	["Cum res unimum occupavere verba ambiunt","Kada stvar obuzme um, reči same dolaze"],
	["Cum tempore","Sa akademskim kašnjenjem (15 minuta)"],
	["Cum tot sustineas et tanta negotia solus","Kada sam nosiš toliki teret i tolike poslove"],
	["Cum vota consultiva","Sa savetodavnim glasom"],
	["Cuncta supercilio moventis","Pokreće sve obrvojom (vladar)"],
	["Cunctando restituit rem","Oklevanjem je spasio državu"],
	["Cupiditas rerum novarum","Želja za promenom (prevratom)"],
	["Cupio omnia, quae vis","Želim ti sve što želiš"],
	["Cura te ipsum","Izleči samoga sebe"],
	["Curae leves loquuntur, ingentes stupent","Male brige govore, velike neme"],
	["Currente calamo","Brzim perom (u žurbi)"],
	["Curriculum vitae","Biografija (tok života)"],
	["Cursus honorum","Redosled službi / karijera"],
	["Custodia honesta","Časni pritvor"],
	["Custos morum","Čuvar morala"],
	["Cymini sectores","Cepidlake (stani-cepači)"],
	["Damnant quod non intellegunt","Osuđuju ono što ne razumeju"],
	["Damnatio ad bestias","Osuđivanje na zveri"],
	["Damnatio memoriae","Prokletstvo sećanja"],
	["Damnatus est","Osuđen je"],
	["Damnosa quid non imminuit dies?","Šta sve ne uništi pogubni zub vremena?"],
	["Damnum emergens","Stvarna šteta"],
	["Damoclis gladius","Damoklov mač"],
	["(Timeo) Danaos et dona ferentes","Bojim se Danajaca i kad darove nose"],
	["Dat census honores","Bogatstvo donosi počasti"],
	["Dat, donat, dedĭcat (DDD)","Daje, daruje i posvećuje"],
	["Dat veniam corvis, vexat censura columbas","Prašta gavranovima, a progoni golubove"],
	["Date obolum Belisario","Dajte novčić Velizaru"],
	["De capsula totae","Svi iz iste kutije"],
	["De facto","Faktički / stvarno"],
	["De jure","Po pravu / zakonski"],
	["De gustibus non est disputandum","O ukusima ne treba raspravljati"],
	["De lana caprina rixari","Svađati se oko kozje vune (oko nebitnih stvari)"],
	["De lege ferenda","Sa stanovišta zakona koji treba doneti"],
	["De lege lata","Sa stanovišta postojećeg zakona"],
	["De lingua stulta incommoda multa","Zbog ludog jezika mnoge su nevolje"],
	["De mare ad mare","Od mora do mora"],
	["De minimis non curat lex","Zakon se ne bavi sitnicama"],
	["De mortuis aut bene, aut nihil","O mrtvima sve najbolje ili ništa"],
	["De mortuis et absentibus nihil nisi bene","O mrtvima i odsutnima samo najbolje"],
	["De nihilo nihil","Iz ničega ništa ne nastaje"],
	["De nomine","Po imenu"],
	["De novo","Iznova"],
	["De omni re scibili et quibusdam aliis","O svemu što se može znati i o još ponečemu"],
	["De omnibus dubito","U sve sumnjam"],
	["De possibili et impossibili","O mogućem i nemogućem"],
	["De principiis non est disputandum","O principima se ne raspravlja"],
	["De profundis","Iz dubine"],
	["De quo fabula narratur","O kome se priča priča"],
	["De rerum natura","O prirodi stvari"],
	["De se ipso modifice, de aliis honorifice","O sebi skromno, o drugima sa poštovanjem"],
	["De stercore Ennii","Iz Enijevog đubrišta"],
	["De visu et auditu","Iz viđenja i slušanja"],
	["Decies repetitia placebit","I deset puta ponovljeno će se svideti"],
	["Decipimur specie recti","Vara nas privid pravde"],
	["Debellare superbos","Savladati ponosne"],
	["Debes ergo potes","Moraš, dakle možeš"],
	["Deductio ad absurdum","Svođenje na apsurd"],
	["Definitio fit per genus et differentiam specificam","Definicija se pravi pomoću roda i specifične razlike"],
	["Dei gratia","Milošću Božijom"],
	["Delegatus non potest delegare","Delegirani ne može dalje delegirati"],
	["Delicta carnis","Grepesi tela"],
	["Delicta facti permanentis","Delikt sa trajnim posledicama"],
	["Delicta facti transeuntis","Trenutni delikt"],
	["Delectabile tempus!","Prijatno vreme!"],
	["Delictum commissionis","Delikt činjenja"],
	["Delictum communi juris","Opšti delikt"],
	["Delictum omissionis","Delikt nečinjenja"],
	["Delirium furens","Besno bunilo"],
	["Delirium tremens","Drhtavo bunilo"],
	["Dementia praecox","Rana demencija"],
	["Dementia senilis","Staračka demencija"],
	["Demonstratio ad oculos","Očigledan dokaz"],
	["Dente lupus, cornu taurus petit","Vuk napada zubom, bik rogom"],
	["Dente superbo","Oholim zubom"],
	["Dentibus albis","Belim zubima (smejući se)"],
	["Deo ignoto","Nepoznatom Bogu"],
	["Deos manes placari victimis humanis","Neka se podzemni bogovi umire ljudskim žrtvama"],
	["Desideria carnis","Telesne želje"],
	["Desine sperare qui hic intras","Napustite svaku nadu vi koji ulazite"],
	["Desinit in piscem mulier formosa superne","Lepa žena odgore završava se kao riba"],
	["Destruam et aedificabo","Razrušiću i ponovo ću sagraditi"],
	["Deus conservat omnia","Bog sve čuva"],
	["Deus ex machina","Bog iz mašine (neočekivano rešenje)"],
	["Deus magnus et potens, et terribilis","Bog je veliki, moćan i strašan"],
	["Deus vult","Bog tako želi"],
	["Di meliora","Neka bogovi daju bolje"],
	["Diagnosis ex juvantibus","Dijagnoza na osnovu delovanja leka"],
	["Diagnosis ex observatione","Dijagnoza na osnovu posmatranja"],
	["Dicendo de cibis dicendum est de moribus","Govoreći o hrani, mora se govoriti i o običajima"],
	["Dicis causa","Radi forme / reda radi"],
	["Dicis gratia","Radi reči"],
	["Dictum factum","Rečeno - učinjeno"],
	["Dictum sapienti sat est","Pametnome je reč dovoljna"],
	["Dies diem docet","Dan dan poučava"],
	["Dies interpellat pro homine","Rok opominje umesto čoveka"],
	["Dies irae","Dan gneva"],
	["Differentia specifica","Specifična razlika"],
	["Difficile est proprie communia dicere","Teško je na svoj način reći opšte stvari"],
	["Difficile est satyram non scribere","Teško je ne pisati satiru"],
	["Digitus dei est hic!","Ovde je prst Božiji!"],
	["Dignus est intrare","Dostojan je da uđe"],
	["Dii minorum gentium","Sporedni bogovi"],
	["Diligentia qualem diligentissimus pater familias abhibet","Pažnja kakvu pokazuje najbrižniji domaćin"],
	["Diligentia quam im rebus suis","Pažnja kao u sopstvenim stvarima"],
	["Diluvii testis","Svedok potopa (staromodna osoba)"],
	["Dimidium animae meae","Polovina moje duše"],
	["Dimidium facti, qui соерit, habet","Ko je počeo, uradio je polovinu posla"],
	["Dira necessitas","Krutu nužnost"],
	["Dis manibusque sacrum","Posvećeno dušama umrlih"],
	["Disjecta membra","Razbacani udovi"],
	["Displicuit nasus tuus","Nije mi se svideo tvoj nos"],
	["Diurna manu nocturnaquae","Rukom i danju i noću (nefrestano čitaj)"],
	["Divide et impera","Zavadi pa vladaj"],
	["Divinum opus sedare dolorem","Božansko je delo ublažiti bol"],
	["Dixi","Rekao sam"],
	["Dixi et animam levavi","Rekao sam i olakšao dušu"],
	["Dixi et animam meam salvavi","Rekao sam i spasao svoju dušu"],
	["Do manus","Dajem ruke (predajem se)"],
	["Do ut des","Dajem da bi mi dao"],
	["Do ut facias","Dajem da bi učinio"],
	["Docendo discimus (discitur)","Podučavajući učimo"],
	["Dolendi modus, timendi non item","Tuzi ima kraja, ali strahu nema"],
	["Dolus malus","Zla namera"],
	["Domi sedet lanam ducit","Sedi kod kuće i prede vunu"],
	["Domina omnium scientiarum","Gospodarica svih nauka"],
	["Dominium bonitarium","Bonitarna svojina"],
	["Dominus et deus noster sic fieri jubet","Naš gospodar i bog zapoveda da tako bude"],
	["Dominus litis","Gospodar spora"],
	["Don gratuit","Dobrovoljni prilog"],
	["Donec eris felix, multos numerabis amicos","Dok budeš srećan, imaćeš mnogo prijatelja"],
	["Donum didacticum","Nastavni dar"],
	["Draco dormiens nunquam titillandus","Nikada ne zagolicaj zmaja dok spava"],
	["Dramatis personae","Lica u drami"],
	["Duae res longe sunt difficillimae, lexicon scribere et grammaticam","Dve su stvari najteže: pisati rečnik i gramatiku"],
	["Dubia plus torquent mala","Sumnje više muče nego sama zla"],
	["Ducunt volentem fata, nolentem trahunt","Sudbina vodi one koji hoće, a vuče one koji neće"],
	["Dulce est desipere in loco","Prijatno je uveseljavati se u pravo vreme"],
	["Dulce et decorum est pro patria mori","Slatko je i časno umreti za domovinu"],
	["Dulce laudari a laudato viro","Prijatno je kad te hvali hvaljeni čovek"],
	["Dulcis fumus patriae","Sladak je dim zavičaja"],
	["Dum docemus, discimus","Dok poučavamo, učimo"],
	["Dum spiro spero","Dok dišem, nadam se"],
	["Dum vivimus vivamus","Dok živimo, živimo punim plućima"],
	["Duo quum faciunt idem, non est idem","Kad dvoje rade isto, to nije isto"],
	["Duobus certantibus tertius gaudet","Dok se dvojica svađaju, treći se raduje"],
	["Dura lex sed lex","Zakon je strog, ali je zakon"],
	["E pluribus unum","Iz mnogih jedno"],
	["Ea tempestate","U ono vreme"],
	["Eadem oberrare chorda","Grešiti na istoj struni"],
	["Ecce homo","Evo čoveka"],
	["Ecce spectaculum dignum, ad quod respiciat intentus operi suo Deus","Evo prizora dostojnog da ga pazi sam Bog"],
	["Ede, bibi, lude","Jedi, pij, igraj se"],
	["Edictum perpetuum","Trajni edikt"],
	["Edimus ut vivamus, non vivimus ut edamus","Jedemo da bismo živeli, ne živimo da bismo jeli"],
	["Edite, bibite, post mortem nulla voluptas","Jedite, pijte, posle smrti nema uživanja"],
	["Effectrix eloquentiae est audientium approbatio","Odobravanje slušalaca stvara rečitost"],
	["Ego","Ja"],
	["Ego cogito ergo sum","Ja mislim, dakle postojim"],
	["Ego sum rex Romanus et supra grammaticos","Ja sam rimski kralj i iznad gramatičara"],
	["Ego ti intus et in cute novi","Poznajem te iznutra i ispod kože"],
	["Ego versiculos feci, tulit alter honores","Ja sam pravio stihove, drugi je pokupio počasti"],
	["Eheu fugaces labuntur anni!","Ah, kako brzo prolaze godine!"],
	["Ei incumbit probatio, qui dicit, non qui negat","Teret dokazivanja je na onome ko tvrdi, a ne na onome ko poriče"],
	["Ejus est nolle qui potest velle","Onaj ko može želeti, može i odbiti"],
	["Ejusdem farinae","Iz istog testa"],
	["Ejusdem generis","Iste vrste"],
	["Elegantia juris","Pravna elegancija"],
	["Elephanti corio circumtentus est","Prekriven je slonovom kožom (debeli živci)"],
	["Eloquentia canina","Pseća rečitost"],
	["Emere catullum in sacco","Kupiti mačku u džaku"],
	["Emunctae naris homo","Oštrouman čovek"],
	["Ens a se","Biće po sebi"],
	["Ens causa sui","Biće koje je uzrok samoga sebe"],
	["Ens cogitans","Misleće biće"],
	["Ens rationis","Razumsko biće"],
	["Ens reale","Stvarno biće"],
	["Ens realissimum","Najstvarnije biće"],
	["Entia metaphysica","Metafizička bića"],
	["Epicuri de grege porcus","Svinja iz Epikurovog krda"],
	["Epistola non erubescit","Pismo ne crveni"],
	["Equo non credite Teucri","Ne verujte konju, Trojanci"],
	["Equus Troianus","Trojanski konj"],
	["Ergo","Dakle"],
	["Ergo bibamus","Dakle, pijmo"],
	["Erit sicut cadaver","Biće kao leš"],
	["Errare humanum est, ili Humanum errare est","Ljudski je grešiti"],
	["Errare humanum est sed stultum est in errore perseverare","Grešiti je ljudski, ali je ludo ustrajati u grešci"],
	["Eruditio aspera optima est","Strogo obrazovanje je najbolje"],
	["Est avis in dextra, melior quam quattuor extra","Bolja je ptica u ruci nego četiri izvan nje"],
	["Est deus in nobis","Boga ima u nama"],
	["Est modus in rebus","Postoji mera u stvarima"],
	["Est quaedam severe voluptas","I u plakanju ima nekog uživanja"],
	["Esse genus","Biti roda / vrsta"],
	["Esse, vivere, sentire","Postojati, živeti, osećati"],
	["Et alia","I ostalo"],
	["Et cetera","I tako dalje"],
	["Et fabula partem veri habet","I u bajci ima dela istine"],
	["Et fumus patriae dulcis","I dim zavičaja je sladak"],
	["Et gaudium et solatium in litteris","U književnosti je i radost i utahe"],
	["Et hoc genus omne","I sve te vrste"],
	["Et in Arcadia ego","I ja sam bio u Arkadiji"],
	["Et multa alia","I mnogo drugog"],
	["Et tu, Brute?","Zar i ti, Brute?"],
	["Et premitur ratione animus vincique laborat","Duh se pokorava razumu i trudi se da bude savladan"],
	["Et propter vitam vivendi perdere causas","Zbog života izgubiti razloge življenja"],
	["Et quibusdam aliis","I nekim drugim"],
	["Et semel emissum volat irrevocabile verbum","A jednom izgovorena reč leti nepovratno"],
	["Etiam periere ruinae","Čak su i ruševine nestale"],
	["Etiamsi omnes ego non","Ako će i svi ostali, ja neću"],
	["Eventus docet","Ishod poučava"],
	["Eventus stultorum magister est","Ishod je učitelj budalama"],
	["Ex abrupto","Nenadano / iznenada"],
	["Ex adverso","Sa suprotne strane"],
	["Ex aequo","Jednako / na ravne časti"],
	["Ex aequo et bono","Po pravičnosti i dobru"],
	["Ex auditu","Iz čuvenja"],
	["Ex cathedra","Sa katedre (mjerodavno)"],
	["Exclusa","Isključena"],
	["Ex mero motu","Iz sopstvene pobude"],
	["Exegi monumentum","Podigao sam spomenik"],
	["Ex libris","Iz knjiga"],
	["Ex nihilo nihil fit","Iz ničega ništa ne nastaje"],
	["Ex nunc prout ex tunc","Od sada kao i od tada"],
	["Ex officio","Po službenoj dužnosti"],
	["Ex quo loco?","Sa kog mesta?"],
	["Ex ungue leonem","Po kandži se poznaje lav"],
	["Exceptio probat regulam in casibus non exceptis","Izuzetak potvrđuje pravilo u neizuzetim slučajevima"],
	["Excitare fluctus in simpulo (см. Буря в стакане)","Praviti buru u čaši vode"],
	["Excudent alii spirantia mollius aera","Drugi će bolje vajati bronzu"],
	["Exempli gratia","Na primer"],
	["Experimenta est optima rerum magistra","Iskustvo je najbolji učitelj stvari"],
	["Experimentum crucis","Krajnji / presudni ogled"],
	["Extra omnes!","Svi napolje!"],
	["Faber est suae quisque fortunae","Svako je kovač svoje sreće"],
	["Factum est factum","Učinjeno je učinjeno"],
	["Fac fideli sis fidelis","Budi veran vernome"],
	["Facta, non verba","Dela, a ne reči"],
	["Fallaces sunt rerum species","Lida je spoljašnost stvari"],
	["Fas est et ab hoste doceri","Učiti treba i od neprijatelja"],
	["Fatum","Sudbina"],
	["Falax species rerum","Variljiv izgled stvari"],
	["Feci quod potui, faciant meliora potentes","Uradio sam šta sam mogao, ko može neka uradi bolje"],
	["Fecit","Uradio je"],
	["Ferox verbis","Oštar na rečima"],
	["Ferro et igni; Igni et ferro","Ognjem i mačem"],
	["Festina lente","Požuri polako"],
	["Fiat iustitia, et pereat mundus!","Neka bude pravda, pa makar propao svet!"],
	["Fiat lux!","Neka bude svetlost!"],
	["Fiat Roma, et ubi illa nunc est?","Izgradi Rim, pa gde je on sada?"],
	["Fidei defensor","Branič vere"],
	["Fidelis et fortis","Veran i hrabar"],
	["Finis coronat opus","Kraj delo krasi"],
	["Finis sanctificat media","Cilj opravdava sredstva"],
	["Fortis fortuna adiuvat (форма: Fortes fortuna adiuvat)","Sreća pomaže hrabrima"],
	["Forum delicti","Mesto izvršenja prekršaja"],
	["Fortis imaginatio generat casum","Jaka mašta stvara događaj"],
	["Fortuna caeca est","Sreća je slepa"],
	["Fuimus Troes, fuit Ilium","Bili smo Trojanci, bio je Ilij (sve je prošlo)"],
	["Furor Teutonicus","Tevtonski bes"],
	["Furtum manifestum","Očigledna krađa"],
	["Frustra fit per plura quod potest fieri per pauciora","Uzalud se radi sa više ono što se može uraditi sa manje"],
	["Gaudeamus igitur, juvenes dum sumus!","Radujmo se, dakle, dok smo mladi!"],
	["Genius loci","Duh mesta"],
	["Gratis","Besplatno"],
	["Gratias ago","Hvala vam"],
	["Gutta cavat lapidem <non vi sed saepe cadendo>","Kap dubi kamen, ne snagom nego čestim padanjem"],
	["Habeas corpus","Imaj telo (pravo na oslobođenje od nezakonitog pritvora)"],
	["Habemus Papam","Imamo papu"],
	["Hannibal ante portas","Hanibal je pred vratima"],
	["Hic bibitur","Ovde se pije"],
	["Heu quam est timendus qui mori tutus putat","Ah, kako je strašan onaj koji smatra da mu je smrt sigurna"],
	["Hic locus est ubi mors gaudet succurrere vitae","Ovo je mesto gde se smrt raduje što pomaže životu"],
	["Hic et nunc","Ovde i sada"],
	["Hic portus salutis","Ovo je luka spasenja"],
	["Hic Rhodus, hic salta","Ovde je Rodos, ovde skoči"],
	["Hic sunt dracones","Ovde su zmajevi"],
	["Hic sunt leones","Ovde su lavovi"],
	["Hoc fac et vinces","Uradi ovo i pobedićeš"],
	["Hoc volo, sic jubeo, sit pro ratione voluntas","Tako hoću, tako zapovedam, neka moja volja bude razlog"],
	["Hodie mihi, cras tibi","Danas meni, sutra tebi"],
	["Homo homini lupus est","Čovek je čoveku vuk"],
	["Homo proponit, sed Deus disponit","Čovek sniva, a Bog odlučuje"],
	["Homo Sapiens non urinat in ventum","Pametan čovek ne piški uz vetar"],
	["Homo sum, humani nihil a me alienum puto","Čovek sam i ništa ljudsko mi nije strano"],
	["Honores mutant mores, sed raro in meliores","Počasti menjaju ponašanje, ali retko nabolje"],
	["Honoris causa","Počasni (radi časti)"],
	["Horribile dictu","Strašno je reći"],
	["Humanum errare est","Ljudski je grešiti"],
	["Ibi semper est victoria, ubi concordia est","Tamo je uvek pobeda gde je sloga"],
	["Ibi victoria, ubi concordia","Tamo gde je sloga, tamo je pobeda"],
	["Ibidem","Na istom mestu"],
	["Idem per idem","Isto pomoću istog"],
	["Id est","To jest"],
	["In bono veritas","U dobrom je istina"],
	["Iesus Nazarenus, Rex Iudaeorum","Isus Nazarećanin, Kralj Jevreja"],
	["Igni et ferro","Ognjem i mačem"],
	["Ignoramus et ignorabimus","Ne znamo i nećemo znati"],
	["Ignorantia non excusat","Neznanje ne opravdava"],
	["Ignoratio elenchi","Neznavanje dokaza / skretanje sa teme"],
	["Ignorantia non est argumentum","Neznanje nije dokaz"],
	["Imago animi vultus est","Lice je slika duše"],
	["Imperare sibi maximum imperium est","Vladati sobom najveća je vlast"],
	["Imperatorem stantem mori oportet","Imperator treba da umre stojeći"],
	["In absentia","U odsustvu"],
	["In angustiis amici apparent","U nevolji se poznaju prijatelji"],
	["In articulo mortis","U času smrti"],
	["In camera","Iza zatvorenih vrata (u kabinetu)"],
	["In coena domini","Na večeri Gospodnjoj"],
	["In contumaciam","U prkosu / usled nedolaska"],
	["In corpore","U celini / svi zajedno"],
	["Indignus qui inter mala verba","Nedostojan među lošim rečima"],
	["In dubio pro reo","U sumnji, u korist optuženog"],
	["In flagrante delicto","U samom izvršenju dela / na delu"],
	["In foro scientiae","Pred sudom nauke"],
	["Ingenium mala saepe movent","Nevolje često podstiču um"],
	["In infinitum","U beskonačnost"],
	["In hoc signo vinces","U ovom znaku ćeš pobediti"],
	["Injuria realis","Fizička uvreda"],
	["Injuria verbalis","Verbalna uvreda"],
	["Injuriam faclius fasias guam feras","Nepravdu je lakše učiniti nego podneti"],
	["In memoriam","U sećanje / u spomen"],
	["In nomine Patris, et Filii, et Spiritus Sancti, (amen)","U ime Oca i Sina i Svetoga Duha (amin)"],
	["Innocens credit omni verbo","Nevin veruje svakoj reči"],
	["In partem salari","U uračunavanje plate"],
	["In perpetuum","Zauvek"],
	["In pricipio erat verbum","U početku beše Reč"],
	["In propria persona","Lično"],
	["In propia causa nemo jundex","Niko ne može biti sudija u sopstvenoj stvari"],
	["In rerum natura","U prirodi stvari"],
	["In saecula saeculorum","U vekove vekova"],
	["In silico","U kompjuterskoj simulaciji"],
	["In situ","Na samom mestu"],
	["Inter alia","Između ostalog"],
	["Inter arma enim silent leges","Među oružjem zakoni ćute"],
	["Inter arma silent Musae","Među oružjem ćute muze"],
	["Interdum lacriumae pondera vocis habent","Ponekad suze imaju težinu glasa"],
	["In utero","U materici"],
	["In vacuo","U vakuumu / praznom prostoru"],
	["Invia est in medicina via sine lingua latina","U medicini je neprohodan put bez latinskog jezika"],
	["Invia virtuti nulla est via","Za vrlinu nijedan put nije neprohodan"],
	["In vino veritas","U visu je istina"],
	["Inutile terrae pondus","Uzalan teret zemljin"],
	["Ipsa se velocitas implicat","Brzina sama sebe zapliće"],
	["In vitro","U epruveti"],
	["In vivo","Na živom organizmu"],
	["Ipse dixit","Sam je rekao"],
	["Ipso facto","Samim tim / po samom činu"],
	["Iura novit curia","Sud zna pravo"],
	["Ira furor brevis est","Gnjev je kratko ludilo"],
	["Ira odium generat, concordia nutrit amorem","Mržnja rađa gnjev, sloga hrani ljubav"],
	["Irreparabilium (iprepara rabilium) felix oblivio rerum","Srećan je zaborav nepopravljivih stvari"],
	["Is fecit cui prodest","Uradio je onaj kome koristi"],
	["Jamque opus exegi quod nec Jovis ira, nec ignis, nec poterit ferrum, nec edax abolere vetustas","I izradio sam delo koje ni Jupiterov bes, ni vatra, ni mač, ni zub vremena ne mogu uništiti"],
	["Judex damnatur, cum nocens absolvitur","Sudija se osuđuje kad se krivac oslobodi"],
	["Juris praecepta sunt haec: honeste vivere, alterum non laedere, suum cuique tribuere","Pravna načela su ova: pošteno živeti, drugoga ne povrediti, svakom svoje dati"],
	["Jus primae noctis","Pravo prve bračne noći"],
	["Jus primae occupationis","Pravo prvog zauzeća"],
	["Jus sanguinis","Pravo krvi (porekla)"],
	["Jus soli","Pravo tla (mesta rođenja)"],
	["Jus vitae ac necis","Pravo na život i smrt"],
	["Justitia regnorum fundamentum","Pravda je osnov država"],
	["Justum et tenacem propositi virum","Pravedan čovek i čvrst u nameri"],
	["Labor omnia vincit","Rad sve pobeđuje"],
	["Labor est etiam ipse voluptas","Rad je sam po sebi uživanje"],
	["Lassata viris necdum satiata recessit","Umorna od muškaraca, ali ne i zasićena, povukla se"],
	["Laborare est orare","Raditi znači moliti se"],
	["Lectori benevolo salutem, L.B.S.","Pozdrav dobronamernom čitaocu"],
	["Legum servi sumus ut liberi esse possimus","Sluge smo zakona da bismo bili slobodni"],
	["Letum non omnia finit","Smrt ne završava sve"],
	["Legio nomen mihi est","Legija mi je ime"],
	["Levis est labor omnis amanti","Svaki je rad lak onome ko voli"],
	["Lex specialis derogat generali","Posebni zakon ukida opšti"],
	["Lex posterior derogat legi priori","Kasniji zakon ukida raniji"],
	["Lex superior derogat legi inferiori","Viši zakon ukida niži"],
	["Lex talionis","Zakon odmazde (oko za oko)"],
	["Liberum veto","Slobodni veto"],
	["Libro ultimo","U poslednjoj knjizi"],
	["Licentia poetica","Pesnička sloboda"],
	["Littera scripta manet","Napisana reč ostaje"],
	["Littera humaniores","Humanističke nauke"],
	["Locus regit actum","Mesto određuje pravni čin"],
	["Lorem ipsum","Lorem ipsum (tekstualni popunjivač)"],
	["Longa manus calami","Duga ruka pera"],
	["Lege artis","Po pravilu struke"],
	["Lucri bonus est odor ex re qualibet","Miris dobitka je dobar bez obzira na izvor"],
	["Lupus in fabilus","Mi o vuku, a vuk na vrata"],
	["Lupus non mordet lupum","Vuk ne ujeda vuka"],
	["Lupus pilum mutat, non mentem","Vuk dlaku menja, ali ćud nikada"],
	["Lux in tenebris","Svetlost u tami"],
	["Lux ex tenebris","Svetlost iz tame"],
	["Magni nominis umbra","Senka velikog imena"],
	["Magnum opus","Veliko delo"],
	["Mala fides","Nesavesnost / zla namera"],
	["Malum discordiae","Jabuka razdora"],
	["Malum se ipsum devorat","Zlo samo sebe prožire"],
	["Manifestum non eget probatione","Očigledno ne treba dokazivati"],
	["Maniae infinitae sunt species","Vrste ludila su beskonačne"],
	["Manus manum lavat","Ruka ruku umiva"],
	["Margaritas ante porcos","Biserje pred svinje"],
	["Matrimonium iustum","Zakonit brak"],
	["Mea culpa","Moj greh / moja krivica"],
	["Mea virtute me involvo","Umotavam se u svoju vrlinu"],
	["Medica mente non medicamentis","Leči umom, a ne lekovima"],
	["Medicus curat, natūra sanat","Lekar leči, priroda uzdravljuje"],
	["Medius terminus","Srednji termin"],
	["Memento mori","Seti se da si smrtan"],
	["Memento vivere","Seti se da živiš"],
	["Memento quia pulvis es","Seti se da si prah"],
	["Mens sana in corpore sano","U zdravom telu zdrav duh"],
	["Metri causa","Radi stiha / metra"],
	["Metus, dolor, mors ac formidines","Strah, bol, smrt i užasi"],
	["Misericórdia - infirma","Milosrđe je slabo"],
	["Modus operandi","Način rada"],
	["Modus vivendi","Način života / sporazum"],
	["More majorum","Po običaju predaka"],
	["Mortem effugere nemo potest","Niko ne može pobeći od smrti"],
	["Multum vinum bibere - non diu vivere","Piti mnogo vina znači ne živeti dugo"],
	["Multi multa - Nemo omnia novit","Mnogi znaju mnogo, niko ne zna sve"],
	["Multa paucis","Mnogo u malo reči"],
	["Mutatis mutandibus","Uz odgovarajuće izmene"],
	["Nam vitiis nemo sine nascitur","Niko se ne rađa bez mana"],
	["Natura abhorret vacuum","Priroda se gadi praznine"],
	["Naturalia non sunt turpia","Prirodno nije sramotno"],
	["Navigare necesse est, vivere non est necesse","Ploviti se mora, živeti se ne mora"],
	["Naviget, haec summa est","Neka plovi, to je najvažnije"],
	["Nec gemino bellum Trojanum orditur ab ovo","Trojanski rat se ne počinje od dva jajeta"],
	["Nec nostri saeculi est","Nije u duhu našeg vremena"],
	["Nec Deus intersit","Neka se Bog ne meša"],
	["Nec pluribus impar","Jednak mnogima"],
	["Nec sutor ultra crepidam","Obućar neka ne ide dalje od cipela"],
	["Nemo debet bis puniri pro uno delicto","Niko ne treba da bude dva puta kažnjen za isti prekršaj"],
	["Nemo debet esse judex in propria causa","Niko ne treba da bude sudija u sopstvenoj stvari"],
	["Nemo me impune lacessit","Niko me ne može nekažnjeno izazvati"],
	["Nemo omnia potest scire","Niko ne može sve znati"],
	["Nemo solus satis sapit","Niko sam nije dovoljno pametan"],
	["Ne sutor supra crepidam","Neka obućar ne sudi iznad cipela"],
	["Nihil admirari","Ničemu se ne čuditi"],
	["Nihil habeo, nihil timeo","Ništa nemam, ničega se ne bojim"],
	["Nihil habeo, nihil curo","Ništa nemam, ni o čemu ne brinem"],
	["Nihil habenti nihil deest","Onome ko ništa nema, ništa ne nedostaje"],
	["Nil aliud scit necessitas quam vincere","Nužda ne zna ništa drugo osim da pobeđuje"],
	["Nil inultum remanebit","Ništa neće ostati neosvećeno"],
	["Nil sancti","Ništa nije sveto"],
	["Nil satis nisi optimum","Samo najbolje je dovoljno dobro"],
	["Nolens volens","Hteo - ne hteo"],
	["Nomen est omen","Ime je znak"],
	["Nomen Nescio","Ime nepoznato (N.N.)"],
	["Nomina sunt odiosa","Imena su mrska (imena ne treba pominjati)"],
	["Non bis in idem","Ne dva puta o istom"],
	["Non curatur, qui curat","Ne leči se onaj ko brine"],
	["Non est necesse ut omnis qui clamas et inquietas beatos dicenda est qui dat gratias parvum vobis gaudium - Не стоит кричать всем, что вы счастливы","Ne treba vikati svima da ste srećni"],
	["Non moritura","Nije namenjeno smrti"],
	["Non olet (см. Деньги не пахнут)","Ne smrdi (Novac ne smrdi)"],
	["Non plus ultra","Nema dalje / vrhunac"],
	["Non progredi est regredi","Ne napredovati znači nazadovati"],
	["Non rex est lex, sed lex est rex","Nije kralj zakon, već je zakon kralj"],
	["Non scholae, sed vitae discimus","Ne učimo za školu, već za život"],
	["Non tam praeclarum est scire Latine, quam turpe nescire","Nije toliko divno znati latinski, koliko je sramota ne znati ga"],
	["Non vi, sed arte","Ne silom, već veštinom"],
	["Nosce te ipsum","Upoznaj samoga sebe"],
	["Nota bene","Zabeleži dobro / obrati pažnju"],
	["Novus ordo seclorum","Novi poredak vekova"],
	["Nullum crimen sine poena, nulla poena sine lege, nullum crimen sine poena legali","Nema zločina bez kazne, nema kazne bez zakona, nema zločina bez zakonske kazne"],
	["Nusquam est qui ubique est","Nigde nije onaj ko je svuda"],
	["Occasio receptus difficiles habet","Prilika ima težak povratak"],
	["Oderint, dum metuant","Neka me mrze, samo dok me se plaše"],
	["Odi et amo","Mrzim i volim"],
	["Omissa spe qui huc intrasti","Napusti svaku nadu ti koji ulaziš"],
	["Omnia homini, dum vivit, speranda sunt","Čovek se mora nadati dok je živ"],
	["Omne vivum ex ovo","Sve živo nastaje iz jajeta"],
	["Omnes una manet nox","Sve nas čeka jedna noć"],
	["Omnes vulnerant, ultima necat","Svi časovi ranjavaju, poslednji ubija"],
	["Omnia mea mecum porto","Sve svoje sa sobom nosim"],
	["Omnia mutantur, nihil interit","Sve se menja, ništa ne propada"],
	["Omnia orta cadunt","Sve što je nastalo, propada"],
	["Omnia praeclara rara","Sve što je božanstveno je retko"],
	["Omnia vincit amor et nos cedamus amori","Ljubav sve pobeđuje, pokorimo se i mi ljubavi"],
	["Omnis homo mendax","Svaki je čovek lažov"],
	["Omnis ars imitatio est naturae","Svaka umetnost je oponašanje prirode"],
	["Omnium consensu","Uz saglasnost svih"],
	["Ora et labora","Moli se i radi"],
	["Orbis terrarum","Zemaljska kugla"],
	["Ordo ab chao","Red iz haosa"],
	["O sancta simplicitas","O, sveta jednostavnosti!"],
	["O tempora, o mores!","O vremena, o običaji!"],
	["Otia dant vitia","Besposlenost rađa poroke"],
	["Otium post negotium","Odmor posle posla"],
	["Pacta sunt servanda","Ugovori se moraju poštovati"],
	["Panem et circenses","Hleba i igara"],
	["Pater noster","Oče naš"],
	["Pax optima rerum est","Mir je najbolja stvar"],
	["Pax mundi","Mir u svetu"],
	["Pecunia non olet","Novac ne smrdi"],
	["Pecuniae oboediunt omnia","Novcu se sve pokorava"],
	["Per angusta ad augusta","Kroz teškoće do uzvišenih ciljeva"],
	["Per aspera ad astra","Kroz trnje do zvezda"],
	["Per definitionem","Po definiciji"],
	["Per Iovem","Tako mi Jupitera"],
	["Periculum in mora","Opasnost je u odlaganju"],
	["Perpetuum mobile","Večiti motor"],
	["Per se","Sam po sebi"],
	["Persona grata","Poželjna osoba"],
	["Persona non grata","Nepoželjna osoba"],
	["Persona suspecta","Sumnjiva osoba"],
	["Personae dramatis","Lica u drami"],
	["Pes sic tendatur ne lodix protereatur","Pruži noge koliko ti je pokrivač dugačak"],
	["Petitio principii","Pretpostavljanje osnovice dokaza"],
	["Pictoribus atque poetis","Slikarima i pesnicima (sve je dozvoljeno)"],
	["Pie Jesu Domine, dona eis requiem","Blagi Gospode Isuse, daruj im mir"],
	["Plus ultra","Još dalje"],
	["Poëma","Pesma"],
	["Poëtae nascuntur, oratōres fiunt","Pesnici se rađaju, govornici postaju"],
	["Porta itineri longissima","Kapija je najduži deo puta"],
	["Post coitum omne animal triste est","Posle spajanja svaka je životinja tužna"],
	["Post factum","Posle učinjenog dela"],
	["Post hoc ergo propter hoc","Posle toga, dakle zbog toga"],
	["Post hoc non est propter hoc","Posle toga ne znači i zbog toga"],
	["Post mortem","Posle smrti"],
	["Post prandium stabis, post cenam ambulabis","Posle ručka stoj, posle večere hodaj"],
	["Post scriptum","Posle napisanog (P.S.)"],
	["Post tenebras lux","Posle tame dolazi svetlost"],
	["Potius sero quam nunquam","Bolje ikad nego nikad"],
	["Praemonitus praemunitus","Unapred upozoren, unapred naoružan"],
	["Primo","Prvo"],
	["Primum non nocere","Pre svega ne naškoditi"],
	["Primus inter pares","Prvi među jednakima"],
	["Pro forma","Radi forme"],
	["Pro pace","Za mir"],
	["Pro patria mori","Umreti za domovinu"],
	["Pro poena","Za kaznu"],
	["Pro tempore","Za sada / privremeno"],
	["Probatio minus plena","Nepotpun dokaz"],
	["Probatuum est","Dokazano je"],
	["Procul negotiis","Daleko od briga"],
	["Qua definitione","Po definiciji"],
	["Quae medicamenta non sanat, ferrum sanat; Quae ferrum non sanat, ignis sanat. Quae vero ignis non sanat, insanabilia reputari oportet","Što ne izleče lekovi, leči nož; što ne izleči nož, leči vatra; što ne izleči vatra, smatra se neizlečivim"],
	["Qualis artifex pereo!","Kakav umetnik umire u meni!"],
	["Quantum satis","Koliko je dovoljno"],
	["Qui nimium probat, nihil probat.","Ko suviše dokazuje, ništa ne dokazuje."],
	["Qui non laborat, non manducet","Ko ne radi, neka ne jede"],
	["Qui non proficit deficit.","Ko ne napreduje, nazaduje."],
	["Qui pro quo","Jedno umesto drugog / nesporazum"],
	["Qui scribit, bis legit","Ko piše, dva puta čita"],
	["Qui seminat mala, metet mala","Ko seje zlo, požnjeće zlo"],
	["Qui sine pecato est?","Ko je bez greha?"],
	["Qui ventum seminat, turbinem metet","Ko seje vetar, požnjeće buru"],
	["Quid dubitas, ne faceris","Ako sumnjaš, ne radi to"],
	["Quid est veritas?","Šta je istina?"],
	["Quid pro quo","Ovo za ono / usluga za uslugu"],
	["Quid timeas? Caesarem vehis Caesarisque fortunam","Čega se plašiš? Nosiš Cezara i Cezarovu sreću"],
	["Quis? Quid? Ubi? Quibus auxiliis? Cur? Quomodo? Quando?","Ko? Šta? Gde? Kojiim sredstvima? Zašto? Kako? Kada?"],
	["Quis custodiet ipsos custodes?","Ko će čuvati same čuvare?"],
	["Quo tendis?","Kuda ideš?"],
	["Quo vadis?","Kuda ideš?"],
	["Quod deus bene vertat","Neka Bog okrene na dobro"],
	["Quod erat demonstrandum","Što je trebalo dokazati"],
	["Quod fert fortuna, fer!","Što nosi sudbina, podnosi!"],
	["Quod gratis asseritur, gratis negatur","Što se bez dokaza tvrdi, bez dokaza se i poriče"],
	["Quod licet Jovi, non licet bovi","Što je dozvoljeno Jupiteru, nije dozvoljeno volu"],
	["Quod scripsi, scripsi","Što sam napisao, napisao sam"],
	["Quot capita, tot sententiae","Koliko glava, toliko mišljenja"],
	["Quo usque pro Roma ibis?","Dokle ćeš ići za Rim?"],
	["Radices litterarum amarae sunt, fructus dulces","Koreni znanja su gorki, ali su plodovi slatki"],
	["Rara est [adeo] concordia formae atque pudicitiae","Retka je sloga između lepote i čednosti"],
	["Rebus sic stantibus","Dok stvari tako stoje"],
	["Rectus","Pravo / ispravno"],
	["Reddite quae sunt Caesaris Caesari, et quae sunt Dei Deo","Podajte Cezaru Cezarovo, a Bogu Božije"],
	["Reductio ad absurdum","Svođenje na apsurd"],
	["Regula certa datur: bene qui stat, non moveatur","Dato je sigurno pravilo: ko dobro stoji, neka se ne pomera"],
	["Repetitio est mater studiorum","Ponavljanje je majka znanja"],
	["Requiescat in pace","Neka počiva u miru"],
	["Requiem aeternam dona eis, Domine","Večni mir daj im, Gospode"],
	["Res Publica","Javna stvar / država"],
	["Respice finem","Misli na kraj"],
	["Respondeat superior","Neka odgovara nadređeni"],
	["Reti ventos venari","Mrežom hvatati vetar"],
	["Rex regnat, sed non gubernat","Kralj vlada, ali ne upravlja"],
	["Roma invicta","Nepobedivi Rim"],
	["Roma locuta, causa finita","Rim je rekao svoje, stvar je završena"],
	["Roma traditoribus non premia","Rim ne nagrađuje izdajnike"],
	["Salus populi suprema lex","Dobrobiti naroda je najviši zakon"],
	["Sancta sanctorum","Svetinja nad svetinjama"],
	["Sapere aude","Usudi se da budeš mudan (misliš svojom glavom)"],
	["Sapenti sat","Pametnome dosta"],
	["Scientia potentia est","Znanje je moć"],
	["Scire leges non hoc est verba earum tenere, sed vim ac potestatem","Poznavati zakone ne znači znati njihove reči, već njihov smisao i snagu"],
	["Secundo","Drugo"],
	["Sed alia tempora","Ali druga su vremena"],
	["Sed semel insanivimus omnes","Svi smo mi makar jednom bili ludi"],
	["Sede Vacante","Dok je stolica prazna"],
	["Sedia Gestatoria","Nosiljka za papu"],
	["Sed non quo ad hanc","Ali ne u pogledu ovoga"],
	["Semper idem","Uvek isto"],
	["Semper in motu","Uvek u pokretu"],
	["Semper fidelis","Uvek veran"],
	["Senatus bestia, senatores boni viri","Senat je zver, a senatori su dobri ljudi"],
	["Senatus Populusque Romanus (S.P.Q.R)","Senat i narod Rima"],
	["Sententia absolutoria","Oslobađajuća presuda"],
	["Sero venientibus ossa","Kasno dolazećima samo kosti"],
	["Serva me, servanto te","Spasi ti mene, spasio sam ja tebe"],
	["Servus Servorum Dei","Sluga slugu Božijih"],
	["Si parva licet componere magnis","Ako se malo može porediti sa velikim"],
	["Si vales, bene est; Ego valeo (SVBEEV)","Ako si dobro, u redu je; ja sam dobro"],
	["Si vis amari, ama!","Ako hoćeš da budeš voljen, voli!"],
	["Si vis pacem, para bellum","Ako hoćeš mir, spremaj rat"],
	["Si vis vincere, disce pati","Ako hoćeš da pobediš, nauči da trpiš"],
	["Sic!","Tako! / Upravo tako!"],
	["Sic itur ad astra","Tako se ide do zvezda"],
	["Sic transit gloria mundi","Tako prolazi slava sveta"],
	["Sic semper tyrannis","Tako uvek tiranima"],
	["Sic volo, sic jubeo!","Tako hoću, tako zapovedam!"],
	["Silentium est aurum","Ćutanje je zlato"],
	["Silentium videtur confessio","Ćutanje se smatra priznanjem"],
	["Similia similibus curantur","Slično se leči sličnim"],
	["Sine causa","Bez razloga"],
	["Sine cura","Bez brige (sinakura)"],
	["Sine ira et studiо","Bez gnjeva i pristrasnosti"],
	["Sit tibi terra levis","Neka ti je laka zemlja"],
	["Sitio","Žedan sam"],
	["Sola Scriptura","Samo Pismo"],
	["Soli Deo gloria","Samo Bogu slava"],
	["Sol lucet omnibus","Sunce sija svima"],
	["Solum debilis mori debent","Samo slabi treba da umru"],
	["Solus cum sola, in loco remoto, non cogitabuntur orare «Pater noster»","Muskarac sam sa ženom na skrovitom mestu neće misliti na molitvu"],
	["Status quo","Trenutno stanje"],
	["Status quo ante bellum","Stanje pre rata"],
	["Sub rosa","Pod ružom (u tajnosti)"],
	["Sub specie aeternitatis","Sa stanovišta večnosti"],
	["Sudore et sanguine","Znojem i krvlju"],
	["Sui generis","Svoje vrste / osoben"],
	["Suis quaeque temporibus","Sve u svoje vreme"],
	["Summa summarum","Zbir zbirova / sve u svemu"],
	["Supra nos Fortuna negotia curat","Iznad nas Sreća vodi poslove"],
	["Supremum vale","Poslednji pozdrav"],
	["Sursum corda","Gore srca"],
	["Suum cuique","Svakom svoje"],
	["Tabula rasa","Prazna tabla"],
	["Tacito consensu","Prećutnom saglasnošću"],
	["Tale quale","Takvo kakvo jeste"],
	["Te amo est verum","Istina je da te volim"],
	["Tempora mutantur et nos mutamur in illis","Vremena se menjaju i mi se menjamo u njima"],
	["Tempus edax rerum","Vreme koje sve prožire"],
	["Tempus fugit","Vreme leti"],
	["Tempora labuntur, tacitisque senescimus annis","Vreme prolazi i starimo u nečujnim godinama"],
	["Tertium non datur","Treće nije dato (nema treće mogućnosti)"],
	["Terra incognita","Nepoznata zemlja"],
	["Terra nullius","Ničija zemlja"],
	["Terminus post quem","Rok posle koga"],
	["Testis unus - testis nullus","Jedan svedok kao nijedan"],
	["Timeo Danaos et dona ferentes","Bojim se Danajaca i kad darove nose"],
	["Toties quoties","Koliko puta, toliko puta"],
	["Totum revolutum","Sve ispremještano / opšti haos"],
	["Totus floreo","Sav cvetam"],
	["Trahit sua quemque voluptas","Svakog privlači njegova strast"],
	["Tres faciunt collegium","Trojica čine društvo"],
	["Tres muliers faciunt nundias","Tri žene čine pijacu"],
	["Ubi bene, ibi patria","Gde mi je dobro, tamo mi je domovina"],
	["Ubi concordia, ibi victoria","Gde je sloga, tamo je pobeda"],
	["Ubi culpa est ibi poena subbesse debet","Gde je krivica, tamo treba da bude i kazna"],
	["Ubi nil vales, ibi nil velis","Gde ništa ne možeš, tu ništa ne želi"],
	["Ubi mel, ibi apes","Gde je med, tamo su i pčele"],
	["Ubi mel, ibi fel","Gde je med, tamo je i žuč"],
	["Ubi pus, ibi incisio","Gde je gnoj, tu raseci"],
	["Ultima ratio","Krajnje sredstvo"],
	["Ultra posse nemo obligatur","Preko mogućnosti niko nije obavezan"],
	["Una voce","Jednoglasno"],
	["Unde venis?","Odakle dolaziš?"],
	["Unum et idem","Jedno te isto"],
	["Unus pro omnibus, omnes pro uno","Svi za jednog, jedan za sve"],
	["Urbi et Orbi","Gradu (Rimu) i svetu"],
	["Usus est optimus magister","Iskustvo je najbolji učitelj"],
	["Utile dulce miscere","Spojiti korisno sa prijatnim"],
	["Ut tensio sic vis","Kakvo istezanje, takva i sila"],
	["Ut desint vires, tamen est laudanda voluntas","Iako nedostaje snaga, valja pohvaliti volju"],
	["Uti, non abuti","Koristiti, a ne zloupotrebljavati"],
	["Vale","Zbogom / budi zdrav"],
	["Vade retro, Satana","Odstupi od mene, Satano"],
	["Vae victis","Teško pobeđenima"],
	["Vanitas vanitatum et omnia vanitas","Taština nad taštinama i sve je taština"],
	["Varietas delectat","Raznolikost pričinjava zadovoljstvo"],
	["Veni, vidi, vici","Dođoh, videh, pobedih"],
	["Verba magistri","Reči učitelja"],
	["Verba volant, scripta manent","Reči lete, zapisano ostaje"],
	["Verbatim","Od reči do reči"],
	["Verte","Okreni stranicu"],
	["Verum est quod pro salute fit mendacium","Istina je da je laž opravdana ako je radi spasenja"],
	["Veto","Zabranjujem"],
	["Versus","Protiv"],
	["Via est vita","Put je život"],
	["Viam supervadet vadens","Put savladava onaj ko korača"],
	["Vice versa","Obrnuto"],
	["Vide licet","To jest / naime"],
	["Videre majus quiddam","Videti nešto veće"],
	["Vince in bono malum","Pobedi zlo dobrim"],
	["Vinum - memoriae mors","Vino je smrt za pamćenje"],
	["Vinum verba ministrat","Vino daje reči"],
	["Viribus unitis","Zajedničkim snagama"],
	["Vis unita fortior","Ujedinjena snaga je jača"],
	["Vita brevis ars longa","Život je kratak, umetnost je duga"],
	["Vita sine libertate, nihil","Život bez slobode je ništa"],
	["Vita sine litteris mors est","Život bez knjige je smrt"],
	["Vitae sal - amicitia","Prijateljstvo je so života"],
	["Vivenda","Ono što treba proživeti"],
	["Vivere est cogitare","Živeti znači misliti"],
	["Vi veri universum vivus vici","Snagom istine za života sam osvojio svemir"],
	["Volens nolens","Hteo - ne hteo"],
	["Volo ergo sum","Želim, dakle postojim"],
	["Volo, non valeo","Hoću, ali ne mogu"],
	["Votum separatum","Izdvojeno mišljenje"],
	["Vox populi vox Dei","Glas narod je glas Božiji."]
];

/* Game */

const youWon = "Pobedili ste!";
const youLost = "Izgubili ste!";
let tip = ".";

// Звуковые эффекты
let audio_yes = new Audio("yes.mp3");
let audio_no = new Audio("no.mp3");
let audio_win = new Audio("win.mp3");
let audio_los = new Audio("los.mp3");

function Game()
{
	let index = Math.floor(Math.random() * movies.length);
	let word = movies[index][0];
	tip = movies[index][1];
	word = word.toUpperCase();
	let guessedLetters = [];
	let maskedWord = "";
	let incorrectGuesses = 0;
	
	const allLetters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
	let won = false;
	let lost = false;
	const maxGuesses = 7;

	for ( let i = 0; i < word.length; i++ )
	{
		let nextCharacter = word.charAt(i);
		let charCode = nextCharacter.charCodeAt(0);
		let A = 65;
		let Z = 90;
		if( A <= charCode && charCode <= Z )
		{
			nextCharacter = "_";
		}
		maskedWord += nextCharacter;
	}

	let guess = function( letter )
	{
		letter = letter.toUpperCase();
		if( !guessedLetters.includes( letter ) && !won && !lost )
		{	
			guessedLetters.push(letter);
			
			if( word.includes( letter ) )
			{
				let matchingIndexes = [];
				for ( let i = 0; i < word.length; i++ ) 
				{
					if( word.charAt(i) === letter )
					{
						matchingIndexes.push( i );
					}
				}

				matchingIndexes.forEach( function(index) {
					maskedWord = replace( maskedWord, index, letter );
				});	

				won = maskedWord === word;
				
				if(won) {
					maskedWord = word;
					audio_win.play().catch(() => {});
				} else {
					audio_yes.play().catch(() => {});
				}
			}
			else
			{
				handleIncorrectGuess();
			}
		}
	}

	let handleIncorrectGuess = function()
	{
		incorrectGuesses++;
		lost = incorrectGuesses >= maxGuesses;
		if( lost )
		{
			maskedWord = word;
			audio_los.play().catch(() => {});
		}
		else
		{
			audio_no.play().catch(() => {});
		}
	}

	return {
		"getWord": function(){ return word; },
		"getMaskedWord": function(){ return maskedWord; },
		"guess": guess,
		"getAllLetters": function(){ return [...allLetters]; },
		"getGuessedLetters": function(){ return guessedLetters; },
		"getIncorrectGuesses": function(){ return incorrectGuesses; },
		"isWon": function(){ return won; },
		"isLost": function(){ return lost; }
	};
}

function replace( value, index, replacement ) 
{
	return value.substring(0, index) + replacement + value.substring(index + replacement.length);
}

function listenForInput( game ) 
{
	let guessLetter = function( letter )
	{
		if( letter )
		{
			let gameStillGoing = !game.isWon() && !game.isLost();
			if( gameStillGoing )
			{
				game.guess( letter );
				render( game );
			}
		}
	};

	let handleClick = function( event )
	{
		if (event.target.classList.contains('guess') && !event.target.classList.contains('disabled'))
		{
			guessLetter( event.target.innerHTML.trim() );
		}
	}

	let handleKeyPress = function( event )
	{
		let letter = null;
		const A = 65;
		const Z = 90;
		const ENTER = 13;
		let isLetter = event.keyCode >= A && event.keyCode <= Z;
		let newGameButton = document.getElementById("newGameButton");
		let gameOver = game.isWon() || game.isLost();

		if( isLetter )
		{
			letter = String.fromCharCode( event.keyCode );
		}
		else if( event.keyCode === ENTER && gameOver )
		{
			newGameButton.click();
		}
		guessLetter( letter );
	}

	document.addEventListener('keydown', handleKeyPress );
	document.body.addEventListener('click', handleClick );
}

function render( game )
{
	document.getElementById("word").innerHTML = game.getMaskedWord(); 
	
	let guessesContainer = document.getElementById("guesses");
	guessesContainer.innerHTML = "";
	
	let guessedLetters = game.getGuessedLetters();
	
	game.getAllLetters().forEach( function(letter) {
		let isGuessed = guessedLetters.includes(letter);
		let disabledClass = isGuessed ? " disabled" : "";
		
		let innerHtml = "<span class='guess" + disabledClass + "'>" + letter + "</span>";
		guessesContainer.innerHTML += innerHtml;
	});
	
	document.getElementById("hangmanImage").src = "img/hangman" + game.getIncorrectGuesses() + ".png";

	let tipBox = document.getElementById('tipBox');
	
	if( game.isWon() )
	{
		tipBox.textContent = youWon + " " + tip;
		tipBox.className = "win";
	}
	else if( game.isLost() )
	{
		tipBox.textContent = youLost + " " + tip;
		tipBox.className = "loss";
	}
	else
	{
		tipBox.textContent = tip;
		tipBox.className = "";
	}
}

function newGame()
{
	history.go(0);
}

let game = new Game();
render( game );
listenForInput( game );