let words = [
	["A caelo usque ad centrum", "Од неба до центра Земље"],
	["A capillo usque ad ungues", "Од косе до ноктију"],
	["A capite ad calcem", "Од главе до пете"],
	["A casu ad casum", "Од случаја до случаја"],
	["A contrario", "С супротне стране (насупрот томе)"],
	["A dato", "Од дана издавања"],
	["A die", "Од овог дана"],
	["A fortiori", "Узимајући у обзир јачи разлог (тим пре)"],
	["A limine", "Са самог прага (одмах, без разматрања)"],
	["A maiore ad minus", "Од већег ка мањем"],
	["A mari usque ad mare", "Од мора до мора"],
	["A maximis ad minima", "Од највећег ка најмањем"],
	["A mensa et toro", "Од стола и постеље (развод/раставит)"],
	["A nativitate", "Од рођења"],
	["A nescire ad non esse", "Од незнања ка непостојању"],
	["A novo", "Изнова (од почетка)"],
	["A parte", "Пострани (одвојено)"],
	["A pedibus usque ad caput", "Од ногу до главе"],
	["A posse ad esse", "Од могућег ка стварном"],
	["A posse ad esse non valet consequentia", "Из могућности не следи нужно и стварност"],
	["A posteriori", "На основу искуства"],
	["A potentia ad actum", "Од могућности ка остварењу"],
	["A potiori", "На основу претежног/јачег разлога"],
	["A potiori fit denominatio", "Називање се врши по главном својству"],
	["A prima facie", "На први поглед"],
	["A priori", "Независно од искуства (унапред)"],
	["A probis probari, ab improbis improbari aequa laus est", "Једнака је хвала када те хвале добри и када те куде лоши"],
	["A realibus ad realiora", "Од стварног ка стварнијем"],
	["A sacris", "Одвојен од светих ствари"],
	["A tuo lare incipe", "Почни од свог дома"],
	["Ab absurdo", "Од апсурда (доказивање апсурдом)"],
	["Ab aeterno", "Од вечности"],
	["Ab antiquo", "Од старине"],
	["Ab equis ad asinos", "Са коња на магарце"],
	["Ab esse ad posse valet consequentia", "Из стварности следи могућност"],
	["Ab exterioribus ad interiora", "Од спољашњег ка унутрашњем"],
	["Ab extra", "Споља"],
	["Ab hinc", "Од сада"],
	["Ab hoc et ab hac", "О овом и о оном (разноразне смушене речи)"],
	["Ab hodierno", "Од данашњег дана"],
	["Ab hoedis scindere oves", "Одвојити овце од јараца"],
	["Ab igne ignem", "Ватра од ватре"],
	["Ab imis unguibus ad verticem summum", "Од врхова ножића до врха главе"],
	["Ab imo pectore", "Из дубине груди (из свег срца)"],
	["Ab inconvenienti", "На основу непријатности/непогодности"],
	["Ab incunabulis", "Из колике (од калевка)"],
	["Ab initio", "Од почетка"],
	["Ab initio nullum, semper nullum", "Што је од почетка ништавно, остаје увек ништавно"],
	["Ab intestato", "Без тестамента"],
	["Ab irato", "У сутњи (у гневу)"],
	["Ab Iove principium", "Почетак од Јупитера (почети од најважнијег)"],
	["Ab origine", "Од порекла"],
	["Ab ovo", "Од јајета (од самог почетка)"],
	["Ab ovo usque ad mala", "Од јајета до јабука (од почетка до краја ручка)"],
	["Ab posse ad esse consequentia non valet", "Закључивање од могућности на стварност нема снагу"],
	["Ab uno disce omnes", "По једноме упознај све"],
	["Ab Urbe condita", "Од оснивања Града (Рима)"],
	["Abeunt studia in mores", "Интересовања прелазе у навике"],
	["Abiens, abi!", "Одлазећи, одлази!"],
	["Absente aegroto", "У одсутности болесника"],
	["Absit omen!", "Нека то не буде лош знак!"],
	["Absit verbo invidia", "Нека речи не изазову завист/увреду"],
	["Absolutio ab instantia", "Ослобађање услед недостатка доказа"],
	["Absolvo te!", "Опраштам ти!"],
	["Absque nota", "Без ознаке"],
	["Absque omni exceptione", "Без икаквог изузетка"],
	["Abstractum pro concreto", "Апстрактно уместо конкретног"],
	["Absurdum in adiecto", "Апсурд у придодатом (противречност)"],
	["Abusus non tollit usum", "Злоупотреба не укида право коришћења"],
	["Abyssus abyssum invocat", "Бездан бездан призива"],
	["Accessio cedit principali", "Споредна ствар прати главну"],
	["Acta diurna", "Дневни догађаји (новине)"],
	["Acta est fabula!", "Представа је завршена!"],
	["Actio immanens", "Унутрашња радинст (акција)"],
	["Actio in distans", "Деловање на даљину"],
	["Actio in factum", "Тужба на основу чињеничног стања"],
	["Actio popularis", "Народна тужба"],
	["Actio transiens", "Прелазна радња"],
	["Actore non probante reus absolvitur", "Ако тужилац не докаже, оптужени се ослобађа"],
	["Actor sequitur forum rei", "Тужилац прати суд туженог"],
	["Actum atque tractatum", "Завршено и договорено"],
	["Actum est ilicet!", "Све је завршено!"],
	["Actum ut supra", "Урађено као што је горе наведено"],
	["Actus purus", "Чист чин (чиста стварност)"],
	["Ad absurdum", "До апсурда"],
	["Ad acta", "Међу списе (архивирати)"],
	["Ad aeternum", "Завек"],
	["Ad aras", "До жртвеника"],
	["Ad arbitrium", "По слободној вољи"],
	["Ad augusta per angusta", "До узвишеног кроз препреке"],
	["Ad bestias!", "Пред звери!"],
	["Ad Calendas Graecas", "О грчким календама (никад)"],
	["Ad captandum benevolentiam", "Да би се задобила наклоност"],
	["Ad captandum vulgus", "Да би се задобила светина"],
	["Ad cogitandum et agendum homo natus est", "Човек је рођен за размишљање и деловање"],
	["Ad delectandum", "За забаву"],
	["Ad discendum, non ad docendum", "За учење, а не за подучавање"],
	["Ad disputandum", "За расправу"],
	["Ad ea debeat adaptari ius, quae frequenter eveniunt", "Право треба прилагодити ономе што се често дешава"],
	["Ad exemplum", "На пример"],
	["Ad extra", "Према споља"],
	["Ad extremitates", "До крајности"],
	["Ad finem", "До краја"],
	["Ad fontes", "На изворе"],
	["Ad futuram memoriam", "За будуће сећање"],
	["Ad futuram rei memoriam", "За будуће сећање на догађај"],
	["Ad gloriam", "За славу"],
	["Ad gustum", "По укусу"],
	["Ad hastam", "На аукцију (на јавну продају)"],
	["Ad Herculis columnas", "До Херкулових стубова"],
	["Ad hoc", "За ову сврху (посебно за ову прилику)"],
	["Ad hominem", "Према човеку (на личност)"],
	["Ad honores", "Ради части"],
	["Ad hoste maligno libera nos, Domine", "Од злог непријатеља избави нас, Господе"],
	["Ad impossibilia nemo tenetur", "Нико није обавезан на немогуће"],
	["Ad infinitum", "У бесконачност"],
	["Ad informandum", "Ради информисања"],
	["Ad instar", "По угледу на"],
	["Ad instruendum", "За припрему (за прикупљање грађе)"],
	["Ad interim", "Привремено"],
	["Ad latus", "Уз бок (помоћник)"],
	["Ad libita librarii", "По вољи преписивача"],
	["Ad libitum", "По вољи / по жељи"],
	["Ad limina", "До прагова (апостолских)"],
	["Ad litem", "За потребе парнице"],
	["Ad litteram", "Дословно"],
	["Ad loca!", "На своја места!"],
	["Ad maiorem Dei gloriam", "На већу славу Божју"],
	["Ad manum", "При руци"],
	["Ad maximum", "До максимума"],
	["Ad meliora tempora", "До бољих времена"],
	["Ad meliorem", "Ка бољем"],
	["Ad memorandum", "За подсетник"],
	["Ad minimum", "На минимум"],
	["Ad modum", "По начину"],
	["Ad multos annos!", "На много година!"],
	["Ad narrandum, non ad probandum", "За казивање, а не за доказивање"],
	["Ad nauseam", "До мучнине"],
	["Ad normam", "По норми"],
	["Ad notam", "К знању"],
	["Ad notanda", "За бележење"],
	["Ad notata", "Ка забелешкама"],
	["Ad oculos", "Очигледно (пред очи)"],
	["Ad opus!", "На посао!"],
	["Ad patres", "К прецима (умрети)"],
	["Ad patres conscriptos", "Сенаторима (обраћање сенату)"],
	["Ad perpetuam rei memoriam", "За трајно сећање на догађај"],
	["Ad personam", "Лично (на одређену особу)"],
	["Ad pias causas", "У добротворне сврхе"],
	["Ad pluralitatem votorum", "Већином гласова"],
	["Ad populum", "Народно (обраћање народу)"],
	["Ad profundum", "До дубине (до дна)"],
	["Ad publicandum", "За објављивање"],
	["Ad ratificandum", "На потврду"],
	["Ad referendum", "За извештај (привремено)"],
	["Ad rem", "Пређимо на ствар"],
	["Ad se ipsum", "К самом себи"],
	["Ad totalem evaporationem", "До потпуног испаравања"],
	["Ad tertium", "Треће"],
	["Ad unguem", "До тачице (до нокта)"],
	["Ad unum omnes", "Сви до једног"],
	["Ad usum delphini", "За употребу Делфина (пречишћено издање)"],
	["Ad usum externum", "За спољашњу употребу"],
	["Ad usum internum", "За унутрашњу употребу"],
	["Ad usum populi", "За народну употребу"],
	["Ad usum proprium", "За сопствену употребу"],
	["Ad usum vitae", "За животу употребу"],
	["Ad valorem", "Према вредности"],
	["Ad verbum", "Реч по реч"],
	["Ad verbum audiendum", "Ради саслушања"],
	["Ad victoriam", "До победе"],
	["Ad vitam", "За живот"],
	["Ad vitam aeternam", "За вечни живот"],
	["Ad vitam aut culpam", "Доживотно или до прве кривице"],
	["Ad vocem", "По питању речи (по поводу)"],
	["Adhuc sub iudice lis est", "Спор је још увек код судије"],
	["Adverbium", "Прилог"],
	["Advitalitum", "Доживотно уживање"],
	["Advocatus Dei", "Божји адвокат"],
	["Advocatus Diaboli", "Ђавољи адвокат"],
	["Aequam memento rebus in arduis servare mentem", "Запомни да сачуваш спокојан дух у тешким тренуцима"],
	["Aequat causa effectum", "Узрок је једнак последици"],
	["Aequilibrium indifferentiae", "Равнотежа неодлучности"],
	["Aequo animo", "Равнодушно (мирног духа)"],
	["Aequo pulsat pede", "Удара истом ногом (смрт куца исто и сиромаху и цару)"],
	["Aequum est neminem cum alterius detrimento et iniuria fieri locupletiorem", "Праведно је да се нико не обогати на штету и увреду другог"],
	["Aere perennius", "Трајније од бронзе"],
	["Aes triplex", "Троструки месинг (троструки штит)"],
	["Aeterna historia", "Вечна историја"],
	["Aeterna urbs", "Вечни град"],
	["Aeternae veritates", "Вечне истине"],
	["Aeternum vale", "Вечно збогом"],
	["Age, libertate decembri utere", "Хајде, искористи децембарску слободу"],
	["Age, quod agis, et respice finem", "Ради то што радиш и мисли на крај"],
	["Agere sequitur esse", "Деловање следи из бића"],
	["Ager publicus", "Јавно земљиште"],
	["Agnosco veteris vestigia flammae", "Препознајем трагове старог пламена"],
	["Agnus Dei", "Јагње Божје"],
	["Aio!", "Тврдим!"],
	["Albo lapillo notare diem", "Белим каменчићем означити дан"],
	["Alea iacta est", "Коцка је бачена"],
	["Alia editio", "Друго издање"],
	["Alia tempora", "Друга времена"],
	["Alibi", "На другом месту"],
	["Aliena vitia in oculis habemus, a tergo nostra sunt", "Туђе мане су нам пред очима, а наше су нам иза леђа"],
	["Alienatio mentis", "Помућење ума"],
	["Alieni iuris", "Под туђим правом"],
	["Aliis inserviendo consumor", "Служећи другима трошим се"],
	["Aliquando bonus dormitat Homerus", "Кадкад и забрињавајући Хомер заспа критикујући"],
	["Aliud stans, aliud sedens", "Једно говори стојећи, друго седећи"],
	["Alius alio plura invenire potest, nemo omnia", "Један може да нађе више од другог, али нико све"],
	["Alma Mater", "Мајка хранитељица (Универзитет)"],
	["Alter ego", "Друго ја"],
	["Alter idem", "Други исти"],
	["Altera pars", "Друга страна"],
	["Altum silentium", "Дубока тишина"],
	["Amabile opus", "Драгоцено дело"],
	["Amabilis insania", "Пријатно лудило"],
	["Amabilis scientia", "Љупка наука (ботаника)"],
	["Amant alterna Camenae", "Музе воле наизменичне песме"],
	["Amantes non vident. Videntes non amant.", "Заљубљени не виде. Они који виде не воле."],
	["Amantes sunt amentes", "Заљубљени су безумни"],
	["Amantium irae", "Свађе заљубљених"],
	["Amantium irae amoris integratio", "Свађе заљубљених су обнављање љубави"],
	["Amat victoria curam", "Победа воли припрему"],
	["Amata nobis quantum amabitur nulla", "Вољена од нас као што ниједна неће бити вољена"],
	["Amen!", "Амин!"],
	["Amicalia desideria", "Пријатељске жеље"],
	["Amici, diem perdidi", "Пријатељи, изгубио сам дан"],
	["Amicus certus in re incerta cernitur", "Прави се пријатељ у невољи познаје"],
	["Amicus cognoscitur amore, more, ore, re", "Пријатељ се познаје по љубави, понашању, речима и делима"],
	["Amicus humani generis", "Пријатељ људског рода"],
	["Amicus incommodus ab inimico non differt", "Непредусретљив пријатељ се не разликује од непријатеља"],
	["Amicus meus", "Мој пријатељ"],
	["Amicus Plato, sed magis amica est veritas", "Драг ми је Платон, али ми је дража истина"],
	["Amicus verus rara avis", "Истинити пријатељ је ретка птица"],
	["Amor caecus", "Љубав је слепа"],
	["Amor fati", "Љубав према судбини"],
	["Amor patriae", "Љубав према отаџбини"],
	["Amor vincit omnia", "Љубав све побеђује"],
	["Amor non est medicabilis herbis", "Љубав се не лечи травама"],
	["An nescis longas regibus esse manus?", "Зар не знаш да краљеви имају дуге руке?"],
	["An nescis, mi fili, quantilla prudentia mundus regatur?", "Зар не знаш, сине мој, са како мало мудрости се влада светом?"],
	["Analogia entis", "Аналогија бића"],
	["Anathema maranatha", "Анатема маранапа (нека буде анатемисан)"],
	["Ancilla philosophiae", "Служавка филозофије"],
	["Ancilla theologiae", "Служавка теологије"],
	["Anguis in herba", "Змија у трави"],
	["Angulus ridet", "Овај ми се кутак смеши"],
	["Anima", "Душа"],
	["Anima vilis", "Безвредна душа"],
	["Animalia vivunt, crescunt et sentiunt", "Животиње живе, расту и осећају"],
	["Animam in promptu habere", "Имати душу на длану"],
	["Animi magnitudo", "Величина духа"],
	["Animus", "Дух / Намера"],
	["Animus denuntiandi", "Намера пријављивања"],
	["Animus iniuriandi", "Намера вређања"],
	["Animus meminisse horret", "Душа дрхти када се сети"],
	["Animus possidendi", "Намера држања (поседовања)"],
	["Animus quod perdidit optat, atque in praeterita se totus imagine versat", "Душа жуди за оним што је изгубила и сва се удубљује у слике прошлости"],
	["Animus rem sibi habendi", "Намера задржавања ствари за себе"],
	["Animus suspicax", "Сумњичав дух"],
	["Anni currentis", "Текуће године"],
	["Anno", "Године"],
	["Anno ab urbe condita", "Године од оснивања Града"],
	["Anno aetatis suae", "У години свог живота"],
	["Anno ante Christum natum", "Године пре Христовог рођења"],
	["Anno Christi", "Године Христове"],
	["Anno Domini", "Године Господње"],
	["Anno mundi", "Године света"],
	["Anno post Romam conditam", "Године након оснивања Рима"],
	["Annus horribilis", "Ужасна година"],
	["Ante bellum", "Пре рата"],
	["Ante Christum natum", "Пре Христовог рођења"],
	["Ante diem", "Пре одређеног дана"],
	["Ante factum", "Пре чина"],
	["Ante mare undae", "Пре мора беху таласи"],
	["Ante meridiem", "Пре подне"],
	["Ante nuptias donatio", "Поклон пре брака"],
	["Ante quem", "Пре кога"],
	["Anterioritas", "Првенство (предност)"],
	["Ante scriptum", "Пре написаног"],
	["Apparatus criticus", "Критички апарат"],
	["Appellatio", "Жалба (апелација)"],
	["Appendix", "Dodatak"],
	["Appetitus societatis", "Тежња ка друштву"],
	["Aqua bulliens", "Кључала вода"],
	["Aqua destillata", "Дестилована вода"],
	["Aqua et igni alicui interdicere", "Укратити коме воду и ватру (прогнати)"],
	["Aqua et ignis", "Вода и ватра"],
	["Aqua et panis, vita canis", "Вода и хлеб — пасји живот"],
	["Aqua fontana", "Изворска вода"],
	["Aqua lapidem cavat non vi, sed saepe cadendo", "Вода дуби камен не снагом, већ честим капањем"],
	["Aqua pluvialis", "Кишница"],
	["Aqua pura", "Чиста вода"],
	["Aqua tophana", "Тофанина вода (отров)"],
	["Aqua vitae", "Вода живота (ракија)"],
	["Aquae et ignis interdictio, hoc est exsilium", "Забрана воде и ватре, то је прогнанство"],
	["Aquae potoribus", "За оне који пију воду"],
	["Aquila non captat muscas", "Орао не хвата муве"],
	["Arbiter elegantiae", "Судија елеганције (арбитар укуса)"],
	["Arboretum", "Дендролошки парк"],
	["Arcades ambo", "Обојица су Аркађани (исти су)"],
	["Argenteis hastis pugnare", "Борити се сребрним копљима (подмићивати)"],
	["Argentum nitricum", "Сребро-нитрат"],
	["Argumenta ambigua", "Двосмислени докази"],
	["Argumenta ponderantur, non numerantur", "Докази се мере, а не броје"],
	["Argumentum a contrario", "Доказ из супротности"],
	["Argumentum a posteriori", "Доказ на основу искуства"],
	["Argumentum a priori", "Доказ независно од искуства"],
	["Argumentum a silentio", "Доказ на основу ћутања"],
	["Argumentum a tuto", "Безбедан доказ"],
	["Argumentum ab impossibili", "Доказ из немогућности"],
	["Argumentum achilleum", "Ахилов доказ (главни доказ)"],
	["Argumentum ad crumenam", "Доказ новчаником (апел на материјалну корист)"],
	["Argumentum ad hominem", "Доказ усмерен на човека"],
	["Argumentum ad ignorantiam", "Доказ заснован на незнању"],
	["Argumentum ad invidiam", "Доказ апеловањем на завист"],
	["Argumentum ad iudicium", "Доказ апеловањем на здрав разум"],
	["Argumentum ad misericordiam", "Доказ апеловањем на милосрђе"],
	["Argumentum ad populum", "Доказ апеловањем на народ"],
	["Argumentum ad rem", "Доказ усмерен на суштину ствари"],
	["Argumentum ad verecundiam", "Доказ апеловањем на ауторитет (поштовање)"],
	["Argumentum ad veritatem", "Доказ усмерен ка истини"],
	["Argumentum ambiguum", "Двосмислен доказ"],
	["Argumentum baculinum", "Доказ батином"],
	["Argumentum ex consensu gentium", "Доказ на основу општег слагања народа"],
	["Argumentum ex silentio", "Доказ из ћутања"],
	["Argumentum externum", "Спољашњи доказ"],
	["Argumentum internum", "Унутрашњи доказ"],
	["Argumentum legis", "Законски доказ"],
	["Argumentum primarium", "Главни доказ"],
	["Arma virumque cano", "О оружју и јунаку певам"],
	["Arrectis auribus", "Са наћуљеним ушима"],
	["Ars adeo latet arte sua", "Уметност је скривена сопственом уметношћу"],
	["Ars amandi", "Уметност љубави"],
	["Ars est celare artem", "Уметност је сакрити уметност"],
	["Ars et norma interpretandi naturam", "Уметност и правило тумачења природе"],
	["Ars gubernandi", "Уметност управљања"],
	["Ars moriendi", "Уметност умирања"],
	["Ars logica", "Логичка уметност"],
	["Ars longa, vita brevis", "Уметност је дуга, живот кратак"],
	["Ars oratoria", "Беседничка уметност"],
	["Ars poetica", "Песничка уметност"],
	["Ars sacra", "Света уметност"],
	["Ars una, species mille", "Уметност је једна, појава је хиљаду"],
	["Ars vitae", "Уметност живљења"],
	["Artes ingenuae", "Слободне уметности"],
	["Artes molliunt mores", "Уметности облагорађују обичаје"],
	["Articulo mortis", "У моменту смрти"],
	["Articulus", "Члан / Тачка"],
	["Articulus secretissimus", "Најстрожа тајна тачка"],
	["Artificiosa natura", "Уметничка природа"],
	["Artium magister", "Магистар уметности"],
	["Asa foetida", "Смрдљива смола"],
	["Asini exiguo pabulo vivunt", "Магарци живе од мало хране"],
	["Asinos non curo", "За магарце не марим"],
	["Asinus asinorum in saecula saeculorum", "Магарац над магарцима у векове векова"],
	["Asinus asinum fricat", "Магарац магарца чеше"],
	["Asinus Buridani inter duo prata", "Буриданов магарац између два ливаде"],
	["Associatio idearum", "Асоцијација идеја"],
	["Astra inclinant, non necessitant", "Звезде наговештавају, али не приморавају"],
	["Asylum ignorantiae", "Уточиште незнања"],
	["Atrium mortis", "Предворје смрти"],
	["Atrophia nervorum", "Атрофија живаца"],
	["Auctoritas foris", "Ауторитет споља"],
	["Auctoritas rei iudicatae", "Ауторитет пресуђене ствари"],
	["Audacter calumniare, semper aliquid haeret", "Клеветај одважно, увек нешто остане"],
	["Audentes fortuna iuvat", "Срећа помаже храбрима"],
	["Audiatur et altera pars", "Нек се саслуша и друга страна"],
	["Auguror nec me fallit augurium, historias tuas immortales futuras", "Предвиђам и пророчанство ме не вара, твоје историје биће бесмртне"],
	["Aura popularis", "Наклоност народа"],
	["Aurea mediocritas", "Златна средина"],
	["Aures habent, et non audient", "Уши имају, а не чују"],
	["Auri sacra fames", "Проклета глад за златом"],
	["Auribus teneo lupum", "Држим вука за уши"],
	["Aurora borealis", "Поларна светлост"],
	["Aurora musis amica est", "Зора је пријатељица муза"],
	["Aurum nostrum non est aurum vulgi", "Наше злато није злато простака"],
	["Aurum potestas est", "Злато је моћ"],
	["Auspicia sunt fausta", "Знамења су повољна"],
	["Auspicium melioris aevi", "Знамење бољег доба"],
	["Aut bene, aut nihil", "Или добро, или ништа"],
	["Aut bibat, aut abeat", "Или пиј, или одлази"],
	["Aut Caesar, aut nihil", "Или Цезар, или ништа"],
	["Aut cum scuto, aut in scuto", "Или са штитом, или на штиту"],
	["Aut deus, aut natura", "Или Бог, или природа"],
	["Aut non tentaris, aut perfice", "Или не покушавај, или доврши"],
	["Aut disce, aut discede", "Или учи, или одлази"],
	["Aut prodesse volunt aut delectare poetae", "Песници желе или да користе или да забаве"],
	["Aut vincere, aut mori", "Или победити, или умрети"],
	["Ave", "Здраво"],
	["Ave, Caesar, morituri te salutant", "Здраво, Цезаре, поздрављају те они који ће умрети"],
	["Ave Maria", "Здраво Маријо"],
	["Ave ac vale", "Здраво и збогом"],
	["Ave verum corpus", "Здраво, истинито тело"],
	["Avibus bonis", "Са добрим птицама (повољним знамењима)"],
	["Bacchum Nymphis temperare", "Мешати Баха са Нимфама (вино са водом)"],
	["Barba crescit caput nescit", "Брада расте, глава не зна"],
	["Barba non facit philosophum", "Брада не чини филозофа"],
	["Barbam video, sed philosophum non video", "Браду видим, али филозофа не видим"],
	["Barbarus hic ego sum, quia non intelligor ulli", "Овде сам ја варвар, јер ме нико не разуме"],
	["Beata stultitia", "Блажено незнање"],
	["Beatae plane aures, quae non vocem foris sonantem, sed intus auscultant veritatem docentem", "Блажене су уши које не слушају глас споља, већ унутрашњу истину која подучава"],
	["Beati pauperes spiritu", "Блажени сиромашни духом"],
	["Beati possidentes", "Блажени они који поседују"],
	["Beatitudo non est virtutis praemium, sed ipsa virtus", "Блаженство није награда за врлину, већ сама врлина"],
	["Beatus ille, qui procul negotiis", "Блажен онај који је далеко од послова"],
	["Bella matribus detestata", "Ратови омражени мајкама"],
	["Bellum internecivum", "Рат до истребљења"],
	["Bellum omnium contra omnes", "Рат свих против свих"],
	["Bene diagnoscitur, bene curatur", "Добро се дијагностикује, добро се лечи"],
	["Bene misceatur", "Добро измешати"],
	["Bene placito", "По добром вољи"],
	["Bene qui latuit, bene vixit", "Ко је добро живео скривен, добро је живео"],
	["Bene tritum", "Добро иситњено"],
	["Bene valete", "Будите здрави (збогом)"],
	["Benevole lector", "Добронамерни читаоче"],
	["Benevolentiae captandae causa", "Ради задобијања наклоности"],
	["Bestiolae, quae unum tantum diem vivunt", "Животињице које живе само један дан"],
	["Biblia pauperum", "Библија сиромашних"],
	["Bibliothecae scriptorum", "Библиотека писаца"],
	["Bis dat qui cito dat", "Двоструко даје ко брзо даје"],
	["Bis repetita placent", "Оно што се двапут понови свиђа се"],
	["Bis vincit qui se vincit in victoria", "Двоструко побеђује онај ко себе победи у победи"],
	["Bona adventicia", "Имовина стечена са стране"],
	["Bona dicta", "Добре речи"],
	["Bona fama divitiis est potior", "Добар глас је вреднији од богатства"],
	["Bona fide", "У доброј вери"],
	["Bona fides", "Добра вера"],
	["Bona hereditaria", "Наследна имовина"],
	["Bona mente", "Са добром намером"],
	["Bona opinio homini tuttior pecunia est", "Добро мишљење је човеку сигурније од новца"],
	["Bona venia vestra", "Са вашим љубазним допуштењем"],
	["Bonae fidei possessio", "Држање у доброј вери"],
	["Boni homines", "Добри људи"],
	["Bonis auspiciis", "Под добрим знамењима"],
	["Bono modo", "На добар начин"],
	["Bono sensu", "У добром смислу"],
	["Bonum publicum", "Опште добро"],
	["Bonum vinum laetificat cor hominum", "Добро вино весели срце људи"],
	["Bonus eventus", "Добар исход"],
	["Bonus ordo", "Добар ред"],
	["Bonus pater familias", "Добар домаћин"],
	["Bonus vir semper tiro est", "Добар човек је увек почетник"],
	["Breves vibrantesque sententiae", "Кратке и упечатљиве мисли"],
	["Brevi manu", "Укратко (без формалности)"],
	["Brevis esse laboro, obscurus fio", "Трудим се да будем кратак, а постајем нејасан"],
	["Bruta fulmina", "Празна претња (слепа муња)"],
	["Cacatum non est pictum", "Загађено није насликано"],
	["Cadit quaestio", "Питање отпада"],
	["Cadmea victoria", "Кадмејска победа (победа која доноси пропаст)"],
	["Caedite eos. Novit enim Dominus qui sunt eius", "Убијајте их све, Господ ће препознати своје"],
	["Caelo tonantem credidimus Iovem regnare", "Пјевајући са неба веровали смо да Јупитер влада"],
	["Caelum, non animum mutant, qui trans mare currunt", "Они који прелазе море мењају небо, а не дух"],
	["Caesar ad Rubiconem", "Цезар на Рубикону"],
	["Caesar citra Rubiconem", "Цезар са ове стране Рубикона"],
	["Caesarem licet stantem mori", "Цезару приличи да умре стојећи"],
	["Caesarem vehis Caesarisque fortunam", "Носиш Цезара и Цезарову срећу"],
	["Caesar non supra grammaticos", "Цезар није изнад граматичара"],
	["Caetera activitati", "Остало препустити активности"],
	["Caetera desiderantur", "Остало се прижељкује"],
	["Caetera desunt", "Остало недостаје"],
	["Calamitas virtutis occasio", "Несрећа је прилика за врлину"],
	["Callida iunctura", "Вешто повезивање"],
	["Calumniare audacter, semper aliquid haeret", "Клеветај одважно, увек нешто остане"],
	["Calvitium non est vitium sed prudentiae iudicium", "Ћелавост није мана већ знак мудрости"],
	["Camera clara", "Светла комора"],
	["Camera lucida", "Светла комора"],
	["Camera obscura", "Мрачна комора"],
	["Camica santa", "Света кошуља"],
	["Candidior lacte", "Бељи од млека"],
	["Canina facundia", "Пасја речитост"],
	["Canis a non canendo", "Пас по томе што не пева"],
	["Cantabit vacuus coram latrone viator", "Сиромашан путник певаће пред разбојником"],
	["Capitis deminutio", "Губитак грађанских права"],
	["Captatio benevolentiae", "Придобијање наклоности"],
	["Caput atro carbone notatum", "Глава означена црним угљем"],
	["Caput mortuum", "Мртва глава (безвредни остатак)"],
	["Caput mundi", "Престоница света"],
	["Caput orbi", "Глава света"],
	["Caritas humani generis", "Љубав према људском роду"],
	["Caritas omnia credit", "Љубав све верује"],
	["Carmen famosum", "Клеветничка песма"],
	["Carmen horrendum", "Застрашујућа песма"],
	["Carmina nulla canam", "Никакве песме нећу певати"],
	["Carmina morte carent", "Песме не умиру"],
	["Caro est qui securis est", "Тело је онај ко носи секиру"],
	["Carpe angelum", "Ухвати анђела"],
	["Carpe diem", "Искористи дан"],
	["Carpent tua poma nepotes", "Твоје ће плодове брати унуци"],
	["Carthago delenda est", "Картагину треба разорити"],
	["Casta est quam nemo rogavit", "Чедна је она коју нико није питао"],
	["Castis omnia casta", "Чистима је све чисто"],
	["Casum sentit dominus", "Власник сноси ризик случајне пропасти"],
	["Casus a nullo praestantur", "За случај нико не одговара"],
	["Casus belli", "Повод за рат"],
	["Casus conscientiae", "Случај савести"],
	["Casus foederis", "Случај предвиђен уговором"],
	["Casus incurabilis", "Неизлечив случај"],
	["Catena scientiarum", "Ланац наука"],
	["Causa activa", "Делатни узрок"],
	["Causa bibendi", "Разлог за пиће"],
	["Causa causalis", "Узрок свих узрока"],
	["Causa civilis", "Грађански правни основ"],
	["Causa criminalis", "Кривични предмет"],
	["Causa efficiens", "Делатни узрок"],
	["Causa essendi", "Узрок постојања"],
	["Causa finalis", "Коначни циљ"],
	["Causa finita est", "Случај је закључен"],
	["Causa formalis", "Формални узрок"],
	["Causa irae", "Узрок гнева"],
	["Causa iusta", "Праведни разлог"],
	["Causa materialis", "Материјални узрок"],
	["Causa naturalis", "Природни узрок"],
	["Causa occasionalis", "Поводни узрок"],
	["Causa prima", "Први узрок"],
	["Causa principalis", "Главни узрок"],
	["Causa privata", "Приватна парница"],
	["Causa proxima, non remota spectatur", "Гледа се непосредни, а не удаљени узрок"],
	["Causa sine qua non", "Услов без ког се не може"],
	["Causa sufficiens", "Довољан узрок"],
	["Causa sui", "Узрок самог себе"],
	["Cautio iudicatum solvi", "Озбиље за трошкове поступка"],
	["Cave canem", "Чувај се psa"],
	["Cave hominem unius libri", "Чувај се човека који је прочитао само једну књигу"],
	["Cave ne cadas", "Пази да не padнеш"],
	["Caveant consules!", "Нека консули буду на опрезу!"],
	["Cedant arma togae", "Нек оружје уступи место тоги"],
	["Cedo maiori", "Уступам већем"],
	["Censor morum", "Чувар морала"],
	["Certa de causa", "Из одређеног разлога"],
	["Certa viriliter sustine patienter", "Бори се мушки, подноси стрпљиво"],
	["Cessante causa, cessat effectus", "Престанком узрока престаје и деловање"],
	["Cessio bonorum", "Уступање имовине"],
	["Ceteris paribus", "Под осталим једнаким условима"],
	["Ceterum censeo", "Уосталом, сматрам"],
	["Charta non erubescit", "Папир не црвени"],
	["Cibus, onus et virga asino", "Храна, терет и штап за магарца"],
	["Circulus in probando", "Круг у доказивању"],
	["Circulus vitiosus", "Зачарани круг"],
	["Citato loco", "На наведеном месту"],
	["Citius, altius, fortius!", "Брже, више, јаче!"],
	["Cito citissimo", "Што је брже могуће"],
	["Civiliter mortui", "Грађански мртви"],
	["Civis Romanus sum", "Римски сам грађанин"],
	["Civitas Dei", "Божја држава"],
	["Clara pacta, boni amici", "Чист рачун, дуга љубав"],
	["Clari viri", "Знаменити људи"],
	["Claris verbis", "Јасним речима"],
	["Classicus scriptor", "Класични писац"],
	["Classicus testis", "Поуздан сведок"],
	["Claudite iam rivos, sat prata biberunt", "Затворите већ канале, ливаде су се доста напојиле"],
	["Clausula rebus sic stantibus", "Клаузула о промењеним околностима"],
	["Cloaca maxima", "Велика канализација"],
	["Codex chartaceus", "Папирни кодекс"],
	["Codex manuscriptus", "Рукописни кодекс"],
	["Codex rescriptus", "Палимпсест (преписани кодекс)"],
	["Coeli lumen", "Светлост неба"],
	["Cogita et visa", "Запажања и мисли"],
	["Cogitationum poenam nemo luit", "Нико не сноси казну за мисли"],
	["Cogito ergo sum", "Мислим, дакле постојим"],
	["Cognata vocabula rebus", "Речи које одговарају стварима"],
	["Cognatio spiritualis", "Духовно сродство"],
	["Coincidentia oppositorum", "Поклапање супротности"],
	["Collegium musicum", "Музичко друштво"],
	["Collegium privatum", "Приватни курс"],
	["Collegium publicum", "Јавно предавање"],
	["Colluvies gentium", "Стеклиште народа"],
	["Columnae Herculis", "Херкулови стубови"],
	["Commentarius perpetuus", "Непрекидни коментар"],
	["Commodum possessionis", "Предност поседа"],
	["Commodum publicum", "Јавна корист"],
	["Commotio cerebri", "По потрес мозга"],
	["Communia bonorum", "Заједница добара"],
	["Communibus annis", "Просечним годинама"],
	["Communis opinio", "Опште мишљење"],
	["Comoedia togata", "Комедија о римском животу"],
	["Compelle intrare", "Натерај их да уђу"],
	["Compesce mentem", "Обуздај свој дух"],
	["Comple promissum", "Испуни обећање"],
	["Compos mentis", "При здравој свести"],
	["Compos sui", "Господар себе"],
	["Conclamatum est", "Све је завршено (проглашено)"],
	["Concordet sermo cum vita", "Нек се речи слажу са животом"],
	["Concordia discors", "Нескладна слога"],
	["Concordia parvae res crescunt, discordia maximae dilabuntur", "Слогом мале ствари расту, неслогом се и највеће распадају"],
	["Conditio sine qua non", "Услов без ког се не може"],
	["Conditio suspensiva", "Одложни услов"],
	["Confessus pro iudicato habetur", "Онај ко призна сматра се осуђеним"],
	["Confiteor solum hoc tibi", "Признајем ово само теби"],
	["Consensus facit nuptias", "Сагласност чини брак"],
	["Consensus gentium", "Слагање народа"],
	["Consensus omnium", "Општа сагласност"],
	["Consequentia non valet", "Закључак није важећи"],
	["Consideratis considerandis", "Узимајући све у обзир"],
	["Consilio manuque", "Саветом и руком"],
	["Consilium abeundi", "Препорука да се оде"],
	["Consortium omnis vitae", "Заједница целог живота"],
	["Consuetudo altera natura", "Навика је друга природа"],
	["Consummatum est!", "Свршено је!"],
	["Consumor aliis inserviendo", "Служећи другима трошим се"],
	["Contra bonos mores", "Противно добрим обичајима"],
	["Contra Gracchos Tiberim habemus", "Против Граха имамо Тибер"],
	["Contra factum non datur argumentum", "Против чињеница нема аргумента"],
	["Contra ius et fas", "Против људског и божанског права"],
	["Contra tabulas", "Противно документима"],
	["Contra rationem", "Противно разуму"],
	["Contraria contrariis curantur", "Супротно се лечи супротним"],
	["Contra spem spero", "Надам се упркос нади"],
	["Contra vim mortis non est medicamen in hortis", "Против смртне силе нема лека у баштама"],
	["Contradictio in adiecto", "Противречност у придоданом"],
	["Contradictio in contrarium", "Противречност са супротним"],
	["Contradictio in re", "Противречност у самој ствари"],
	["Contradictio symptomatum", "Сукоб симптома"],
	["Contraria sunt complementa", "Супротности се допуњују"],
	["Contumacia cumulat poenam", "Непослушност увећава казну"],
	["Coram arbitris", "Пред арбитрима"],
	["Coram hominibus", "Пред људима"],
	["Coram publico", "Јавно (пред народом)"],
	["Cornu copiae", "Рог изобиља"],
	["Corpora non agunt nisi soluta", "Тела не делују осим ако су растворена"],
	["Corpus delicti", "Предмет кривичног дела"],
	["Corpus Domini", "Тело Господње"],
	["Corpus iuris", "Зборник права"],
	["Corpus iuris civilis", "Зборник грађанског права"],
	["Corpus symbioticum", "Симбиотско тело"],
	["Corpus solidum", "Чврсто тело"],
	["Corpus vile", "Безвредно тело"],
	["Correctis, corrigendis, imprimatur", "Након исправки, нека се штампа"],
	["Corruptio optimi pessima", "Изопачење најбољег је најгоре"],
	["Corruptissima re publica plurimae leges", "У најпокваренијој држави има највише закона"],
	["Corvus cornici oculos non eruit", "Врана врани очи не вади"],
	["Crambe repetita", "Подгрејан купус (досадно понављање)"],
	["Crassa ignorantia", "Потпуно незнање"],
	["Crassa Minerva", "Без префињености (прост разум)"],
	["Credo quia absurdum", "Верујем јер је апсурдно"],
	["Credendo vides", "Верујући видиш"],
	["Crescit amor nummi, quantum ipsa pecunia crescit", "Љубав према новцу расте колико расте и сам новац"],
	["Crescite, nos qui vivimus, multiplicamini", "Растите и множите се, ви који живите"],
	["Crimen laesae maiestatis", "Злочин повреде величанства"],
	["Crimine ab uno disce omnes", "По једном злочину упознај све"],
	["Cui bono?", "У чију корист?"],
	["Cui prodest malum?", "Коме користи зло?"],
	["Cuius regio, eius lingua", "Чија је земља, његов је и језик"],
	["Cuius regio, eius religio", "Чија је земља, његова је и вера"],
	["Cuiusvis hominis est errare, nullius nisi insipientis in errore perseverare", "Свако може да погреши, али само лупац уједно у грешци истрајава"],
	["Culpa ficta", "Измишљена кривица"],
	["Culpa in eligendo", "Кривица због погрешног избора"],
	["Culpa in inspiciendo", "Кривица због лошег надзора"],
	["Culpa lata", "Тешка кривица (непажња)"],
	["Culpa lata dolo comparatur", "Тешка непажња се изједначава са намером"],
	["Culpa lata dolo proxima est", "Тешка непажња је најближа намери"],
	["Culpa levis", "Лака кривица"],
	["Culpae poena par esto", "Казна нека буде сразмерна кривици"],
	["Cum commento", "Са коментаром"],
	["Cum Deo", "Са Богом"],
	["Cum eximia laude", "Са највишом похвалом"],
	["Cum figuris", "Са сликама"],
	["Cum grano salis", "Са зрном соли (са резервом)"],
	["Cum hoc non est propter hoc", "Заједно са овим не значи и због овог"],
	["Cum moriar, medium solvar et inter opus", "Кад умрем, нека то буде посред рада"],
	["Cum notis variorum scriptorum", "Са белешкама разних писаца"],
	["Cum principia negante non est disputandum", "Са оним ко пориче основе не треба расправљати"],
	["Cum quodam fastidio", "Са извесним гађењем"],
	["Cum res animum occupavere verba ambiunt", "Када ствари обузму дух, речи долазе саме"],
	["Cum tempore", "Са академијском четврти сата"],
	["Cum tot sustineas et tanta negotia solus", "Кад сам сносиш толике и тако велике послове"],
	["Cum voto consultivo", "Са саветодавним гласом"],
	["Cuncta supercilio moventis", "Све покреће обрвом"],
	["Cunctando restituit rem", "Оклевањем је спасао државу"],
	["Cupiditas rerum novarum", "Жађ за новотаријама"],
	["Cupio omnia, quae vis", "Желим све што желиш"],
	["Cura te ipsum", "Излечи себе самог"],
	["Curae leves loquuntur, ingentes stupent", "Лаке бриге говоре, велике занемљују"],
	["Currente calamo", "Брзим пером"],
	["Curriculum vitae", "Биографија (ток живота)"],
	["Cursus honorum", "Пут напредовања у служби"],
	["Custodia honesta", "Частан притвор"],
	["Custos morum", "Чувар морала"],
	["Cymini sectores", "Цепачи кимина (сипачи длака у јајету)"],
	["Damnant quod non intellegunt", "Осуђују оно што не разумеју"],
	["Damnatio ad bestias", "Бацање пред звери"],
	["Damnatio memoriae", "Брисање из сећања"],
	["Damnatus est", "Осуђен је"],
	["Damnosa quid non imminuit dies?", "Шта све не умањује кобни дан?"],
	["Damnum emergens", "Стварна штета"],
	["Damoclis gladius", "Дамоклов мач"],
	["Timeo Danaos et dona ferentes", "Плашим се Данајаца и када носе поклоне"],
	["Dat census honores", "Богатство доноси части"],
	["Dat, donat, dedicat", "Даје, дарује, посвећује"],
	["Dat veniam corvis, vexat censura columbas", "Ослобађа гавранове, а прогони голубове"],
	["Date obolum Belisario", "Дајте обол Велизару"],
	["De capsula totae", "Све из кутијице (пажљиво дотерано)"],
	["De facto", "Чински (чињенично)"],
	["De iure", "По праву"],
	["De gustibus non est disputandum", "О укусима не вреди расправљати"],
	["De lana caprina rixari", "Свађати се око козје вуне (око тричарија)"],
	["De lege ferenda", "Са становишта закона који треба донети"],
	["De lege lata", "Према важећем закону"],
	["De lingua stulta incommoda multa", "Због глупог језика многе су невоље"],
	["De mari ad mare", "Од мора до мора"],
	["De minimis non curat lex", "Закон се не бави ситницама"],
	["De mortuis aut bene, aut nihil", "О мртвима све најбоље или ништа"],
	["De mortuis et absentibus nihil nisi bene", "О мртвима и одсутнима ништа осим доброг"],
	["De nihilo nihil", "Из ничега ништа не настаје"],
	["De nomine", "По имену"],
	["De novo", "Изнова"],
	["De omni re scibili et quibusdam aliis", "О свему што се може сазнати и о још неким стварима"],
	["De omnibus dubitandum", "У све треба сумњати"],
	["De possibili et impossibili", "О могућем и немогућем"],
	["De principiis non est disputandum", "О принципима се не расправља"],
	["De profundis", "Из дубине"],
	["De quo fabula narratur", "О коме се прича прича"],
	["De rerum natura", "О природи ствари"],
	["De se ipso modifice, de aliis honorifice", "О себи скромно, о другима са поштовањем"],
	["De stercore Ennii", "Из Енијевог ђубришта"],
	["De visu et auditu", "Из виђеног и чувеног"],
	["Decies repetita placebit", "Десет пута поновљено свиђаће се"],
	["Decipimur specie recti", "Заварава нас изглед праведности"],
	["Debellare superbos", "Покорити охоле"],
	["Debes ergo potes", "Мораш, дакле можеш"],
	["Deductio ad absurdum", "Свођење на апсурд"],
	["Definitio fit per genus et differentiam specificam", "Дефиниција се прави помоћу рода и специфичне разлике"],
	["Dei gratia", "Божјом милошћу"],
	["Delegatus non potest delegare", "Делегат не може даље делегирати"],
	["Delicta carnis", "Греси тела"],
	["Delicta facti permanentis", "Дела са трајним последицама"],
	["Delicta facti transeuntis", "Пролазна кривична дела"],
	["Delectabile tempus!", "Угодно време!"],
	["Delictum commissionis", "Дело учињено чињењем"],
	["Delictum communis iuris", "Дело по општем праву"],
	["Delictum omissionis", "Дело учињено нечињењем"],
	["Delirium furens", "Бесно лудило"],
	["Delirium tremens", "Алкохолно лудило (дрхтећи делиријум)"],
	["Dementia praecox", "Рана деменција"],
	["Dementia senilis", "Старачка деменција"],
	["Demonstratio ad oculos", "Очигледан доказ"],
	["Dente lupus, cornu taurus petit", "Вук напада зубом, бик рогом"],
	["Dente superbo", "Охолим зубом"],
	["Dentibus albis", "Белим зубима (насмејано)"],
	["Deo ignoto", "Непознатом Богу"],
	["Deos manes placari victimis humanis", "Умирити подземне богове људским жртвама"],
	["Desideria carnis", "Телесне жеље"],
	["Desine sperare qui hic intras", "Остави сваку наду ти који улазиш"],
	["Desinit in piscem mulier formosa superne", "Лепа жена горе завршава се као риба доле"],
	["Destruam et aedificabo", "Разорићу и саградићу"],
	["Deus conservat omnia", "Бог све чува"],
	["Deus ex machina", "Бог из машине (неочекивано решење)"],
	["Deus magnus et potens, et terribilis", "Бог велики, моћан и страшан"],
	["Deus vult", "Бог тако хоће"],
	["Di meliora", "Богови дали боље"],
	["Diagnosis ex iuvantibus", "Дијагноза на основу тога шта помаже"],
	["Diagnosis ex observatione", "Дијагноза на основу посматрања"],
	["Dicendo de cibis dicendum est de moribus", "Говорећи о храни мора се говорити и о обичајима"],
	["Dicis causa", "Форме ради"],
	["Dicis gratia", "Речи ради"],
	["Dictum factum", "Речено — учињено"],
	["Dictum sapienti sat est", "Мудроме је и реч доста"],
	["Dies diem docet", "Дан дану поука је"],
	["Dies interpellat pro homine", "Рок опомиње уместо човека"],
	["Dies irae", "Дан гнева"],
	["Differentia specifica", "Специфична разлика"],
	["Difficile est proprie communia dicere", "Тешко је опште ствари исказати на оригиналан начин"],
	["Difficile est satyram non scribere", "Тешко је не писати сатиру"],
	["Digitus Dei est hic!", "Овде је прст Божји!"],
	["Dignus est intrare", "Достојан је да уђе"],
	["Dii minorum gentium", "Споредни богови"],
	["Diligentia qualem diligentissimus pater familias adhibet", "Пажња коју примењује најбрижљивији домаћин"],
	["Diligentia quam in rebus suis", "Пажња као у сопственим стварима"],
	["Diluvii testis", "Сведок потопа"],
	["Dimidium animae meae", "Половина моје душе"],
	["Dimidium facti, qui coepit, habet", "Ко је почео, већ је урадио пола посла"],
	["Dira necessitas", "Ужасна нужност"],
	["Dis manibusque sacrum", "Посвећено боговима и сенкама мртвих"],
	["Disiecta membra", "Разбацани удови"],
	["Displicuit nasus tuus", "Не свиђа ми се твој нос"],
	["Diurna manu nocturnaque", "Дању и ноћу"],
	["Divide et impera", "Завади па владај"],
	["Divinum opus sedare dolorem", "Божанско је дело ублажити бол"],
	["Dixi", "Рекао сам"],
	["Dixi et animam levavi", "Рекао сам и олакшао своју душу"],
	["Dixi et animam meam salvavi", "Рекао сам и спасао сопствену душу"],
	["Do manus", "Дајем руке (предајем се)"],
	["Do ut des", "Дајем да би ми дао"],
	["Do ut facias", "Дајем да би учинио"],
	["Docendo discimus", "Подучавајући учимо"],
	["Dolendi modus, timendi non item", "Пати се до границе, али се плаши без границе"],
	["Dolus malus", "Зла намера"],
	["Domi sedet lanam ducit", "Седи код куће и преде вуну"],
	["Domina omnium scientiarum", "Господарица свих наука"],
	["Dominium bonitarium", "Преторска својина"],
	["Dominus et Deus noster sic fieri iubet", "Господар и Бог наш тако заповеда"],
	["Dominus litis", "Господар парнице"],
	["Don gratuit", "Добровољни прилог"],
	["Donec eris felix, multos numerabis amicos", "Док будеш срећан, имаћеш много пријатеља"],
	["Donum didacticum", "Дидактички поклон"],
	["Draco dormiens nunquam titillandus", "Никада не дражи змаја који спава"],
	["Dramatis personae", "Лица у драми"],
	["Duae res longe sunt difficillimae, lexicon scribere et grammaticam", "Две ствари су надалеко најтеже: писати речник и граматику"],
	["Dubia plus torquent mala", "Сумњива зла муче више"],
	["Ducunt volentem fata, nolentem trahunt", "Судбина води оне који то хоће, а вуче оне који неће"],
	["Dulce est desipere in loco", "Слатко је бити луд на правоме месту"],
	["Dulce et decorum est pro patria mori", "Слатко је и часно умрети за отаџбину"],
	["Dulce laudari a laudato viro", "Слатко је када те хвали хваљен човек"],
	["Dulcis fumus patriae", "Сладак је дим отаџбине"],
	["Dum docemus, discimus", "Док подучавамо, учимо"],
	["Dum spiro, spero", "Док дишем, надам се"],
	["Dum vivimus, vivamus", "Док живимо, уживајмо у животу"],
	["Duo cum faciunt idem, non est idem", "Кад двоје раде исто, то није исто"],
	["Duobus certantibus tertius gaudet", "Док се двојица свађају, трећи се радује"],
	["Dura lex, sed lex", "Тврд закон, али закон"],
	["E pluribus unum", "Из многих — једно"],
	["Ea tempestate", "У то доба"],
	["Eadem oberrare chorda", "Грешити на истој жици"],
	["Ecce homo", "Ево човека"],
	["Ecce spectaculum dignum, ad quod respiciat intentus operi suo Deus", "Ево призора достојног да га Бог погледа посвећен свом делу"],
	["Ede, bibe, lude", "Једи, пиј, играј се"],
	["Edictum perpetuum", "Трајни едикт"],
	["Edimus ut vivamus, non vivimus ut edamus", "Једемо да бисмо живели, не живимо да бисмо јели"],
	["Edite, bibite, post mortem nulla voluptas", "Једите, пијте, после смрти нема никаквог уживања"],
	["Effectrix eloquentiae est audientium approbatio", "Поклич слушалаца ствара речитост"],
	["Ego", "Ја"],
	["Ego cogito ergo sum", "Ја мислим, дакле постојим"],
	["Ego sum rex Romanus et supra grammaticos", "Ја сам краљ римски и изнад граматичара"],
	["Ego te intus et in cute novi", "Знам те изнутра и испод коже"],
	["Ego versiculos feci, tulit alter honores", "Ја сам направио стихове, други је покупио заслуге"],
	["Eheu fugaces labuntur anni!", "Авај, пролазе брзе године!"],
	["Ei incumbit probatio, qui dicit, non qui negat", "Терет доказивања је на ономе ко тврди, а не на ономе ко пориче"],
	["Eius est nolle qui potest velle", "Ко има право да жели, има право и да одбије"],
	["Eiusdem farinae", "Из истог брашна"],
	["Eiusdem generis", "Исте врсте"],
	["Elegantia iuris", "Правна елеганција"],
	["Elephanti corio circumtentus est", "Обмотан је слоновом кожом"],
	["Eloquentia canina", "Пасја речитост"],
	["Emere catulum in sacco", "Купити маче у џаку"],
	["Emunctae naris homo", "Човек бистрог ума (оштрог носа)"],
	["Ens a se", "Биће по себи"],
	["Ens causa sui", "Биће узрок самог себе"],
	["Ens cogitans", "Мислеће биће"],
	["Ens rationis", "Разумско биће"],
	["Ens reale", "Стварно биће"],
	["Ens realissimum", "Најстварније биће"],
	["Entia metaphysica", "Метафизичка бића"],
	["Epicuri de grege porcus", "Свиња из Епикуровог стада"],
	["Epistola non erubescit", "Писмо не црвени"],
	["Equo non credite, Teucri", "Не верујте коњу, Тројанци"],
	["Equus Troianus", "Тројански коњ"],
	["Ergo", "Дакле"],
	["Ergo bibamus", "Дакле, пијмо"],
	["Erit sicut cadaver", "Биће попут леша"],
	["Errare humanum est", "Грешити је људски"],
	["Errare humanum est, sed stultum est in errore perseverare", "Грешити је људски, али је глупо у грешци истрајавати"],
	["Eruditio aspera optima est", "Строго образовање је најбоље"],
	["Est avis in dextra, melior quam quattuor extra", "Боље птица у руци него четири ван ње"],
	["Est deus in nobis", "Има божанства у нама"],
	["Est modus in rebus", "Постоји мера у стварима"],
	["Est quaedam flere voluptas", "И плакање је неко уживање"],
	["Esse genus", "Суштина рода"],
	["Esse, vivere, sentire", "Постојати, живети, осећати"],
	["Et alia", "И остало"],
	["Et cetera", "И тако даље"],
	["Et fabula partem veri habet", "И бајка има део истине"],
	["Et fumus patriae dulcis", "И дим отаџбине је сладак"],
	["Et gaudium et solatium in litteris", "У књижевности је и радост и утеха"],
	["Et hoc genus omne", "И цела та врста"],
	["Et in Arcadia ego", "И ја сам био у Аркадији"],
	["Et multa alia", "И много тога другог"],
	["Et tu, Brute?", "Зарем и ти, Бруте?"],
	["Et premitur ratione animus vincique laborat", "Дух се савлађује разумом и труди се да буде побеђен"],
	["Et propter vitam vivendi perdere causas", "И због самог живота изгубити разлоге живљења"],
	["Et quibusdam aliis", "И неким другим"],
	["Et semel emissum volat irrevocabile verbum", "Једном изречена реч лети и не може се вратити"],
	["Etiam periere ruinae", "Чак су и рушевине пропале"],
	["Etiamsi omnes, ego non", "Ако ће и сви, ја нећ"],
	["Eventus docet", "Исход поучава"],
	["Eventus stultorum magister est", "Исход је учитељ будалама"],
	["Ex abrupto", "Изненада (изнебуха)"],
	["Ex adverso", "Са супротне стране"],
	["Ex aequo", "Подједнако"],
	["Ex aequo et bono", "По правичности и добру"],
	["Ex auditu", "По чувењу"],
	["Ex cathedra", "Са катедре (односи се на непорециви ауторитет)"],
	["Exclusa", "Искључено"],
	["Ex mero motu", "Из чисто сопствене побуде"],
	["Exegi monumentum", "Подигао сам споменик"],
	["Ex libris", "Из књига"],
	["Ex nihilo nihil fit", "Ни из чега ништа не настаје"],
	["Ex nunc prout ex tunc", "Од сада као и од тада"],
	["Ex officio", "По службеној дужности"],
	["Ex quo loco?", "Са ког места?"],
	["Ex ungue leonem", "По канџи се познаје лав"],
	["Exceptio probat regulam in casibus non exceptis", "Изузетак потврђује правило у неизузетим случајевима"],
	["Excitare fluctus in simpulo", "Правити буру у чаши воде"],
	["Excudent alii spirantia mollius aera", "Други ће вештије изливати бронзу која дише"],
	["Exempli gratia", "На пример"],
	["Experimentum est optima rerum magistra", "Искуство је најбољи учитељ свих ствари"],
	["Experimentum crucis", "Пресудни експеримент"],
	["Extra omnes!", "Сви напоље!"],
	["Faber est suae quisque fortunae", "Свако је ковач своје среће"],
	["Factum est factum", "Учињено је учињено"],
	["Fac fideli sis fidelis", "Буди веран вернима"],
	["Facta, non verba", "Дела, а не речи"],
	["Fallaces sunt rerum species", "Вараљив је изглед ствари"],
	["Fas est et ab hoste doceri", "Паметно је учити и од непријатеља"],
	["Fatum", "Судбина"],
	["Fallax species rerum", "Обмањујући изглед ствари"],
	["Feci quod potui, faciant meliora potentes", "Урадих шта сам могао, ко може нека уради боље"],
	["Fecit", "Направио је"],
	["Ferox verbis", "Оштар на речима"],
	["Ferro et igni", "Матoм и ватром"],
	["Festina lente", "Жури полако"],
	["Fiat iustitia, et pereat mundus!", "Нек буде правде, па макар свет пропао!"],
	["Fiat lux!", "Нек буде светлост!"],
	["Fiat Roma, et ubi illa nunc est?", "Нека буде Рим, а где је он сада?"],
	["Fidei defensor", "Бранилац вере"],
	["Fidelis et fortis", "Веран и храбар"],
	["Finis coronat opus", "Крај дело краси"],
	["Finis sanctificat media", "Циљ оправдава средства"],
	["Fortes fortuna adiuvat", "Срећа прати храбре"],
	["Forum delicti", "Место учињеног прекршаја"],
	["Fortis imaginatio generat casum", "Јака машта ствара догађај"],
	["Fortuna caeca est", "Срећа је слепа"],
	["Fuimus Troes, fuit Ilium", "Били смо Тројанци, био је Илиј"],
	["Furor Teutonicus", "Теутонски бес"],
	["Furtum manifestum", "Очигледна крађа"],
	["Frustra fit per plura quod potest fieri per pauciora", "Узалуд се ради преко више оно што се може урадити преко мање"],
	["Gaudeamus igitur, iuvenes dum sumus!", "Радујмо се дакле, док смо млади!"],
	["Genius loci", "Дух места"],
	["Gratis", "Бесплатно"],
	["Gratias ago", "Захваљујем"],
	["Gutta cavat lapidem non vi sed saepe cadendo", "Кап дуби камен не снагом већ честим падањем"],
	["Habeas corpus", "Имаш тело (закон о заштити личне слободе)"],
	["Habemus Papam", "Имамо Папу"],
	["Hannibal ante portas", "Ханибал је пред вратима"],
	["Hic bibitur", "Овде се пије"],
	["Heu quam est timendus qui mori tutus putat", "Авај, како је страшан онај коме је смрт сигурно уточиште"],
	["Hic locus est ubi mors gaudet succurrere vitae", "Ово је место где се смрт радује да помогне животу"],
	["Hic et nunc", "Овде и сада"],
	["Hic portus salutis", "Ово је лука спасења"],
	["Hic Rhodus, hic salta", "Овде је Родос, овде скочи"],
	["Hic sunt dracones", "Овде су змајеви"],
	["Hic sunt leones", "Овде су лавови"],
	["Hoc fac et vinces", "Уради ово и победићеш"],
	["Hoc volo, sic iubeo, sit pro ratione voluntas", "То хоћу, тако наређујем, уместо разлога нека буде моја воља"],
	["Hodie mihi, cras tibi", "Данас мени, сутра теби"],
	["Homo homini lupus est", "Човек је човеку вук"],
	["Homo proponit, sed Deus disponit", "Човек планира, а Бог одређује"],
	["Homo Sapiens non urinat in ventum", "Разуман човек не мокри уз ветар"],
	["Homo sum, humani nihil a me alienum puto", "Човек сам и ништа људско ми није страно"],
	["Honores mutant mores, sed raro in meliores", "Почасти мењају обичаје, али ретко на боље"],
	["Honoris causa", "Ради части (почасни)"],
	["Horribile dictu", "Страшно за рећи"],
	["Humanum errare est", "Људски је грешити"],
	["Ibi semper est victoria, ubi concordia est", "Тамо је увек победа где је слога"],
	["Ibi victoria, ubi concordia", "Тамо је победа где је слога"],
	["Ibidem", "На истом месту"],
	["Idem per idem", "Исто помоћу истог"],
	["Id est", "То јест"],
	["In bono veritas", "У доброти је истина"],
	["Iesus Nazarenus, Rex Iudaeorum", "Исус Назарећанин, Краљ Јевреја"],
	["Igni et ferro", "Ватром и мачем"],
	["Ignoramus et ignorabimus", "Не знамо и нећемо знати"],
	["Ignorantia non excusat", "Незнање не оправдава"],
	["Ignoratio elenchi", "Непознавање питања о ком се расправља"],
	["Ignorantia non est argumentum", "Незнање није аргумент"],
	["Imago animi vultus est", "Лице је слика душе"],
	["Imperare sibi maximum imperium est", "Владати собом највећа је власт"],
	["Imperatorem stantem mori oportet", "Цар треба да умре стојећи"],
	["In absentia", "У одсутности"],
	["In angustiis amici apparent", "У невољи се познају пријатељи"],
	["In articulo mortis", "У моменту смрти"],
	["In camera", "Иза затворених врата (у приватности)"],
	["In coena Domini", "На тајној вечери"],
	["In contumaciam", "У супоредност (због недоласка)"],
	["In corpore", "У пуном саставу (у целини)"],
	["Indignus qui inter mala verba", "Недостојан онај који користи ружне речи"],
	["In dubio pro reo", "У сумњи у корист оптуженог"],
	["In flagrante delicto", "На делу (у затеченом злочину)"],
	["In foro scientiae", "Пред судом науке"],
	["Ingenium mala saepe movent", "Невоље често подстичу дух"],
	["In infinitum", "У бесконачност"],
	["In hoc signo vinces", "У овом знаку ћеш победити"],
	["Iniuria realis", "Фраза за стварну правну повреду/напад"],
	["Iniuria verbalis", "Вербална увреда"],
	["Iniuriam facilius facias quam feras", "Лакше је нанети увреду него је претрпети"],
	["In memoriam", "У сећање"],
	["In nomine Patris, et Filii, et Spiritus Sancti", "У име Оца и Сина и Светога Духа"],
	["Innocens credit omni verbo", "Наиван верује у сваку реч"],
	["In partem salarii", "У рачун плате"],
	["In perpetuum", "Завек"],
	["In principio erat verbum", "У почетку беше реч"],
	["In propria persona", "Лично"],
	["In propria causa nemo iudex", "Нико није судија у сопственој ствари"],
	["In rerum natura", "У природи ствари"],
	["In saecula saeculorum", "У векове векова"],
	["In silico", "У рачунару (симулирано)"],
	["In situ", "На месту догађаја"],
	["Inter alia", "Између осталог"],
	["Inter arma enim silent leges", "У рату закони ћуте"],
	["Inter arma silent Musae", "У рату ћуте музе"],
	["Interdum lacrimae pondera vocis habent", "Каткад сузе имају тежину гласа"],
	["In utero", "У материци"],
	["In vacuo", "У вакууму"],
	["Invia est in medicina via sine lingua Latina", "Непроходан је пут у медицини без латинског језика"],
	["Invia virtuti nulla est via", "За врлину нема непроходног пута"],
	["In vino veritas", "У вину је истина"],
	["Inutile terrae pondus", "Бескористан терет земљи"],
	["Ipsa se velocitas implicat", "Сама брзина себе спутава"],
	["In vitro", "У епрувети"],
	["In vivo", "На живом организму"],
	["Ipse dixit", "Сам је рекао"],
	["Ipso facto", "Самoм чињеницом"],
	["Iura novit curia", "Суд познаје законе"],
	["Ira furor brevis est", "Гнев је кратко лудило"],
	["Ira odium generat, concordia nutrit amorem", "Гнев рађа мржњу, слога храни љубав"],
	["Irreparabilium felix oblivio rerum", "Срећан је онај ко заборавља оно што се не може поправити"],
	["Is fecit cui prodest", "Урадио је онај коме користи"],
	["Iamque opus exegi quod nec Iovis ira, nec ignis, nec poterit ferrum, nec edax abolere vetustas", "И већ заврших дело које ни гнев Јупитеров, ни ватра, ни мач, ни прождрљива старост неће моћи уништити"],
	["Iudex damnatur, cum nocens absolvitur", "Судија се осуђује када се кривац ослободи"],
	["Iuris praecepta sunt haec: honeste vivere, alterum non laedere, suum cuique tribuere", "Правила права су ова: поштено живети, другог не вређати, свакоме своје дати"],
	["Ius primae noctis", "Право Прве ноћи"],
	["Ius primae occupationis", "Право прве заузетости"],
	["Ius sanguinis", "Право крви"],
	["Ius soli", "Право тла"],
	["Ius vitae ac necis", "Право на живот и смрт"],
	["Iustitia regnorum fundamentum", "Правда је основ свих краљевстава"],
	["Iustum et tenacem propositi virum", "Праведног човека који је истрајан у својој намере"],
	["Labor omnia vincit", "Рад све побеђује"],
	["Labor est etiam ipse voluptas", "Сам рад је такође задовољство"],
	["Lassata viris necdum satiata recessit", "Уморна од мушкараца али још незадовољена отишла је"],
	["Laborare est orare", "Радити значи молити се"],
	["Lectori benevolo salutem", "Поздрав добронамерном читаоцу"],
	["Legum servi sumus ut liberi esse possimus", "Слуге смо закона да бисмо могли бити слободни"],
	["Letum non omnia finit", "Смрт не завршава све"],
	["Legio nomen mihi est", "Легион ми је име"],
	["Levis est labor omnis amanti", "Лаган је сваки рад ономе ко воли"],
	["Lex specialis derogat generali", "Посебни закон укида општи"],
	["Lex posterior derogat legi priori", "Каснији закон укида претходни"],
	["Lex superior derogat legi inferiori", "Виши закон укида нижи"],
	["Lex talionis", "Закон одмазде (око за око)"],
	["Liberum veto", "Слободно вето"],
	["Libro ultimo", "У последњој књизи"],
	["Licentia poetica", "Песничка слобода"],
	["Littera scripta manet", "Написана реч остаје"],
	["Litterae humaniores", "Хуманистичке науке"],
	["Locus regit actum", "Место одређује правни чин"],
	["Lorem ipsum", "Текст за попуњавање у штампи"],
	["Longa manus calami", "Дуга рука пера"],
	["Lege artis", "По правилима струке"],
	["Lucri bonus est odor ex re qualibet", "Мирис добити је добар ма од чега долазио"],
	["Lupus in fabula", "Ми о вуку, а вук на врата"],
	["Lupus non mordet lupum", "Вук не уједа вука"],
	["Lupus pilum mutat, non mentem", "Вук длаку мења, али ћуд никако"],
	["Lux in tenebris", "Светлост у тами"],
	["Lux ex tenebris", "Светлост из таме"],
	["Magni nominis umbra", "Сенка великог имена"],
	["Magnum opus", "Велико дело"],
	["Mala fides", "Зла вера"],
	["Malum discordiae", "Јабука раздора"],
	["Malum se ipsum devorat", "Зло прождире само себе"],
	["Manifestum non eget probatione", "Очигледно не треба доказивати"],
	["Maniae infinitae sunt species", "Врсте лудила су бесконачне"],
	["Manus manum lavat", "Рука руку мије"],
	["Margaritas ante porcos", "Бисере пред свиње"],
	["Matrimonium iustum", "Законити брак"],
	["Mea culpa", "Мој грех"],
	["Mea virtute me involvo", "Обијам се својом врлином"],
	["Medica mente non medicamentis", "Лечи умом, а не лековима"],
	["Medicus curat, natura sanat", "Лекар лечи, природа исцељује"],
	["Medius terminus", "Средњи термин"],
	["Memento mori", "Сети се да си смртан"],
	["Memento vivere", "Сети се да живиш"],
	["Memento quia pulvis es", "Сети се да си прах"],
	["Mens sana in corpore sano", "У здравом телу здрав дух"],
	["Metri causa", "Ради метрике"],
	["Metus, dolor, mors ac formidines", "Страх, бол, смрт и ужаси"],
	["Misericordia infirma", "Слабо милосрђе"],
	["Modus operandi", "Начин рада"],
	["Modus vivendi", "Начин живота (споразум о суживоту)"],
	["More maiorum", "По обичају предака"],
	["Mortem effugere nemo potest", "Нико не може побећи од смрти"],
	["Multum vinum bibere non diu vivere", "Пити много вина значи не живети дуго"],
	["Multi multa, nemo omnia novit", "Многи знају много тога, али нико све"],
	["Multa paucis", "Много у мало речи"],
	["Mutatis mutandis", "Уз неопходне измене"],
	["Nam vitiis nemo sine nascitur", "Јер нико се не рађа без мана"],
	["Natura abhorret vacuum", "Природа се гнуша празнине"],
	["Naturalia non sunt turpia", "Оно што је природно није срамотно"],
	["Navigare necesse est, vivere non est necesse", "Пловити се мора, живети се не мора"],
	["Naviget, haec summa est", "Нека плови, то је све"],
	["Nec gemino bellum Troianum orditur ab ovo", "И не почиње тројански рат од двоструког јајета"],
	["Nec nostri saeculi est", "То није одлика нашег доба"],
	["Nec Deus intersit", "Нек се Бог не уплиће"],
	["Nec pluribus impar", "И за многе једнак"],
	["Nec sutor ultra crepidam", "Обућар нека не иде даље од ципеле"],
	["Nemo debet bis puniri pro uno delicto", "Нико не треба двапут да буде кажњен за исти прекршај"],
	["Nemo debet esse iudex in propria causa", "Нико не треба да буде судија у сопственој ствари"],
	["Nemo me impune lacessit", "Нико ме не провоцира некажњено"],
	["Nemo omnia potest scire", "Нико не може да зна све"],
	["Nemo solus satis sapit", "Нико сам није довољно мудар"],
	["Ne sutor supra crepidam", "Обућар нека се не меша изнад ципела"],
	["Nihil admirari", "Ничему се не чудити"],
	["Nihil habeo, nihil timeo", "Ништа немам, ничег се не плашим"],
	["Nihil habeo, nihil curo", "Ништа немам, ни за шта не бринем"],
	["Nihil habenti nihil deest", "Ономе ко нема ништа ништа не недостаје"],
	["Nil aliud scit necessitas quam vincere", "Нужност не зна ни за шта друго осим за победу"],
	["Nil inultum remanebit", "Ништа неће остати неосвећено"],
	["Nil sancti", "Ништа није свето"],
	["Nil satis nisi optimum", "Само најбоље је довољно добро"],
	["Nolens volens", "Хтео — не хтео"],
	["Nomen est omen", "Име је знак"],
	["Nomen nescio", "Име ми није познато"],
	["Nomina sunt odiosa", "Имена су мрска (не треба именовати)"],
	["Non bis in idem", "Не двапут о истом"],
	["Non curatur, qui curat", "Не лечи се онај ко брине"],
	["Non est necesse ut omnis qui clamat et inquietat beatos dicat", "Није потребно да свако ко виче каже да је срећан"],
	["Non moritura", "Оно што неће умрети"],
	["Non olet", "Не мирише (новац не мирише)"],
	["Non plus ultra", "Не даље (врхунац)"],
	["Non progredi est regredi", "Не напредовати значи назадовати"],
	["Non rex est lex, sed lex est rex", "Краљ није закон, већ је закон краљ"],
	["Non scholae, sed vitae discimus", "Не учимо за школу, већ за живот"],
	["Non tam praeclarum est scire Latine, quam turpe nescire", "Није толико дивно знати латински, колико је срамотно не знати га"],
	["Non vi, sed arte", "Не снагом, већ вештином"],
	["Nosce te ipsum", "Упознај самог себе"],
	["Nota bene", "Забележи добро"],
	["Novus ordo seclorum", "Нови поредак векова"],
	["Nullum crimen sine poena, nulla poena sine lege, nullum crimen sine poena legali", "Нема злочина без казне, нема казне без закона, нема злочина без законске казне"],
	["Nusquam est qui ubique est", "Нигде није онај ко је свуда"],
	["Occasio receptus difficiles habet", "Прилика има тешке одступнице"],
	["Oderint, dum metuant", "Нек ме мрзе, само нека ме се плаше"],
	["Odi et amo", "Мрзим и волим"],
	["Omissa spe qui huc intrasti", "Остави сваку наду ти који улазиш"],
	["Omnia homini, dum vivit, speranda sunt", "Човек треба свему да се нада док је жив"],
	["Omne vivum ex ovo", "Све живо потиче из јајета"],
	["Omnes una manet nox", "Све нас чека једна ноћ"],
	["Omnes vulnerant, ultima necat", "Сви сати рањавају, последњи убија"],
	["Omnia mea mecum porto", "Све своје са собом носим"],
	["Omnia mutantur, nihil interit", "Све се мења, ништа не нестаје"],
	["Omnia orta cadunt", "Све што је настало — пропада"],
	["Omnia praeclara rara", "Све што је дивно — ретко је"],
	["Omnia vincit amor et nos cedamus amori", "Љубав све побеђује, предајмо се и ми љубави"],
	["Omnis homo mendax", "Сваки човек је лажов"],
	["Omnis ars imitatio est naturae", "Свака уметност је имитација природе"],
	["Omnium consensu", "Слагањем свих"],
	["Ora et labora", "Моли се и ради"],
	["Orbis terrarum", "Земаљска кугла"],
	["Ordo ab chao", "Ред из хаоса"],
	["O sancta simplicitas", "О, света простото"],
	["O tempora, o mores!", "О времена, о обичаји!"],
	["Otia dant vitia", "Беспосличарење рађа пороке"],
	["Otium post negotium", "Одмор после посла"],
	["Pacta sunt servanda", "Уговори се морају поштовати"],
	["Panem et circenses", "Хлеба и игара"],
	["Pater noster", "Оче наш"],
	["Pax optima rerum est", "Мир је најбоља ствар"],
	["Pax mundi", "Мир света"],
	["Pecunia non olet", "Новац не мирише"],
	["Pecuniae oboediunt omnia", "Све се покорава новцу"],
	["Per angusta ad augusta", "Кроз трње до звезда (кроз тешкоће до узвишеног)"],
	["Per aspera ad astra", "Кроз трње до звезда"],
	["Per definitionem", "По дефиницији"],
	["Per Iovem", "Тако ми Јупитера"],
	["Periculum in mora", "Опасност је у кашњењу"],
	["Perpetuum mobile", "Непрекидно кретање"],
	["Per se", "Сам по себи"],
	["Persona grata", "Пожељна особа"],
	["Persona non grata", "Непожељна особа"],
	["Persona suspecta", "Сумњива особа"],
	["Personae dramatis", "Лица у драми"],
	["Pes sic tendatur ne lodix protereatur", "Пружај ногу колико ти је покривач дуг"],
	["Petitio principii", "Захтевање спора (претпостављање доказа)"],
	["Pictoribus atque poetis", "Сликарима и песницима"],
	["Pie Iesu Domine, dona eis requiem", "Благословени Господе Исусе, даруј им мир"],
	["Plus ultra", "Још даље"],
	["Poema", "Песма"],
	["Poetae nascuntur, oratores fiunt", "Песници се рађају, беседници постају"],
	["Porta itineri longissima", "Капија је најдужи део пута"],
	["Post coitum omne animal triste est", "После коитуса свака је животиња тужна"],
	["Post factum", "После чина"],
	["Post hoc ergo propter hoc", "После овог, дакле због овог"],
	["Post hoc non est propter hoc", "После овог не значи и због овог"],
	["Post mortem", "После смрти"],
	["Post prandium stabis, post cenam ambulabis", "После ручка стој, после вечере шетај"],
	["Post scriptum", "После написаног"],
	["Post tenebras lux", "После таме — светлост"],
	["Potius sero quam nunquam", "Боље икад него никад"],
	["Praemonitus, praemunitus", "Ко је упозорен, тај је и наоружан"],
	["Primo", "Прво"],
	["Primum non nocere", "Пре свега — не штетити"],
	["Primus inter pares", "Први међу једнакима"],
	["Pro forma", "Форме ради"],
	["Pro pace", "За мир"],
	["Pro patria mori", "Умрети за отаџбину"],
	["Pro poena", "За казну"],
	["Pro tempore", "Привремено"],
	["Probatio minus plena", "Непотпун доказ"],
	["Probatum est", "Доказано је"],
	["Procul negotiis", "Далеко од послова"],
	["Qua definitione", "По којој дефиницији"],
	["Quae medicamenta non sanat, ferrum sanat; quae ferrum non sanat, ignis sanat; quae vero ignis non sanat, insanabilia reputari oportet", "Што лекови не излече, челик лечи; што челик не излечи, ватра лечи; што ватра не излечи, сматра се неизлечивим"],
	["Qualis artifex pereo!", "Какав уметник у мени умире!"],
	["Quantum satis", "Колико је довољно"],
	["Qui nimium probat, nihil probat", "Ко сувише доказује, ништа не доказује"],
	["Qui non laborat, non manducet", "Ко не ради, нека и не једе"],
	["Qui non proficit, deficit", "Ко не напредује, назадује"],
	["Qui pro quo", "Замена (један уместо другог)"],
	["Qui scribit, bis legit", "Ко пише, двапут чита"],
	["Qui seminat mala, metet mala", "Ко сеје зло, жење зло"],
	["Qui sine peccato est?", "Ко је без греха?"],
	["Qui ventum seminat, turbinem metet", "Ко сеје ветар, пожњеће олују"],
	["Quid dubitas, ne feceris", "У шта сумњаш, то не чини"],
	["Quid est veritas?", "Шта је истина?"],
	["Quid pro quo", "Услуга за услугу"],
	["Quid timeas? Caesarem vehis Caesarisque fortunam", "Чега се плашиш? Носиш Цезара и Цезарову срећу"],
	["Quis? Quid? Ubi? Quibus auxiliis? Cur? Quomodo? Quando?", "Ко? Шта? Где? Чиме? Зашто? Како? Када?"],
	["Quis custodiet ipsos custodes?", "Ко ће чувати саме чуваре?"],
	["Quo tendis?", "Куда се упућујеш?"],
	["Quo vadis?", "Куда идеш?"],
	["Quod Deus bene vertat", "Нек Бог то окрене на добро"],
	["Quod erat demonstrandum", "Што је и требало доказати"],
	["Quod fert fortuna, fer!", "Што носи срећа, подноси!"],
	["Quod gratis asseritur, gratis negatur", "Што се тврди без доказа, одбија се без доказа"],
	["Quod licet Iovi, non licet bovi", "Што је дозвољено Јупитеру, није дозвољено волу"],
	["Quod scripsi, scripsi", "Што сам написао, написао сам"],
	["Quot capita, tot sententiae", "Колико глава, толико мишљења"],
	["Quo usque pro Roma ibis?", "Колико далеко ћеш ићи за Рим?"],
	["Radices litterarum amarae sunt, fructus dulces", "Корени наука су горки, али су плодови слатки"],
	["Rara est concordia formae atque pudicitiae", "Ретка је слога између лепоте и чедности"],
	["Rebus sic stantibus", "Док ствари тако стоје"],
	["Rectus", "Право (исправно)"],
	["Reddite quae sunt Caesaris Caesari, et quae sunt Dei Deo", "Вратите Цезару Цезарево, а Богу Божје"],
	["Reductio ad absurdum", "Свођење на апсурд"],
	["Regula certa datur: bene qui stat, non moveatur", "Дато је сигурно правило: ко добро стоји, нека се не помера"],
	["Repetitio est mater studiorum", "Понављање је мајка знања"],
	["Requiescat in pace", "Почивао у миру"],
	["Requiem aeternam dona eis, Domine", "Даруј им вечни мир, Господе"],
	["Res Publica", "Јавна ствар (Држава)"],
	["Respice finem", "Мисли на крај"],
	["Respondeat superior", "Нека одговара надређени"],
	["Reti ventos venari", "Ловити ветар мрежом"],
	["Rex regnat, sed non gubernat", "Краљ влада, али не управља"],
	["Roma invicta", "Непобедиви Рим"],
	["Roma locuta, causa finita", "Рим је рекао свое, случај је закључен"],
	["Roma traditoribus non praemia", "Рим не награђује издајнике"],
	["Salus populi suprema lex", "Добробит народа је највиши закон"],
	["Sancta sanctorum", "Светиња над светињама"],
	["Sapere aude", "Усуди се да будеш мудар"],
	["Sapienti sat", "Мудроме доста"],
	["Scientia potentia est", "Знање је моћ"],
	["Scire leges non hoc est verba earum tenere, sed vim ac potestatem", "Познавати законе не значи памтити њихове речи, већ разумети њихову суштину и моћ"],
	["Secundo", "Друго"],
	["Sed alia tempora", "Али друга су времена"],
	["Sed semel insanivimus omnes", "Али сви смо ми једном били луди"],
	["Sede Vacante", "Док је престо празан"],
	["Sedia Gestatoria", "Носила за папу"],
	["Sed non quoad hanc", "Али не што се тиче ове"],
	["Semper idem", "Увек исто"],
	["Semper in motu", "Увек у кретању"],
	["Semper fidelis", "Увек веран"],
	["Senatus bestia, senatores boni viri", "Сенат је звер, а сенатори су добри људи"],
	["Senatus Populusque Romanus", "Сенат и народ римски"],
	["Sententia absolutoria", "Ослобађајућа пресуда"],
	["Sero venientibus ossa", "Онима који касно долазе — кости"],
	["Serva me, servabo te", "Спаси ти мене, спасићу ја тебе"],
	["Servus Servorum Dei", "Sluga slugu Božjih"],
	["Si parva licet componere magnis", "Ако се мало може поредити са великим"],
	["Si vales, bene est; ego valeo", "Ако си здрав, добро је; и ја сам здрав"],
	["Si vis amari, ama!", "Ако хоћеш да будеш вољен, воли!"],
	["Si vis pacem, para bellum", "Ако хоћеш мир, спремај рат"],
	["Si vis vincere, disce pati", "Ако хоћеш да победиш, научи да трпиш"],
	["Sic!", "Управо тако!"],
	["Sic itur ad astra", "Тако се иде до звезда"],
	["Sic transit gloria mundi", "Тако пролази слава света"],
	["Sic semper tyrannis", "Тако увек тиранима"],
	["Sic volo, sic iubeo!", "Тако хоћу, тако наређујем!"],
	["Silentium est aurum", "Ћутање је злато"],
	["Silentium videtur confessio", "Ћутање изгледа као признање"],
	["Similia similibus curantur", "Слично се лечи сличним"],
	["Sine causa", "Без разлога"],
	["Sine cura", "Без бриге (синекура)"],
	["Sine ira et studio", "Без гнева и наклоности"],
	["Sit tibi terra levis", "Нека ти је лака земља"],
	["Sitio", "Жедан сам"],
	["Sola Scriptura", "Само Писмо"],
	["Soli Deo gloria", "Само Богу слава"],
	["Sol lucet omnibus", "Сунце сија свима"],
	["Solum debiles mori debent", "Само слаби треба да умру"],
	["Solus cum sola, in loco remoto, non cogitabuntur orare «Pater noster»", "Мушкарац сам са женом на скровитом месту неће мислити да моли «Оче наш»"],
	["Status quo", "Трентуно стање"],
	["Status quo ante bellum", "Стање какво је било пре рата"],
	["Sub rosa", "Под ружом (у тајности)"],
	["Sub specie aeternitatis", "Са становишта вечности"],
	["Sudore et sanguine", "Знојем и крвљу"],
	["Sui generis", "Својеврстан (посебне врсте)"],
	["Suis quaeque temporibus", "Све у своје време"],
	["Summa summarum", "Све у свему (коначни збир)"],
	["Supra nos Fortuna negotia curat", "Изнад нас Судбина води послове"],
	["Supremum vale", "Последње збогом"],
	["Sursum corda", "Горе срца"],
	["Suum cuique", "Свакоме своје"],
	["Tabula rasa", "Празна табла"],
	["Tacito consensu", "Прећутним слагањем"],
	["Tale quale", "Кaкво јесте"],
	["Te amo est verum", "Истина је да те волим"],
	["Tempora mutantur et nos mutamur in illis", "Времена се мењају и ми се мењамо са њима"],
	["Tempus edax rerum", "Време које све прождире"],
	["Tempus fugit", "Време лети"],
	["Tempora labuntur, tacitisque senescimus annis", "Времена пролазе, а ми старимо у неосетним годинама"],
	["Tertium non datur", "Трећег нема"],
	["Terra incognita", "Непозната земља"],
	["Terra nullius", "Ничија земља"],
	["Terminus post quem", "Рок после кога"],
	["Testis unus, testis nullus", "Један сведок — ниједан сведок"],
	["Timeo Danaos et dona ferentes", "Плашим се Данајаца и када носе поклоне"],
	["Toties quoties", "Колико пута... толико пута..."],
	["Totum revolutum", "Потпуна збрка"],
	["Totus floreo", "Цветам у потпуности"],
	["Trahit sua quemque voluptas", "Сваког вуче његова страст"],
	["Tres faciunt collegium", "Троје чине друштво"],
	["Tres mulieres faciunt nundinas", "Три жене чине пијацу"],
	["Ubi bene, ibi patria", "Где је добро, ту је отаџбина"],
	["Ubi concordia, ibi victoria", "Где је слога, ту је победа"],
	["Ubi culpa est, ibi poena subesse debet", "Где је кривица, ту треба да буде и казна"],
	["Ubi nil vales, ibi nil velis", "Где ништа не можеш, ту ништа не жели"],
	["Ubi mel, ibi apes", "Где је мед, ту су и пчеле"],
	["Ubi mel, ibi fel", "Где је мед, ту је и жут"],
	["Ubi pus, ibi incisio", "Где је гној, ту је рез"],
	["Ultima ratio", "Последње средство"],
	["Ultra posse nemo obligatur", "Преко могућности нико није обавезан"],
	["Una voce", "Једногласно"],
	["Unde venis?", "Одакле долазиш?"],
	["Unum et idem", "Једно те исто"],
	["Unus pro omnibus, omnes pro uno", "Један за све, сви за једног"],
	["Urbi et Orbi", "Граду (Риму) и свету"],
	["Usus est optimus magister", "Искуство је најбољи учитељ"],
	["Utile dulce miscere", "Спојити корисно са пријатним"],
	["Ut tensio sic vis", "Колико је истезање, толика је и сила"],
	["Ut desint vires, tamen est laudanda voluntas", "Иако недостаје снага, ипак треба похвалити вољу"],
	["Uti, non abuti", "Користити, а не злоупотребљавати"],
	["Vale", "Збогом"],
	["Vade retro, Satana", "Одлази од мене, Сатано"],
	["Vae victis", "Тешко побеђенима"],
	["Vanitas vanitatum et omnia vanitas", "Таштина над таштинама и све је таштина"],
	["Varietas delectat", "Разноликост чини задовољство"],
	["Veni, vidi, vici", "Дођох, видех, победих"],
	["Verba magistri", "Учитељеве речи"],
	["Verba volant, scripta manent", "Речи лете, написано остаје"],
	["Verbatim", "Реч по реч"],
	["Verte", "Окрени страну"],
	["Verum est quod pro salute fit mendacium", "Истинита је она лаж која се каже ради спасења"],
	["Veto", "Забрањујем"],
	["Versus", "Против"],
	["Via est vita", "Пут је живот"],
	["Viam supervadet vadens", "Пут ће прећи онај ко иде"],
	["Vice versa", "Обрнуто"],
	["Videlicet", "То јест (очигледно)"],
	["Videre maius quiddam", "Видети нешто веће"],
	["Vince in bono malum", "Победи зло добрим"],
	["Vinum memoriae mors", "Вино је смрт за памћење"],
	["Vinum verba ministrat", "Вино подстиче речи"],
	["Viribus unitis", "Заједничким снагама"],
	["Vis unita fortior", "Уједињена снага је јача"],
	["Vita brevis, ars longa", "Живот је кратак, уметност дуга"],
	["Vita sine libertate, nihil", "Живот без слободе је ништа"],
	["Vita sine litteris mors est", "Живот без науке је смрт"],
	["Vitae sal amicitia", "Пријатељство је со живота"],
	["Vivenda", "Оно што треба проживети"],
	["Vivere est cogitare", "Живети значи мислити"],
	["Vi veri universum vivus vici", "Снагом истине сам за живота освојио свемир"],
	["Volens nolens", "Хтео — не хтео"],
	["Volo ergo sum", "Желим, дакле постојим"],
	["Volo, non valeo", "Хоћу, али не могу"],
	["Votum separatum", "Издвојено мишљење"],
	["Vox populi, vox Dei", "Глас народа је глас Божји"]
];

/* Game */

const youWon = "Победили сте!";
const youLost = "Изгубили сте!";
let tip = ".";

let audio_yes = new Audio("yes.mp3");
let audio_no = new Audio("no.mp3");
let audio_win = new Audio("win.mp3");
let audio_los = new Audio("los.mp3");

let score = parseInt(localStorage.getItem('hangman_score')) || 0;

function Game()
{
    let index = Math.floor(Math.random() * words.length);
    let word = words[index][0];
    tip = words[index][1];
    word = word.toUpperCase();
    let guessedLetters = [];
    let maskedWord = "";
    let incorrectGuesses = 0;
    
    // Алфавит остаётся классической латынью
    const allLetters = 'ABCDEFGHILMNOPQRSTUVXYZ';
    let won = false;
    let lost = false;
    let scoreUpdated = false;
    const maxGuesses = 7;

    for ( let i = 0; i < word.length; i++ )
    {
        let nextCharacter = word.charAt(i);
        let charCode = nextCharacter.charCodeAt(0);
        let A = 65;
        let Z = 90;
        if( A <= charCode && charCode <= Z )
        {
            nextCharacter = "_";
        }
        maskedWord += nextCharacter;
    }

    let guess = function( letter )
    {
        letter = letter.toUpperCase();
        if( !guessedLetters.includes( letter ) && !won && !lost )
        {   
            guessedLetters.push(letter);
            
            if( word.includes( letter ) )
            {
                let matchingIndexes = [];
                for ( let i = 0; i < word.length; i++ ) 
                {
                    if( word.charAt(i) === letter )
                    {
                        matchingIndexes.push( i );
                    }
                }

                matchingIndexes.forEach( function(index) {
                    maskedWord = replace( maskedWord, index, letter );
                }); 

                won = maskedWord === word;
                
                if(won) {
                    maskedWord = word;
                    if(!scoreUpdated) {
                        score += 1;
                        localStorage.setItem('hangman_score', score);
                        scoreUpdated = true;
                    }
                    audio_win.play().catch(() => {});
                } else {
                    audio_yes.play().catch(() => {});
                }
            }
            else
            {
                handleIncorrectGuess();
            }
        }
    }

    let handleIncorrectGuess = function()
    {
        incorrectGuesses++;
        lost = incorrectGuesses >= maxGuesses;
        if( lost )
        {
            maskedWord = word;
			if(!scoreUpdated) {
                score = Math.max(0, score - 1);
                localStorage.setItem('hangman_score', score);
                scoreUpdated = true;
            }
            audio_los.play().catch(() => {});
        }
        else
        {
            audio_no.play().catch(() => {});
        }
    }

    return {
        "getWord": function(){ return word; },
        "getMaskedWord": function(){ return maskedWord; },
        "guess": guess,
        "getAllLetters": function(){ return [...allLetters]; },
        "getGuessedLetters": function(){ return guessedLetters; },
        "getIncorrectGuesses": function(){ return incorrectGuesses; },
        "isWon": function(){ return won; },
        "isLost": function(){ return lost; }
    };
}

function replace( value, index, replacement ) 
{
    return value.substring(0, index) + replacement + value.substring(index + replacement.length);
}

function listenForInput( game ) 
{
    let guessLetter = function( letter )
    {
        if( letter && game.getAllLetters().includes(letter) )
        {
            let gameStillGoing = !game.isWon() && !game.isLost();
            if( gameStillGoing )
            {
                game.guess( letter );
                render( game );
            }
        }
    };

    let handleClick = function( event )
    {
        if (event.target.classList.contains('guess') && !event.target.classList.contains('disabled'))
        {
            guessLetter( event.target.innerHTML.trim() );
        }
    }

    let handleKeyPress = function( event )
    {
        let letter = null;
        const A = 65;
        const Z = 90;
        const ENTER = 13;
        let isLetter = event.keyCode >= A && event.keyCode <= Z;
        let newGameButton = document.getElementById("newGameButton");
        let gameOver = game.isWon() || game.isLost();

        if( isLetter )
        {
            letter = String.fromCharCode( event.keyCode );
        }
        else if( event.keyCode === ENTER && gameOver )
        {
            newGameButton.click();
        }
        guessLetter( letter );
    }

    document.addEventListener('keydown', handleKeyPress );
    document.body.addEventListener('click', handleClick );
}

function render( game )
{
    document.getElementById("word").innerHTML = game.getMaskedWord(); 
    
    document.getElementById("scoreValue").textContent = score;
    
    let guessesContainer = document.getElementById("guesses");
    guessesContainer.innerHTML = "";
    
    let guessedLetters = game.getGuessedLetters();
    
    game.getAllLetters().forEach( function(letter) {
        let isGuessed = guessedLetters.includes(letter);
        let disabledClass = isGuessed ? " disabled" : "";
        
        let innerHtml = "<span class='guess" + disabledClass + "'>" + letter + "</span>";
        guessesContainer.innerHTML += innerHtml;
    });
    
    document.getElementById("hangmanImage").src = "img/hangman" + game.getIncorrectGuesses() + ".png";

    let tipBox = document.getElementById('tipBox');
    
    if( game.isWon() )
    {
        tipBox.textContent = youWon + " " + tip;
        tipBox.className = "win";
    }
    else if( game.isLost() )
    {
        tipBox.textContent = youLost + " " + tip;
        tipBox.className = "loss";
    }
    else
    {
        tipBox.textContent = tip;
        tipBox.className = "";
    }
}

function newGame()
{
    history.go(0);
}

let game = new Game();
render( game );
listenForInput( game );