window.AUDIO_MAPPING_SR = {
  "Znati": "ZNATI",
  "Odgovarati": "ODGOVARATI",
  "Pitati": "PITATI",
  "Pevati": "PEVATI",
  "Razgovarati": "RAZGOVARATI",
  "Gurati": "GURATI",
  "Plivati": "PLIVATI",
  "Štampati": "STAMPATI",
  "Kucati": "KUCATI",
  "Gledati": "GLEDATI",
  "Čuvati": "CUVATI",
  "Uspevati": "USPEVATI",
  "Sklanjati": "SKLANJATI",
  "Postavljati": "POSTAVLJATI",
  "Sipati": "SIPATI",
  "Kuvati": "KUVATI",
  "Spremati": "SPREMATI",
  "Čitati": "CITATI",
  "Plaćati": "PLACATI",
  "Smatrati": "SMATRATI",
  "Spavati": "SPAVATI",
  "Ručati": "RUCATI",
  "Večerati": "VECERATI",
  "Ponavljati": "PONAVLJATI",
  "Otvarati": "OTVARATI",
  "Zatvarati": "ZATVARATI",
  "Čekati": "CEKATI",
  "Slikati": "SLIKATI",
  "Imati": "IMATI",
  "Nemati": "NEMATI",
  "Aplicirati": "APLICIRATI",
  "Bacati": "BACATI",
  "Računati": "RACUNATI",
  "Uzimati": "UZIMATI",
  "Birati": "BIRATI",
  "Pokušavati": "POKUSAVATI",
  "Probati": "PROBATI",
  "Čestitati": "CESTITATI",
  "Fenirati se": "FENIRATI_SE",
  "Šetati se": "SETATI_SE",
  "Skidati se": "SKIDATI_SE",
  "Umivati se": "UMIVATI_SE",
  "Tuširati се": "TUSIRATI",
  "Kupati se": "KUPATI_SE",
  "Svađati se": "SVADJATI_SE",
  "Ležati": "LEZATI",
  "Ćutati": "CUTATI",
  "Držati": "DRZATI",
  "Postojati": "POSTOJATI",
  "Trčati": "TRCATI",
  "Bežati": "BEZATI",
  "Stajati": "STAJATI",
  "Brojati": "BROJATI",
  "Bojati se": "BOJATI_SE",
  "Voleti": "VOLETI",
  "Sedeti": "SEDETI",
  "Živeti": "ZIVETI",
  "Videti": "VIDETI",
  "Mrzeti": "MRZETI",
  "Štedeti": "STEDETI",
  "Želeti": "ZELETI",
  "Lepiti": "LEPITI",
  "Pržiti": "PRZITI",
  "Praviti": "PRAVITI",
  "Cediti": "CEDITI",
  "Tražiti": "TRAZITI",
  "Voziti": "VOZITI",
  "Paziti": "PAZITI",
  "Maziti": "MAZITI",
  "Vaditi": "VADITI",
  "Dolaziti": "DOLAZITI",
  "Puniti": "PUNITI",
  "Misliti": "MISLITI",
  "Čistiti": "CISTITI",
  "Raditi": "RADITI",
  "Koristiti": "KORISTITI",
  "Donositi": "DONOSITI",
  "Pratiti": "PRATITI",
  "Ulaziti": "ULAZITI",
  "Izlaziti": "IZLAZITI",
  "Nuditi": "NUDITI",
  "Ljubiti": "LJUBITI",
  "Braniti": "BRANITI",
  "Pušiti": "PUSITI",
  "Baviti se": "BAVITI_SE",
  "Družiti se": "DRUZITI_SE",
  "Šaliti se": "SALITI_SE",
  "Seliti se": "SELITI_SE",
  "Truditi se": "TRUDITI_SE",
  "Snalaziti se": "SNALAZITI_SE",
  "Zvati": "ZVATI",
  "Prati": "PRATI",
  "Slati": "SLATI",
  "Piti": "PITI",
  "Kriti": "KRITI",
  "Ostajati": "OSTAJATI",
  "Počinjati": "POCINJATI",
  "Kašljati": "KASLJATI",
  "Lagati": "LAGATI",
  "Polagati": "POLAGATI",
  "Predlagati": "PREDLAGATI",
  "Pomagati": "POMAGATI",
  "Stizati": "STIZATI",
  "Dizati": "DIZATI",
  "Mazati": "MAZATI",
  "Naručivati": "NARUCIVATI",
  "Sređivati": "SREDJIVATI",
  "Istraživati": "ISTRAZIVATI",
  "Davati": "DAVATI",
  "Dodavati": "DODAVATI",
  "Prodavati": "PRODAVATI",
  "Pakovati": "PAKOVATI",
  "Verovati": "VEROVATI",
  "Letovati": "LETOVATI",
  "Kupovati": "KUPOVATI",
  "Putovati": "PUTOVATI",
  "Napredovati": "NAPREDOVATI",
  "Doručkovati": "DORUCKOVATI",
  "Iznajmljivati": "IZNAJMLJIVATI",
  "Prijavljivati se": "PRIJAVLJIVATI_SE",
  "Jesti": "JESTI",
  "Ići": "ICI",
  "Seći": "SECI",
  "Peći": "PECI",
  "Vući": "VUCI",
  "Tući": "TUCI",
  "Vikati": "VIKATI",
  "Rezervisati": "REZERVISATI",
  "Brisati": "BRISATI",
  "Pisati": "PISATI",
  "Skretati": "SKRETATI",
  "Okretati se": "OKRETATI_SE",
  "Brijati": "BRIJATI",
  "Dobiti": "DOBITI",
  "Brinuti": "BRINUTI",
  "Hteti": "HTETI",
  "Ne hteti": "NE_HTETI",
  "Moći": "MOCI",
  "Razumeti": "RAZUMETI"
};
